# Basic usages of Numpy

In [3]:
import numpy as np
import time

## Create numpy array and matrix - Part 1

In [14]:
### 直接数字创建 dtype=int64 by default
data_a = np.array([4])
print(data_a, data_a.shape)

data_a = np.array([1, 2, 3])
print(data_a.shape, data_a.dtype)

### 创建随机矩阵 dtype=float64 by default
data_a = np.random.randn(3, 2, 5)
print(data_a.shape, data_a.dtype)

### 创建全0, 全1矩阵
data_a = np.zeros((5, 3))
print("zero matrix: \n", data_a, data_a.dtype)

data_a = np.ones(5)
print("ones:", data_a.shape, data_a)

## Create OpenCV image type matrix
frame = np.ones((400, 400, 3), np.uint8) # 指定数据类型

## Create bool type vector
target_class_mask = np.zeros(52, dtype=np.bool) # (52,) all False
print("target_class_mask:", target_class_mask.shape, target_class_mask.dtype, target_class_mask[:2])

for i in range(0, 5):
    print(i)

[4] (1,)
(3,) int64
(3, 2, 5) float64
zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
ones: (5,) [1. 1. 1. 1. 1.]
target_class_mask: (52,) bool [False False]
0
1
2
3
4


## Create numpy array and matrix - Part 2

In [ ]:

### 创建大尺寸矩阵,测试耗时
start = time.time()
img = np.zeros((720, 1080, 1), np.uint8)
print(f"Elapsed time is {time.time() - start}s")

### 矩阵列表转为矩阵 np.asarray用法, 会自动多加一维
list_feat = [np.arange(0, 10), np.arange(10, 20)]
list_arr = np.array(list_feat)
print("list_arr", list_arr.shape)

mels = [np.arange(0, 10), np.arange(10, 20)]
mels = np.asarray(mels)
print("mels", mels, mels.shape)

data_b = [np.random.randn(5,2), np.random.randn(5,2), np.random.randn(5,2)]
# data_b = [np.random.randn(2,), np.random.randn(2,), np.random.randn(2,)]
print("data_b")
data_b = np.asarray(data_b)
print(data_b.shape)

data_c = np.vstack(data_b)
print(data_c.shape)
print(data_c)

## Create numpy array and matrix - Part 3

In [3]:
params_mat = np.asarray([np.random.rand(10), np.random.rand(10)])
print(params_mat.shape, params_mat.dtype)

## Create a all 0 matrix with same size with a existing one
params_mat_zero = np.zeros_like(params_mat)
print(params_mat_zero, params_mat_zero.shape, params_mat_zero.dtype)

img = np.zeros((720,))
print(img.shape)


(2, 10) float64
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] (2, 10) float64
(720,)


## Convert array data type

In [3]:
arr = np.array([1, 2, 3, 4]) ## np.int64 by default
print(arr.shape, arr.dtype)

arr = arr.astype(np.float32)
print(arr.dtype)


(4,) int64
float32


In [3]:
size = 4
nopeak_mask = np.triu(np.ones((1, size, size)), k=1).astype('uint8')

print(nopeak_mask)



[[[0 1 1 1]
  [0 0 1 1]
  [0 0 0 1]
  [0 0 0 0]]]


In [9]:
def use_as_matrix():
    A = np.array([[1,2,3], [4,5,6],[7,8,9]])
    print('A=', type(A), A.shape)
    print(A)

    ## define column matrix
    B = np.array([[1], [2], [3]])
    print(B, B.shape)

     ## define row matrix
    C = np.array([[1, 2, 3]])
    print(C, C.shape)

def use_as_array():
    A = np.arange(1,10,1)
    print(A, A.shape)

    B = np.linspace(1, 10, 10)
    print(B, B.shape, B.dtype)

use_as_matrix()

use_as_array()

A= <class 'numpy.ndarray'> (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]] (3, 1)
[[1 2 3]] (1, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] (10,) float64


## Slice the matrix

In [12]:
input_data = np.random.rand(8, 4, 3)
# print(input_data, input_data.shape)

def split_given_size(a, size):
    return np.split(a, np.arange(size,len(a),size))

splited = split_given_size(input_data, 3)
print(len(splited))

for l in splited:
    print(l)

3
[[[0.95027973 0.69408122 0.71595983]
  [0.66640867 0.23299819 0.4384967 ]
  [0.45917007 0.79473264 0.79113138]
  [0.77783361 0.32157749 0.35147845]]

 [[0.23483744 0.04922651 0.74468683]
  [0.92249776 0.62622845 0.12819601]
  [0.36282255 0.51996465 0.37164608]
  [0.17878366 0.48804741 0.6134491 ]]

 [[0.51119914 0.9876817  0.88428926]
  [0.15614281 0.0555798  0.98423752]
  [0.41431375 0.0286296  0.23056143]
  [0.78584942 0.44622952 0.68192269]]]
[[[8.72819614e-01 4.29538874e-01 8.89550990e-01]
  [3.09392114e-01 1.38051520e-01 2.04889840e-01]
  [6.22587850e-01 3.89298395e-02 3.13468444e-01]
  [1.94154435e-01 4.46350695e-01 2.09556283e-02]]

 [[2.97046346e-01 5.83020424e-01 1.64605335e-01]
  [4.55808246e-01 4.68072619e-03 1.31792672e-01]
  [5.27513709e-01 6.28081684e-01 1.84060611e-01]
  [1.92206609e-02 2.97332961e-01 9.87666197e-01]]

 [[2.62972314e-04 9.62267989e-01 6.09836736e-01]
  [8.05506729e-01 3.62284906e-01 4.27476706e-01]
  [7.33294730e-01 7.08696287e-01 4.22778763e-01]
  [3.

In [4]:
import numpy as np

data = 50

data_b = np.clip(data, 20, 40)
print(data_b)

40


## Matrix basic properties

In [6]:
data_a = np.random.randn(3, 2, 4, 10)
print(data_a.shape, data_a.dtype)

print(data_a.ndim)

(3, 2, 4, 10) float64
4


In [3]:
img_batch = np.random.randn(5, 16, 16, 3)
images = img_batch[..., ::-1].transpose(0,3,1,2)
print(images.shape)

(5, 3, 16, 16)


## Add new axis

In [32]:
gray_img = np.random.rand(96, 96)
print(gray_img.shape)
print(gray_img[:3, :3])

gray_img = gray_img[..., np.newaxis]
print(gray_img.shape)
print(gray_img[:3, :3])

mean_rgb = np.random.randn(1,3)
x = np.expand_dims(mean_rgb, 0)
print(mean_rgb.shape, x.shape)
print(mean_rgb)
print(x)

arr = np.array([1, 2, 3])
arr = arr[None, None, :]
print(arr.shape)

(96, 96)
[[0.55265135 0.4098663  0.6338407 ]
 [0.28554012 0.39664046 0.81507042]
 [0.82099444 0.35540592 0.79751556]]
(96, 96, 1)
[[[0.55265135]
  [0.4098663 ]
  [0.6338407 ]]

 [[0.28554012]
  [0.39664046]
  [0.81507042]]

 [[0.82099444]
  [0.35540592]
  [0.79751556]]]
(1, 3) (1, 1, 3)
[[-0.29139472 -0.44647676  1.47266128]]
[[[-0.29139472 -0.44647676  1.47266128]]]
(1, 1, 3)


## Some useful functions

In [5]:
### Usage of transpose function
x1 = np.random.rand(5, 96, 96, 3)
x1 = x1.transpose(3, 0, 1, 2)
print(x1.shape)
x1 = x1[:,:,x1.shape[2]//2:]
print(x1.shape)

size = 3
arr = np.arange(size, 10, size)
print(arr)

(3, 5, 96, 96)
(3, 5, 48, 96)
[3 6 9]


In [5]:
img = np.random.rand(100,96,3)
H, W = img.shape[:2]
print(H, W)

ValueError: too many values to unpack (expected 2)

## Stack like operations

In [8]:
import numpy as np

def hstack_example():
    black_pixels_left = np.zeros((224, 0, 3), dtype=np.uint8)
    scaled_mask = np.zeros((224, 224, 3), dtype=np.uint8)
    black_pixels_right = np.zeros((224, 2, 3), dtype=np.uint8)

    ## Stack the array list in the horizontal direction, will sum the columns
    hstacked_array = np.hstack([black_pixels_left, scaled_mask, black_pixels_right])
    print(hstacked_array.shape)

hstack_example()

## simple one
subject_idx = [0, 1, 2, 3]
subject_idx = np.stack(subject_idx)
print(subject_idx, subject_idx.shape, type(subject_idx))

data_b = [np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3)]
print(f"input list length is {len(data_b)}")
result = np.stack(data_b)
print("stack result: ", result.shape)

data_c = np.stack(data_b, axis=3)
print("stack axis=3:", data_c.shape)

im = np.expand_dims(data_c, axis=0)
print(im.shape)

centers = [np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3])]
result = np.stack(centers)
print(result.shape)

timestamp = [1, 2, 4, 5]
result = np.array(timestamp).reshape(-1, 1)
print(result.shape, result)


def stack_array():
    a = np.random.rand(5,3)
    b = np.random.rand(5,3)

    array_list = [a, b]
    c = np.stack(array_list, axis=0)
    print(c)
    print(c.shape)

(224, 226, 3)
[0 1 2 3] (4,) <class 'numpy.ndarray'>
input list length is 4
stack result:  (4, 16, 16, 3)
stack axis=3: (16, 16, 3, 4)
(1, 16, 16, 3, 4)
(4, 3)
(4, 1) [[1]
 [2]
 [4]
 [5]]


## Concatenate operation

In [15]:
def combine_arrays():
    a = np.random.rand(3, 96, 96)
    b = np.random.rand(3, 96, 96)
    c = np.random.rand(3, 96, 96)
    d = np.random.rand(3, 96, 96)
    window = [a, b, c, d]

    window_np = np.asarray(window)
    window_np2 = window_np.copy()
    print(window_np.shape)

    x = np.concatenate([window_np, window_np2], axis=0)
    print(x.shape)

    
window = [np.random.randn(16,16,1), np.random.randn(16,16,1), np.random.randn(16,16,1), np.random.randn(16,16,1)]
result = np.concatenate(window)
print("concatenate result: ", result.shape)

result = np.concatenate(window, axis=1)
print("concatenate axis=1: ", result.shape)

result = np.concatenate(window, axis=2)
print("concatenate axis=2: ", result.shape)

concatenate result:  (64, 16, 1)
concatenate axis=1:  (16, 64, 1)
concatenate axis=2:  (16, 16, 4)


## Random operation

In [14]:
train_split = np.arange(0, 100)  # shape (100, )
print(train_split, train_split.shape)

train_i = np.random.choice(train_split)
print(train_i)

rand_perm = np.random.permutation(10)
print(rand_perm)
proportion = (0., 1.)
proportion_idx = (int(proportion[0] * len(rand_perm)), int(proportion[1] * len(rand_perm)))
print(proportion_idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
70
[2 7 3 1 8 0 5 4 9 6]
(0, 10)


## Math operations

In [20]:
## https://numpy.org/doc/stable/reference/generated/numpy.stack.html
arrays = [np.random.randn(3, 4) for _ in range(10)]
print(len(arrays))
np.stack(arrays, axis=0).shape


arr_a = np.random.rand(5, 2)
print(arr_a, arr_a.shape)

arr_b = arr_a + np.array([1, 20])
print(arr_b)

## Substract the matrix
MIN_MOTION = [-0.00916614, -0.02674509, -0.0166305]
MAX_MOTION = [0.01042878, 0.01583716, 0.01325295]
diff = np.array(MAX_MOTION) - np.array(MIN_MOTION)
print(diff, diff.shape)


## Divide the matrix
input_data = np.random.rand(3, 2, 3)
print(input_data)
output = input_data / np.expand_dims(diff, axis=0)
print(output)

10
[[0.13961726 0.14763359]
 [0.07032274 0.90661042]
 [0.39364    0.11111287]
 [0.52464075 0.57078679]
 [0.91484223 0.00106053]] (5, 2)
[[ 1.13961726 20.14763359]
 [ 1.07032274 20.90661042]
 [ 1.39364    20.11111287]
 [ 1.52464075 20.57078679]
 [ 1.91484223 20.00106053]]
[0.01959492 0.04258225 0.02988345] (3,)
[[[0.94079425 0.06929563 0.5931752 ]
  [0.39409165 0.88012489 0.62131803]]

 [[0.71231883 0.19532403 0.54097216]
  [0.95402267 0.3010743  0.257091  ]]

 [[0.413671   0.66827731 0.53900185]
  [0.73407962 0.78200114 0.77947188]]]
[[[48.01215063  1.6273361  19.84962259]
  [20.11192939 20.66882063 20.79137563]]

 [[36.35221911  4.5869823  18.1027343 ]
  [48.68724472  7.07041793  8.60312307]]

 [[21.11113499 15.69379982 18.03680145]
  [37.46275159 18.36448608 26.08373118]]]


In [49]:
import numpy as np

# Matrix divide by a vector
matrix = np.array([[2,2,2],
                   [4,4,4],
                   [6,6,6],
                   [6,6,6]])
# matrix = np.expand_dims(matrix, axis=1)
vector = np.array([2,4,6])

def test_divide(matrix, vector):
    matrix = matrix / vector[:, None]
    print(matrix)

def test_multiply(matrix, vector):
    output = np.multiply(matrix, vector)
    print(output)

test_multiply(matrix, vector)

[[ 4  8 12]
 [ 8 16 24]
 [12 24 36]
 [12 24 36]]


## Compute the delta array

In [7]:
timestamp = np.random.randint((1, 10), size=(10, 1))
print(timestamp)

delta_t = timestamp[1:] - timestamp[0:-1]
print(delta_t.shape)

## Assume these are some objects 3D coordinates
center = np.random.randn(10, 3)
print(center[:3])
deltat_center = center[1:] - center[0:-1]
print(deltat_center.shape)
distance = np.linalg.norm(deltat_center, axis=1)
print("distance", type(distance), distance.shape, distance)

mean_distance = np.mean(distance)
print("mean distance", mean_distance)

[[0]
 [6]
 [0]
 [6]
 [0]
 [1]
 [0]
 [8]
 [0]
 [6]]
(9, 1)
[[1.45146271 0.362749   1.35514625]
 [0.51994227 0.86556387 0.02524436]
 [0.59527528 0.56022706 0.78244459]]
(9, 3)
distance <class 'numpy.ndarray'> (9,) [1.69976238 0.81991331 1.09407121 2.81901685 2.437771   1.52364857
 2.51824093 1.32703159 0.97221643]
mean distance 1.6901858071084175


In [3]:
input_list = [0, -1, 21, 3]
d = np.clip(input_list, 0, None)
print(d)

[ 0  0 21  3]
