# Basic usages of Numpy

In [2]:
import numpy as np
import time

## Create numpy array and matrix

In [16]:
### 直接数字创建
data_a = np.array([1, 2, 3])
print(data_a.shape ,type(data_a.shape))

### 创建随机矩阵
data_a = np.random.randn(3, 2, 5)
print(data_a.shape)

### 创建全0, 全1矩阵
data_a = np.zeros((5, 3))
print("zero matrix: \n", data_a)

frame = np.ones((400, 400, 3), np.uint8) # 指定数据类型

### 创建大尺寸矩阵,测试耗时
start = time.time()
img = np.zeros((720, 1080, 1), np.uint8)
print(f"Elapsed time is {time.time() - start}s")

### 矩阵列表转为矩阵 np.asarray用法, 会自动多加一维
mels = [np.arange(0, 10), np.arange(10, 20)]
mels = np.asarray(mels)
print(mels, mels.shape)

data_b = [np.random.randn(5,2), np.random.randn(5,2), np.random.randn(5,2)]
# data_b = [np.random.randn(2,), np.random.randn(2,), np.random.randn(2,)]
print("data_b")
data_b = np.asarray(data_b)
print(data_b.shape)

data_c = np.vstack(data_b)
print(data_c.shape)
print(data_c)

(3,) <class 'tuple'>
(3, 2, 5)
zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Elapsed time is 0.0003974437713623047s
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] (2, 10)
data_b
(3, 5, 2)
(15, 2)
[[ 1.23336346  0.25446112]
 [-0.48790733 -0.90793776]
 [ 0.46485831 -1.33619305]
 [ 0.16210728  0.64667491]
 [-1.25481131 -0.16355975]
 [-0.75479062  0.35162521]
 [ 1.07775505  0.81670256]
 [ 0.82235074 -1.09437361]
 [-0.73553909 -0.30764736]
 [ 0.14246179 -0.41389297]
 [-0.48814873 -1.81104669]
 [-0.25694855  0.74902972]
 [-2.47351122  0.65861421]
 [ 0.61630761  0.63580667]
 [ 3.04295363 -1.72037552]]


## Some useful functions

In [11]:
### Usage of transpose function
x1 = np.random.rand(5, 96, 96, 3)
x1 = x1.transpose(3, 0, 1, 2)
print(x1.shape)
x1 = x1[:,:,x1.shape[2]//2:]
print(x1.shape)


(3, 5, 96, 96)
(3, 5, 48, 96)


In [5]:
img = np.random.rand(100,96,3)
H, W = img.shape[:2]
print(H, W)

ValueError: too many values to unpack (expected 2)

## Stack like operations

In [4]:
data_b = [np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3)]
data_c = np.stack(data_b, axis=3)
print(data_c.shape)

im = np.expand_dims(data_c,axis=0)
print(im.shape)

(16, 16, 3, 4)
(1, 16, 16, 3, 4)


## Random operation

In [8]:
train_split = np.arange(0, 100)  # shape (100, )
print(train_split, train_split.shape)

train_i = np.random.choice(train_split)
print(train_i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
56


## Math operations

In [19]:
## https://numpy.org/doc/stable/reference/generated/numpy.stack.html
arrays = [np.random.randn(3, 4) for _ in range(10)]
print(len(arrays))
np.stack(arrays, axis=0).shape


arr_a = np.random.rand(5, 2)
print(arr_a, arr_a.shape)

arr_b = arr_a + np.array([1, 20])
print(arr_b)

10
[[0.6030159  0.23681032]
 [0.90250015 0.27786118]
 [0.01272317 0.15606097]
 [0.74395489 0.43585537]
 [0.90958557 0.60175309]] (5, 2)
[[ 1.6030159  20.23681032]
 [ 1.90250015 20.27786118]
 [ 1.01272317 20.15606097]
 [ 1.74395489 20.43585537]
 [ 1.90958557 20.60175309]]


In [5]:
import platform
platform.release()

'5.8.0-63-generic'