# Basic usages of Numpy

In [2]:
import numpy as np

## Create numpy array and matrix

In [19]:
### 直接数字创建
data_a = np.array([1, 2, 3])
print(data_a.shape ,type(data_a.shape))

### 创建随机矩阵
data_a = np.random.randn(3, 2, 5)
print(data_a.shape)

### 矩阵列表转为矩阵 np.asarray用法, 会自动多加一维
mels = [np.arange(0, 10), np.arange(10, 20)]
mels = np.asarray(mels)
print(mels, mels.shape)

data_b = [np.random.randn(3,2), np.random.randn(3,2), np.random.randn(3,2)]
data_b = [np.random.randn(2,), np.random.randn(2,), np.random.randn(2,)]
print(data_b)
data_b = np.asarray(data_b)
print(data_b.shape)

data_c = np.vstack(data_b)
print(data_c.shape)
print(data_c)

(3,) <class 'tuple'>
(3, 2, 5)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] (2, 10)
[array([ 0.76442444, -0.50738742]), array([0.35320213, 1.04992197]), array([-1.77867327,  0.84270484])]
(3, 2)
(3, 2)
[[ 0.76442444 -0.50738742]
 [ 0.35320213  1.04992197]
 [-1.77867327  0.84270484]]


## Stack like operations

In [4]:
data_b = [np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3)]
data_c = np.stack(data_b, axis=3)
print(data_c.shape)

im = np.expand_dims(data_c,axis=0)
print(im.shape)

(16, 16, 3, 4)
(1, 16, 16, 3, 4)


## Random operation

In [8]:
train_split = np.arange(0, 100)  # shape (100, )
print(train_split, train_split.shape)

train_i = np.random.choice(train_split)
print(train_i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
56


## Math operations

In [5]:
## https://numpy.org/doc/stable/reference/generated/numpy.stack.html
arrays = [np.random.randn(3, 4) for _ in range(10)]
print(len(arrays))
np.stack(arrays, axis=0).shape

10


(10, 3, 4)