# Basic usages of Numpy

In [2]:
import numpy as np
import time

## Create numpy array and matrix - Part 1

In [7]:
### 直接数字创建 dtype=int64 by default
data_a = np.array([1, 2, 3])
print(data_a.shape, data_a.dtype)

### 创建随机矩阵 dtype=float64 by default
data_a = np.random.randn(3, 2, 5)
print(data_a.shape, data_a.dtype)

### 创建全0, 全1矩阵
data_a = np.zeros((5, 3))
print("zero matrix: \n", data_a, data_a.dtype)

data_a = np.ones(5)
print("ones:", data_a.shape, data_a)

## Create OpenCV image type matrix
frame = np.ones((400, 400, 3), np.uint8) # 指定数据类型

## Create bool type vector
target_class_mask = np.zeros(52, dtype=np.bool) # (52,) all False
print("target_class_mask:", target_class_mask.shape, target_class_mask.dtype, target_class_mask[:2])

for i in range(0, 5):
    print(i)

(3,) int64
(3, 2, 5) float64
zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
ones: (5,) [1. 1. 1. 1. 1.]
target_class_mask: (52,) bool [False False]
0
1
2
3
4


## Create numpy array and matrix - Part 2

In [ ]:

### 创建大尺寸矩阵,测试耗时
start = time.time()
img = np.zeros((720, 1080, 1), np.uint8)
print(f"Elapsed time is {time.time() - start}s")

### 矩阵列表转为矩阵 np.asarray用法, 会自动多加一维
list_feat = [np.arange(0, 10), np.arange(10, 20)]
list_arr = np.array(list_feat)
print("list_arr", list_arr.shape)

mels = [np.arange(0, 10), np.arange(10, 20)]
mels = np.asarray(mels)
print("mels", mels, mels.shape)

data_b = [np.random.randn(5,2), np.random.randn(5,2), np.random.randn(5,2)]
# data_b = [np.random.randn(2,), np.random.randn(2,), np.random.randn(2,)]
print("data_b")
data_b = np.asarray(data_b)
print(data_b.shape)

data_c = np.vstack(data_b)
print(data_c.shape)
print(data_c)

In [9]:
def use_as_matrix():
    A = np.array([[1,2,3], [4,5,6],[7,8,9]])
    print('A=', type(A), A.shape)
    print(A)

    ## define column matrix
    B = np.array([[1], [2], [3]])
    print(B, B.shape)

     ## define row matrix
    C = np.array([[1, 2, 3]])
    print(C, C.shape)

def use_as_array():
    A = np.arange(1,10,1)
    print(A, A.shape)

    B = np.linspace(1, 10, 10)
    print(B, B.shape, B.dtype)

use_as_matrix()

use_as_array()

A= <class 'numpy.ndarray'> (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]] (3, 1)
[[1 2 3]] (1, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] (10,) float64


In [3]:
img_batch = np.random.randn(5, 16, 16, 3)
images = img_batch[..., ::-1].transpose(0,3,1,2)
print(images.shape)

(5, 3, 16, 16)


## Add new axis

In [6]:
gray_img = np.random.rand(96, 96)
print(gray_img.shape)
print(gray_img[:3, :3])

gray_img = gray_img[..., np.newaxis]
print(gray_img.shape)
print(gray_img[:3, :3])

mean_rgb = np.random.randn(1,3)
x = np.expand_dims(mean_rgb, 0)
print(mean_rgb.shape, x.shape)
print(mean_rgb)
print(x)

(96, 96)
[[0.68711016 0.25743167 0.3918882 ]
 [0.02868399 0.59827092 0.48402818]
 [0.56622452 0.34395004 0.25476914]]
(96, 96, 1)
[[[0.68711016]
  [0.25743167]
  [0.3918882 ]]

 [[0.02868399]
  [0.59827092]
  [0.48402818]]

 [[0.56622452]
  [0.34395004]
  [0.25476914]]]
(1, 3) (1, 1, 3)
[[ 0.40001691 -0.79931382 -1.61001719]]
[[[ 0.40001691 -0.79931382 -1.61001719]]]


## Some useful functions

In [11]:
### Usage of transpose function
x1 = np.random.rand(5, 96, 96, 3)
x1 = x1.transpose(3, 0, 1, 2)
print(x1.shape)
x1 = x1[:,:,x1.shape[2]//2:]
print(x1.shape)


(3, 5, 96, 96)
(3, 5, 48, 96)


In [5]:
img = np.random.rand(100,96,3)
H, W = img.shape[:2]
print(H, W)

ValueError: too many values to unpack (expected 2)

## Stack like operations

In [23]:
data_b = [np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3), np.random.randn(16,16,3)]
print(f"input list length is {len(data_b)}")
result = np.stack(data_b)
print("stack result: ", result.shape)

data_c = np.stack(data_b, axis=3)
print("stack axis=3:", data_c.shape)

im = np.expand_dims(data_c, axis=0)
print(im.shape)

centers = [np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3])]
result = np.stack(centers)
print(result.shape)

timestamp = [1, 2, 4, 5]
result = np.array(timestamp).reshape(-1, 1)
print(result.shape, result)


def stack_array():
    a = np.random.rand(5,3)
    b = np.random.rand(5,3)

    array_list = [a, b]
    c = np.stack(array_list, axis=0)
    print(c)
    print(c.shape)

input list length is 4
stack result:  (4, 16, 16, 3)
stack axis=3: (16, 16, 3, 4)
(1, 16, 16, 3, 4)
(4, 3)
(4, 1) [[1]
 [2]
 [4]
 [5]]


## Concatenate operation

In [15]:
def combine_arrays():
    a = np.random.rand(3, 96, 96)
    b = np.random.rand(3, 96, 96)
    c = np.random.rand(3, 96, 96)
    d = np.random.rand(3, 96, 96)
    window = [a, b, c, d]

    window_np = np.asarray(window)
    window_np2 = window_np.copy()
    print(window_np.shape)

    x = np.concatenate([window_np, window_np2], axis=0)
    print(x.shape)

    
window = [np.random.randn(16,16,1), np.random.randn(16,16,1), np.random.randn(16,16,1), np.random.randn(16,16,1)]
result = np.concatenate(window)
print("concatenate result: ", result.shape)

result = np.concatenate(window, axis=1)
print("concatenate axis=1: ", result.shape)

result = np.concatenate(window, axis=2)
print("concatenate axis=2: ", result.shape)

concatenate result:  (64, 16, 1)
concatenate axis=1:  (16, 64, 1)
concatenate axis=2:  (16, 16, 4)


## Random operation

In [14]:
train_split = np.arange(0, 100)  # shape (100, )
print(train_split, train_split.shape)

train_i = np.random.choice(train_split)
print(train_i)

rand_perm = np.random.permutation(10)
print(rand_perm)
proportion = (0., 1.)
proportion_idx = (int(proportion[0] * len(rand_perm)), int(proportion[1] * len(rand_perm)))
print(proportion_idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
70
[2 7 3 1 8 0 5 4 9 6]
(0, 10)


## Math operations

In [19]:
## https://numpy.org/doc/stable/reference/generated/numpy.stack.html
arrays = [np.random.randn(3, 4) for _ in range(10)]
print(len(arrays))
np.stack(arrays, axis=0).shape


arr_a = np.random.rand(5, 2)
print(arr_a, arr_a.shape)

arr_b = arr_a + np.array([1, 20])
print(arr_b)

## Divide the matrix


10
[[0.6030159  0.23681032]
 [0.90250015 0.27786118]
 [0.01272317 0.15606097]
 [0.74395489 0.43585537]
 [0.90958557 0.60175309]] (5, 2)
[[ 1.6030159  20.23681032]
 [ 1.90250015 20.27786118]
 [ 1.01272317 20.15606097]
 [ 1.74395489 20.43585537]
 [ 1.90958557 20.60175309]]


In [5]:
import platform
platform.release()

'5.8.0-63-generic'

## Compute the delta array

In [7]:
timestamp = np.random.randint((1, 10), size=(10, 1))
print(timestamp)

delta_t = timestamp[1:] - timestamp[0:-1]
print(delta_t.shape)

## Assume these are some objects 3D coordinates
center = np.random.randn(10, 3)
print(center[:3])
deltat_center = center[1:] - center[0:-1]
print(deltat_center.shape)
distance = np.linalg.norm(deltat_center, axis=1)
print("distance", type(distance), distance.shape, distance)

mean_distance = np.mean(distance)
print("mean distance", mean_distance)

[[0]
 [6]
 [0]
 [6]
 [0]
 [1]
 [0]
 [8]
 [0]
 [6]]
(9, 1)
[[1.45146271 0.362749   1.35514625]
 [0.51994227 0.86556387 0.02524436]
 [0.59527528 0.56022706 0.78244459]]
(9, 3)
distance <class 'numpy.ndarray'> (9,) [1.69976238 0.81991331 1.09407121 2.81901685 2.437771   1.52364857
 2.51824093 1.32703159 0.97221643]
mean distance 1.6901858071084175


In [3]:
input_list = [0, -1, 21, 3]
d = np.clip(input_list, 0, None)
print(d)

[ 0  0 21  3]
