In [1]:
import numpy as np

In [3]:
face_vertices = np.random.random((21, 5023, 3))

center = np.mean(face_vertices[0], axis=0)
print(center.shape)

(3,)


## Normalize

In [4]:
MIN_MOTION = np.array([-0.00916614, -0.02674509, -0.0166305])
MAX_MOTION = np.array([0.01042878, 0.01583716, 0.01325295])
DIFF_MOTION = MAX_MOTION - MIN_MOTION

print(DIFF_MOTION)

x = -MIN_MOTION / DIFF_MOTION
print(x)

[0.01959492 0.04258225 0.02988345]
[0.46778145 0.62808071 0.55651205]


In [19]:
length_list = [5, 5, 20, 80, 120]

index = 5

def fetch_data(length_list, index):
    assert index < length_list[-1]
    temp_idx = np.array(length_list) > index
    list_idx = np.where(temp_idx==True)[0][0]
    sub_idx = index
    if list_idx != 0:
        sub_idx = index - length_list[list_idx - 1]
    return list_idx, sub_idx

list_idx, sub_idx = fetch_data(length_list, index)
print(list_idx, sub_idx)

2 0


## MeshGrid

In [9]:
import numpy as np

grid_x, grid_y = np.mgrid[0:5:10j, 0:10:5j]
print(grid_x.shape, grid_y.shape)

print(grid_x)
# print(grid_y)

(10, 5) (10, 5)
[[0.         0.         0.         0.         0.        ]
 [0.55555556 0.55555556 0.55555556 0.55555556 0.55555556]
 [1.11111111 1.11111111 1.11111111 1.11111111 1.11111111]
 [1.66666667 1.66666667 1.66666667 1.66666667 1.66666667]
 [2.22222222 2.22222222 2.22222222 2.22222222 2.22222222]
 [2.77777778 2.77777778 2.77777778 2.77777778 2.77777778]
 [3.33333333 3.33333333 3.33333333 3.33333333 3.33333333]
 [3.88888889 3.88888889 3.88888889 3.88888889 3.88888889]
 [4.44444444 4.44444444 4.44444444 4.44444444 4.44444444]
 [5.         5.         5.         5.         5.        ]]


## Sort values

In [6]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)
print(ages, heights)

sorter = np.argsort(ages)
print(sorter)
print(ages[sorter]) # sort by ages
print(heights[sorter ])

[53 47 57 58 52 42 38 46 50 51] [157 151 167 204 159 151 206 173 160 177]
[6 5 7 1 8 9 4 0 2 3]
[38 42 46 47 50 51 52 53 57 58]
[206 151 173 151 160 177 159 157 167 204]


In [3]:
import numpy as np

img_resolution = 1024

img_resolution_log2 = int(np.log2(img_resolution))
block_resolutions = [2 ** i for i in range(2, img_resolution_log2 + 1)]
print(block_resolutions, len(block_resolutions))

[4, 8, 16, 32, 64, 128, 256, 512, 1024] 9
