In [3]:
import numpy as np

In [3]:
face_vertices = np.random.random((21, 5023, 3))

center = np.mean(face_vertices[0], axis=0)
print(center.shape)

(3,)


## Normalize

In [4]:
MIN_MOTION = np.array([-0.00916614, -0.02674509, -0.0166305])
MAX_MOTION = np.array([0.01042878, 0.01583716, 0.01325295])
DIFF_MOTION = MAX_MOTION - MIN_MOTION

print(DIFF_MOTION)

x = -MIN_MOTION / DIFF_MOTION
print(x)

[0.01959492 0.04258225 0.02988345]
[0.46778145 0.62808071 0.55651205]


In [19]:
length_list = [5, 5, 20, 80, 120]

index = 5

def fetch_data(length_list, index):
    assert index < length_list[-1]
    temp_idx = np.array(length_list) > index
    list_idx = np.where(temp_idx==True)[0][0]
    sub_idx = index
    if list_idx != 0:
        sub_idx = index - length_list[list_idx - 1]
    return list_idx, sub_idx

list_idx, sub_idx = fetch_data(length_list, index)
print(list_idx, sub_idx)

2 0


## MeshGrid

In [9]:
import numpy as np

grid_x, grid_y = np.mgrid[0:5:10j, 0:10:5j]
print(grid_x.shape, grid_y.shape)

print(grid_x)
# print(grid_y)

(10, 5) (10, 5)
[[0.         0.         0.         0.         0.        ]
 [0.55555556 0.55555556 0.55555556 0.55555556 0.55555556]
 [1.11111111 1.11111111 1.11111111 1.11111111 1.11111111]
 [1.66666667 1.66666667 1.66666667 1.66666667 1.66666667]
 [2.22222222 2.22222222 2.22222222 2.22222222 2.22222222]
 [2.77777778 2.77777778 2.77777778 2.77777778 2.77777778]
 [3.33333333 3.33333333 3.33333333 3.33333333 3.33333333]
 [3.88888889 3.88888889 3.88888889 3.88888889 3.88888889]
 [4.44444444 4.44444444 4.44444444 4.44444444 4.44444444]
 [5.         5.         5.         5.         5.        ]]
