# Useful operations in Numpy

In [1]:
import numpy as np

## tile matrix

In [9]:
src_frame = np.random.rand(3, 5, 1)
gray = np.random.randn(src_frame.shape[0], src_frame.shape[1], 1)
print(gray.shape)
print(gray)

rgb = np.tile(gray, (1,1,3))
print(rgb.shape)
print("rgb")
print(rgb)

(3, 5, 1)
[[[-0.22305194]
  [-0.13501087]
  [-1.62244612]
  [-1.20711516]
  [ 1.27533629]]

 [[-0.63114901]
  [-2.41434974]
  [-0.64912477]
  [ 1.08389685]
  [ 1.57379786]]

 [[ 1.36316033]
  [ 0.68273487]
  [ 0.49873773]
  [ 0.64152808]
  [ 1.32988197]]]
(3, 5, 3)
rgb
[[[-0.22305194 -0.22305194 -0.22305194]
  [-0.13501087 -0.13501087 -0.13501087]
  [-1.62244612 -1.62244612 -1.62244612]
  [-1.20711516 -1.20711516 -1.20711516]
  [ 1.27533629  1.27533629  1.27533629]]

 [[-0.63114901 -0.63114901 -0.63114901]
  [-2.41434974 -2.41434974 -2.41434974]
  [-0.64912477 -0.64912477 -0.64912477]
  [ 1.08389685  1.08389685  1.08389685]
  [ 1.57379786  1.57379786  1.57379786]]

 [[ 1.36316033  1.36316033  1.36316033]
  [ 0.68273487  0.68273487  0.68273487]
  [ 0.49873773  0.49873773  0.49873773]
  [ 0.64152808  0.64152808  0.64152808]
  [ 1.32988197  1.32988197  1.32988197]]]


## Compute the mean value

In [6]:
center = np.array([1,2,3.0])
mean = np.mean(center)

2.0
no error


## Compute the L2 norm

In [9]:
delta_center = np.array([2.0, 2, 2.0])
distance = np.linalg.norm(delta_center)
print(distance)

## Compute the matrix
data_src = np.array([[1.1, 3.1],
                     [1.9, 5.5],
                     [2.8, 6.4],
                     [1.4, 3.6],
                     [2.4, 5.6],
                     [3.1, 3.4],
                     [2.7, 3.3]])

print(data_src, data_src.shape)

data_distance = np.linalg.norm(data_src[-3] - data_src, axis=1)
print(data_distance)

center = np.array([1.25, 3.35])
center = np.array([2.367,5.867])
center = np.array([2.9, 3.35])
data_distance = np.linalg.norm(center - data_src, axis=1)
print(data_distance)

3.4641016151377544
[[1.1 3.1]
 [1.9 5.5]
 [2.8 6.4]
 [1.4 3.6]
 [2.4 5.6]
 [3.1 3.4]
 [2.7 3.3]] (7, 2)
[2.81780056 0.50990195 0.89442719 2.23606798 0.         2.30867928
 2.3194827 ]
[1.81727818 2.37118114 3.0516389  1.52069063 2.30488611 0.20615528
 0.20615528]


In [15]:
x = [410.0, 441.0, 473.0]
x = list(map(int, x))
print(x)

curve_x = np.linspace(x[0], x[-1], (x[-1]-x[0]))
print(curve_x)


[410, 441, 473]
[410.         411.01612903 412.03225806 413.0483871  414.06451613
 415.08064516 416.09677419 417.11290323 418.12903226 419.14516129
 420.16129032 421.17741935 422.19354839 423.20967742 424.22580645
 425.24193548 426.25806452 427.27419355 428.29032258 429.30645161
 430.32258065 431.33870968 432.35483871 433.37096774 434.38709677
 435.40322581 436.41935484 437.43548387 438.4516129  439.46774194
 440.48387097 441.5        442.51612903 443.53225806 444.5483871
 445.56451613 446.58064516 447.59677419 448.61290323 449.62903226
 450.64516129 451.66129032 452.67741935 453.69354839 454.70967742
 455.72580645 456.74193548 457.75806452 458.77419355 459.79032258
 460.80645161 461.82258065 462.83870968 463.85483871 464.87096774
 465.88709677 466.90322581 467.91935484 468.93548387 469.9516129
 470.96774194 471.98387097 473.        ]
