# Useful operations in Numpy

In [2]:
import numpy as np

## tile matrix

In [9]:
src_frame = np.random.rand(3, 5, 1)
gray = np.random.randn(src_frame.shape[0], src_frame.shape[1], 1)
print(gray.shape)
print(gray)

rgb = np.tile(gray, (1,1,3))
print(rgb.shape)
print("rgb")
print(rgb)

(3, 5, 1)
[[[-0.22305194]
  [-0.13501087]
  [-1.62244612]
  [-1.20711516]
  [ 1.27533629]]

 [[-0.63114901]
  [-2.41434974]
  [-0.64912477]
  [ 1.08389685]
  [ 1.57379786]]

 [[ 1.36316033]
  [ 0.68273487]
  [ 0.49873773]
  [ 0.64152808]
  [ 1.32988197]]]
(3, 5, 3)
rgb
[[[-0.22305194 -0.22305194 -0.22305194]
  [-0.13501087 -0.13501087 -0.13501087]
  [-1.62244612 -1.62244612 -1.62244612]
  [-1.20711516 -1.20711516 -1.20711516]
  [ 1.27533629  1.27533629  1.27533629]]

 [[-0.63114901 -0.63114901 -0.63114901]
  [-2.41434974 -2.41434974 -2.41434974]
  [-0.64912477 -0.64912477 -0.64912477]
  [ 1.08389685  1.08389685  1.08389685]
  [ 1.57379786  1.57379786  1.57379786]]

 [[ 1.36316033  1.36316033  1.36316033]
  [ 0.68273487  0.68273487  0.68273487]
  [ 0.49873773  0.49873773  0.49873773]
  [ 0.64152808  0.64152808  0.64152808]
  [ 1.32988197  1.32988197  1.32988197]]]


## Compute the mean value

In [6]:
center = np.array([1,2,3.0])
mean = np.mean(center)

2.0
no error


## Compute the L2 norm

In [9]:
delta_center = np.array([2.0, 2, 2.0])
distance = np.linalg.norm(delta_center)
print(distance)

3.4641016151377544
