## Some useful statistics operations in Numpy

## Count the True element in a matrix

In [2]:
import numpy as np

In [5]:
bool_array = np.array([[True, False, True, True, False]])
## Method 1
count = np.count_nonzero(bool_array)
print(count)

## Method 2
count = np.sum(bool_array)
print(count)

3
3


In [7]:
# Create a 2D Array of shape 3X3
arr_2d = np.array([[False, True, True],
                   [True, False, True],
                   [False, True, True]])
# Count of True elements in each column of 2D Numpy Array
count = np.count_nonzero(arr_2d, axis=0)
print('Print count of True elements in each column of the 2D array: ', count)

## Method 2
# Count of True elements in each column of 2D Numpy Array
count = np.sum(arr_2d, axis=0)
print('Print count of True elements in each column of the 2D array: ', count)

Print count of True elements in each column of the 2D array:  [1 2 3]
Print count of True elements in each column of the 2D array:  [1 2 3]


## Get the minimum and maximum value

In [5]:
## get the minimum value in a matrix
input_data = np.random.rand(5, 3)
min_value = np.min(input_data, axis=0, keepdims=True)
print(input_data, min_value, min_value.shape)


data_mat = np.random.rand(10, 3)
print(data_mat, data_mat.shape)
## Get the maximum value
max_value = np.max(data_mat)
print(max_value)

max_index_col = np.argmax(data_mat)
print(max_index_col)
result = np.where(data_mat == np.max(data_mat))
print(result)

an_array = np.array([[1, 1, 3], [1, 2, 1]])
max_index_col = np.argmax(an_array, axis=0)
print(max_index_col)

max_value = np.amax(an_array, axis=0)
print(max_value)



[[0.73155964 0.84471794 0.40168665]
 [0.9723163  0.41194422 0.27621136]
 [0.25482274 0.39703455 0.68578316]
 [0.73441348 0.19014257 0.15278848]
 [0.30227313 0.56898361 0.56728037]] [[0.25482274 0.19014257 0.15278848]] (1, 3)
[[0.62456871 0.06662612 0.61718846]
 [0.73209436 0.47422646 0.07507338]
 [0.89869101 0.00212754 0.65742475]
 [0.43698782 0.6229175  0.27997969]
 [0.30414124 0.97275782 0.38975317]
 [0.03417354 0.17691992 0.77054182]
 [0.40092282 0.26976624 0.78764653]
 [0.25276316 0.6510223  0.61487391]
 [0.59077671 0.66905503 0.10733837]
 [0.68456691 0.93680628 0.61438354]] (10, 3)
0.972757818145426
13
(array([4]), array([1]))
[0 1 0]
[1 2 3]


## Get the mask

In [6]:
input_arr = np.stack([np.arange(0, 10), np.arange(6, 16)]).transpose()

print(input_arr)

mask = input_arr[:, 1] < 10
print(mask, mask.shape)



[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]
 [ 8 14]
 [ 9 15]]
[ True  True  True  True False False False False False False] (10,)
