## Some useful statistics operations in Numpy

## Count the True element in a matrix

In [2]:
import numpy as np

In [5]:
bool_array = np.array([[True, False, True, True, False]])
## Method 1
count = np.count_nonzero(bool_array)
print(count)

## Method 2
count = np.sum(bool_array)
print(count)

3
3


In [7]:
# Create a 2D Array of shape 3X3
arr_2d = np.array([[False, True, True],
                   [True, False, True],
                   [False, True, True]])
# Count of True elements in each column of 2D Numpy Array
count = np.count_nonzero(arr_2d, axis=0)
print('Print count of True elements in each column of the 2D array: ', count)

## Method 2
# Count of True elements in each column of 2D Numpy Array
count = np.sum(arr_2d, axis=0)
print('Print count of True elements in each column of the 2D array: ', count)

Print count of True elements in each column of the 2D array:  [1 2 3]
Print count of True elements in each column of the 2D array:  [1 2 3]


## Get the minimum and maximum value

In [19]:
data_mat = np.random.rand(10, 3)
print(data_mat, data_mat.shape)
## Get the maximum value
max_value = np.max(data_mat)
print(max_value)

max_index_col = np.argmax(data_mat)
print(max_index_col)
result = np.where(data_mat == np.max(data_mat))
print(result)

an_array = np.array([[1, 1, 3], [1, 2, 1]])
max_index_col = np.argmax(an_array, axis=0)
print(max_index_col)

max_value = np.amax(an_array, axis=0)
print(max_value)


[[0.42682364 0.82377656 0.92206833]
 [0.81319599 0.04761575 0.90215187]
 [0.3114927  0.89842812 0.84336648]
 [0.98946052 0.8118595  0.40996233]
 [0.1447982  0.65966754 0.52442848]
 [0.6086152  0.75189729 0.85777447]
 [0.68288067 0.2590522  0.9862588 ]
 [0.27291868 0.14613746 0.05932045]
 [0.16865192 0.2624704  0.23186875]
 [0.77531185 0.19693128 0.23646268]] (10, 3)
0.9894605159446409
9
(array([3]), array([0]))
[0 1 0]
[1 2 3]


## Get the mask

In [6]:
input_arr = np.stack([np.arange(0, 10), np.arange(6, 16)]).transpose()

print(input_arr)

mask = input_arr[:, 1] < 10
print(mask, mask.shape)



[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]
 [ 8 14]
 [ 9 15]]
[ True  True  True  True False False False False False False] (10,)
