In [2]:
import numpy as np
from icecream import ic as print

## Use mask vector to extract subarray

In [4]:
mask_vector = np.array([1, 0, 1, 0, 0, 0, 1], dtype=bool)
print(mask_vector.shape)

data_index = np.arange(7)
print(data_index)

remain_index = data_index[~mask_vector]
print(remain_index)

ic| mask_vector.shape: (7,)
ic| data_index: array([0, 1, 2, 3, 4, 5, 6])
ic| remain_index: array([1, 3, 4, 5])


array([1, 3, 4, 5])

In [9]:
mask_vector = np.array([3, 0, 1, 0], dtype=np.int)
print(mask_vector.shape, mask_vector)

data_index = np.arange(7)
print(data_index)

remain_index = data_index[mask_vector]
print(remain_index)

ic| mask_vector.shape: (4,), mask_vector: array([3, 0, 1, 0])
ic| data_index: array([0, 1, 2, 3, 4, 5, 6])
ic| remain_index: array([3, 0, 1, 0])


array([3, 0, 1, 0])

## Use mask index to set value for another vector

In [8]:
data_index = np.zeros(7)
print(data_index)

mask_index = np.array([1, 0, 4], dtype=np.int)
data_index[mask_index] = 1

print(data_index)



ic| data_index: array([0., 0., 0., 0., 0., 0., 0.])
ic| data_index: array([1., 1., 0., 0., 1., 0., 0.])


array([1., 1., 0., 0., 1., 0., 0.])

## Access subarray

In [3]:
landmarks = np.random.randn(5, 68, 2)
print(landmarks.shape)

for lm in landmarks:
    print(lm.shape)

ic| landmarks.shape: (5, 68, 2)
ic| lm.shape: (68, 2)
ic| lm.shape: (68, 2)
ic| lm.shape: (68, 2)
ic| lm.shape: (68, 2)
ic| lm.shape: (68, 2)


## Linespace the array to get subarrray

In [8]:
import numpy as np
TimeList=[]
TimeList=np.linspace(0, 11-1, 11, dtype=np.int)
print(TimeList, len(TimeList), type(TimeList))

TimeList = list(TimeList)

print(type(TimeList))

[ 0  1  2  3  4  5  6  7  8  9 10] 11 <class 'numpy.ndarray'>
<class 'list'>
