# This notebook learns how to use list in Python3

In [2]:
import numpy as np
import random

## Create list - Part 1

In [4]:
def create_list():
    ### Basic initialization
    a = [1, 2, 3, 4, 5]
    print(a)

    ## Create list has repeated values
    num, N = 3, 10
    b = N * [num]
    print(b)

    ## Create list by using range
    list_num = list(range(0, 24, 4))
    print(list_num)

create_list()

view_id_list = [f"{i:02d}" for i in range(24)]
view_id_list = view_id_list[::4]
print(view_id_list)

[1, 2, 3, 4, 5]
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[0, 4, 8, 12, 16, 20]
['00', '04', '08', '12', '16', '20']


## Create list - Part 2

In [15]:
total_length = 36
stride = 5
fetch_length = 8

def get_all_valid_indices(total_length, fetch_length, stride):
    idx_list = list(range(0, total_length - fetch_length, stride))
    last_idx = total_length - fetch_length
    idx_list += [last_idx]
    return idx_list

idx_list = get_all_valid_indices(total_length, fetch_length, stride)
print(idx_list)

idx_list = list(range(0, total_length, stride))
print(idx_list)

slice_data = list(range(total_length))[28:28+fetch_length]
print(slice_data)

[0, 5, 10, 15, 20, 25, 28]
[0, 5, 10, 15, 20, 25, 30, 35]
[28, 29, 30, 31, 32, 33, 34, 35]


In [7]:
shape_num = 5
batch_num = 3

rt = [0, 2, 1]

iter_order = [(i, rt[j]) for i in range(shape_num) for j in range(batch_num)]
print(iter_order)

import numpy as np

data = np.random.randn(5, 3, 2, 1)
print(data)
selected = data[(1, 1)]
print(selected.shape)
print(selected)

[(0, 0), (0, 2), (0, 1), (1, 0), (1, 2), (1, 1), (2, 0), (2, 2), (2, 1), (3, 0), (3, 2), (3, 1), (4, 0), (4, 2), (4, 1)]
[[[[ 0.22963087]
   [ 0.17998772]]

  [[ 0.32717225]
   [ 1.97121177]]

  [[ 0.13861733]
   [-0.38999729]]]


 [[[ 0.11822471]
   [-0.27493974]]

  [[-0.15268215]
   [-0.51989148]]

  [[ 1.56184234]
   [ 1.47671579]]]


 [[[ 2.0823348 ]
   [-0.7414626 ]]

  [[ 0.54612075]
   [-0.77610986]]

  [[ 0.87197412]
   [-1.8083039 ]]]


 [[[-2.75882432]
   [ 0.33242333]]

  [[ 0.04835124]
   [ 0.78789905]]

  [[-2.27382759]
   [-1.19577957]]]


 [[[ 0.30455462]
   [-1.06568387]]

  [[-0.25735226]
   [ 1.97643379]]

  [[ 0.43195329]
   [-0.43137462]]]]
(2, 1)
[[-0.15268215]
 [-0.51989148]]


## Tuple

In [4]:
tuple1 = (1, 2)
tuple2 = (257,)

tuple_res = tuple1 + tuple2
print(tuple_res)

(1, 2, 257)


## Comma operators

In [5]:
data = list(range(10))
print(data)

data1 = data[::2]
print(data1)

data2 = data[1::2]
print(data2)

data3 = data[2::2]
print(data3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]
[2, 4, 6, 8]


## Index the list

In [3]:
list_data = [1, 2, 3, 4]
index = list_data.index(3)
print(index)

2


## Merge multiple lists

In [6]:
def get_file_list(input):
    all_videos = []
    
    if type(input) == list:
        all_videos += input
    else:
        all_videos += [input]
    return all_videos

videos = ["123.mp4", "345.mp4"]
# videos = "345.mp4"


all_videos = get_file_list(videos)
print(all_videos)

['123.mp4', '345.mp4']


## Check list has elements or not


In [2]:
list_a = [1]
if len(list_a):
    print("Has value")
else:
    print("Empty")


keys = None

if keys is not None and "exp" in keys:
    print("In the keys")
else:
    print("Not in the keys")

Has value
Not in the keys


## Delete elements in list

In [10]:
## Delete the elements in-place
lines = [0, 1, 2, 3, 4, 5]
del lines[3]
print(lines)

del lines[0:3]
print(lines)

## Get the sub list
origin_list = list(range(10))
sub_list = list(set(origin_list) - set(origin_list[4:8]))
print(sub_list)

input_length = 3
out = input_length / 2
print(out)

input_list = list(range(10))
sub_list = list(set(input_list) - set(input_list[2:3]) - set(input_list[-3:]))
print(sub_list)

def delete_elements_in_list():
    print("delete elements in a list")
    data = list(range(10))
    print(data)
    need_data = list(filter(lambda x: x % 2 != 0, data))
    print(need_data)

delete_elements_in_list()

[0, 1, 2, 4, 5]
[4, 5]
[0, 1, 2, 3, 8, 9]
1.5
[0, 1, 3, 4, 5, 6]
delete elements in a list
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


In [11]:
import random

random.seed(2)
list_data = list(range(20))

seq_list = list_data
random.shuffle(seq_list) # in place
print("origin: ", seq_list)
print("after:  ", list_data)

list_data = list(range(20))
output = random.sample(list_data, len(list_data))
print("origin: ", list_data)
print("after:  ", output)

origin:  [7, 6, 17, 8, 19, 15, 13, 0, 3, 9, 14, 4, 10, 12, 16, 5, 11, 18, 2, 1]
after:   [7, 6, 17, 8, 19, 15, 13, 0, 3, 9, 14, 4, 10, 12, 16, 5, 11, 18, 2, 1]
origin:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
after:   [16, 11, 17, 14, 8, 19, 0, 13, 5, 7, 18, 6, 15, 4, 1, 10, 9, 12, 2, 3]


## Extract sub list randomly

In [4]:
import random

def get_sub_list_randomly(input_list, sub_list_len):
    assert sub_list_len <= len(input_list)
    
    len_diff = len(input_list) - sub_list_len
    
    start_idx = random.randint(0, len_diff)
    return input_list[start_idx:start_idx+sub_list_len]

list_a = list(range(20))
sub_list = get_sub_list_randomly(list_a, 4)
print(sub_list)
        

[13, 14, 15, 16]


In [8]:
import random

choose_index = 5
choose_length = 7

all_indices = list(range(18))

choose_indices = list(range(choose_index, choose_index + choose_length))

candidate_indices = list(set(all_indices) - set(choose_indices))
choices = random.sample(candidate_indices, k=choose_length)
print(choices)

[16, 12, 3, 4, 13, 0, 2]


## Shuffle the list

In [2]:
import random
input = list(range(10))
print(input)

output = random.shuffle(input)  # in-place
print(input, output)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[8, 2, 4, 3, 5, 1, 7, 9, 0, 6] None


In [9]:
import numpy as np


input = list(range(10))
print(input)

data = np.array(input)[[1, 3, 5]]
print(data, type(data))

data = data.tolist()
print(data, type(data))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 3 5] <class 'numpy.ndarray'>
[1, 3, 5] <class 'list'>


## Slice the list

In [5]:
def slice_list():
    list_a = list(range(10))
    ## 截取部分元素,注意就算只截取一个元素,返回的仍然是列表
    res_a = list_a[0:1]
    print(res_a)
    ## 每隔两个取一个元素
    res_a  = list_a[::2]  # [0, 2, 4, 6, 8]
    print(res_a)
    ## 删除最后一个元素
    res_a = list_a[:-1]
    print(res_a)
    ## 元素倒序, 注意和删除最后一个元素写法的区别
    res_a = list_a[::-1]
    print(res_a)

    ## 元素采样
    list_a = list(range(200))
    res =list_a[::8]
    print(res, len(res))

    ## 按索引取元素
    list_a = list(range(100, 0, -1))
    list_a = np.array(list_a)
    idx = [0, 1, 3, 10, 3]
    res = list_a[idx]
    print("Index get value: ", res, type(res), res.tolist())


def comma_operator():
    bbox = [12, 23, 34, 56]
    bbox = bbox[:-1]
    print(bbox)


def split_list_evenly():
    lst = list(range(53478))
    number = 5000
    data_splited = [lst[i:i + number] for i in range(0, len(lst), 5000)]
    print(len(data_splited))


def split_list():
    print("Test split_list:")
    data_list = list(range(53478))
    print(len(data_list))

    data_index = data_list[::5000]
    print(len(data_index), data_index)
    
    data_list = np.split(np.array(data_list), 9)
    print(len(data_list), data_list[0].shape)


slice_list()
comma_operator()

split_list()

split_list_evenly()

list_data = list(range(1, 10))
print(list_data)
list_short = list_data[1:20]
print(list_short)



[0]
[0, 2, 4, 6, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192] 25
Index get value:  [100  99  97  90  97] <class 'numpy.ndarray'> [100, 99, 97, 90, 97]
[12, 23, 34]
Test split_list:
53478
11 [0, 5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000]
9 (5942,)
11
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
gpu = None

if gpu != 0:
    print("Not 0")
else:
    print("0")

Not 0


In [13]:
list_length = 85
interval_length = 10

normed_list_length = int(list_length / interval_length) * interval_length
print(normed_list_length)

data_list = list(range(0, normed_list_length, interval_length))
print(data_list)


80
[0, 10, 20, 30, 40, 50, 60, 70]


## Reverse the list

In [1]:
data_a = [1,2,3,4]
data_a = data_a[::-1]
print(data_a)

[4, 3, 2, 1]


## Add and expand or expand multiple lists

In [3]:
def add_list():
    list_a = list(range(0, 5))
    list_b = list(range(5, 10))
    print(list_a)
    print(list_b)
    
    ## Using + would expand the list
    list_c = list_a + list_b
    print("Result of + process: ", list_c) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    ## Using append would get a list of list
    list_c = []
    list_c.append(list_a)
    list_c.append(list_b)
    print(list_c) # [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

add_list()

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
result of + process:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


## Member functions of list

In [4]:
a_list = []
a_list.append(1)
a_list.append(3)
a_list.append(1)
a_list += [10,8,3,1,5,7]
print(a_list, len(a_list))

print(a_list.count(1)) # 对列表中元素进行计数
print(a_list.index(1)) # 返回第一次找到1的索引
a_list.sort()          # 对列表元素进行排序,in-place
print(a_list)

## index function to get the element position
speakers = ["zhang", "hai", "ming"]
idx = speakers.index("ming")
print(idx)

[1, 3, 1, 10, 8, 3, 1, 5, 7] 9
3
0
[1, 1, 1, 3, 3, 5, 7, 8, 10]
2


## Functions return list type

In [8]:
### 列表也可以像tuple一样进行解包
def foo_list():
    list_a = ["zhanghaiming", "170", "55"]
    return list_a

def receive_list(input):
    print(input)

name, height, weight = foo_list()
print(name, height, weight)

data = [1, 2, 3, 4]
receive_list([*data])


zhanghaiming 170 55
[1, 2, 3, 4]


## any and all functions

In [3]:
length = [1, 2, -3, -3]

has_negtive = any(i < 0 for i in length)

print(has_negtive)

True


## Operate on list

In [6]:
import numpy as np
list_a = [1, 2.0, 3.0, 7.0, 9.8]
print(max(list_a))

list_b = np.array(list_a) > 3.0
print(list_b)

### Calculate the mean value
list_a = [1, 2.0, 3.0, 7.0, 9.8]
print(f"Mean is {sum(list_a) / len(list_a)}")

9.8
[False False False  True  True]
Mean is 4.5600000000000005


In [13]:
import numpy as np
transform_params = np.array([512, 512, 0.7, np.array(248.78), np.array(245.6)])
transform_params1 = np.array([512, 512, 0.7, np.array(248.78), np.array(245.6)])

print(transform_params, transform_params.shape)

combine_params = np.stack([transform_params, transform_params1], axis=0)
print(combine_params.shape)

transform_params = combine_params[0]

sTx, sTy = 10, 20.0
t = np.stack([sTx, sTy], axis=0)
print(t.shape)

t = transform_params[3:]
print(type(t))
t = [elem.item() for elem in t]
print(type(t), t)


[512.   512.     0.7  248.78 245.6 ] (5,)
(2, 5)
(2,)
<class 'numpy.ndarray'>
<class 'list'> [248.78, 245.6]


In [6]:
a = list(range(10, 15))

a = [1,1,1]

print(np.unique(a))

[1]


In [4]:
index = 147
num_candidates_perframe = 147

print(int(index / (num_candidates_perframe)))
print(int(index % (num_candidates_perframe)))


1
0


In [25]:
### Choose frames other than neighbors
import random

fname_list = list(range(20))

def select_specified_length_random_list(list_input, choice_idx, neighbor_length):
    if choice_idx + neighbor_length > len(list_input):
        return None

    remove_idx_list = list(range(choice_idx, choice_idx + neighbor_length))
    
    input_idx_list = list(range(len(list_input)))

    remained_idx_list = [x for x in input_idx_list if x not in remove_idx_list]
    
    return random.choices(remained_idx_list, k=neighbor_length)

def get_splitters_with_specific_distance(list_input, min_distance=5):
    all_frames_length = len(list_input)
    all_frames_idx = list(range(all_frames_length))
    
    avaiable_choose_idx = list(range(all_frames_length - min_distance))
    
    while 1:
        choose_idx = random.sample(avaiable_choose_idx, k=2)
        if abs(choose_idx[0] - choose_idx[1]) <= min_distance:
            continue
        else:
            break
    
    return choose_idx[0], choose_idx[1]
    

print(f"input length {len(fname_list)}")
print(select_specified_length_random_list(fname_list, 15, 5))

print(get_splitters_with_specific_distance(fname_list))

    

input length 20
[11, 14, 7, 5, 5]
(6, 13)


## Calculate the mean value of list

In [2]:
list_a = list(range(10, 25))
print(sum(list_a), len(list_a))
mean_a = sum(list_a) / len(list_a)
print(f"mean value is {mean_a}")

255 15
mean value is 17.0


## zip

In [1]:
data1 = [0, 2, 4, 6, 8]
data2 = [1, 3, 5, 7, 9]

part_list = [data1, data2]

# sort the results
ordered_results = []
for res in zip(*part_list):
    ordered_results.extend(list(res))

print(ordered_results)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
import itertools

data1 = [1, 2, 3, 4]
data2 = [4, 5, 6, 7]
save_dir = "./results"

parameters = zip(data1, data2, itertools.repeat(save_dir))

args = [entry for entry in parameters]
print(args)

def function(arg1, arg2, arg3):
    print(arg1, arg2, arg3)

function(*args[0])

[(1, 4, './results'), (2, 5, './results'), (3, 6, './results'), (4, 7, './results')]
1 4 ./results


## Miscellaneous

In [13]:
weight = [0.0, 1.0]

if all(elem > 0 for elem in weight):
    print("Not all zero")
else:
    print("Has zero")

weight = [0.0]

if any(weight):
    print("Not all zero")
else:
    print("Has zero")

Has zero
Has zero
