In [3]:
import numpy as np
import torch

nusc_class_frequencies = np.array([
 944004,
 1897170,
 152386,
 2391677,
 16957802,
 724139,
 189027,
 2074468,
 413451,
 2384460,
 5916653,
 175883646,
 4275424,
 51393615,
 61411620,
 105975596,
 116424404,
 1892500630
 ])

out_channel = 19
class_weights = torch.from_numpy(1 / np.log(nusc_class_frequencies[:out_channel] + 0.001))
print(class_weights, class_weights.shape)

class_weights = torch.cat([torch.tensor([0]), class_weights])
print(class_weights, class_weights.shape)

class_weights[-1] = 0.1 * class_weights[-1]
print(class_weights, class_weights.shape)

tensor([0.0727, 0.0692, 0.0838, 0.0681, 0.0601, 0.0741, 0.0823, 0.0688, 0.0773,
        0.0681, 0.0641, 0.0527, 0.0655, 0.0563, 0.0558, 0.0541, 0.0538, 0.0468],
       dtype=torch.float64) torch.Size([18])
tensor([0.0000, 0.0727, 0.0692, 0.0838, 0.0681, 0.0601, 0.0741, 0.0823, 0.0688,
        0.0773, 0.0681, 0.0641, 0.0527, 0.0655, 0.0563, 0.0558, 0.0541, 0.0538,
        0.0468], dtype=torch.float64) torch.Size([19])
tensor([0.0000, 0.0727, 0.0692, 0.0838, 0.0681, 0.0601, 0.0741, 0.0823, 0.0688,
        0.0773, 0.0681, 0.0641, 0.0527, 0.0655, 0.0563, 0.0558, 0.0541, 0.0538,
        0.0047], dtype=torch.float64) torch.Size([19])
