In [2]:
import numpy as np

In [19]:
import numpy as np
import matplotlib.pyplot as plt


selected_points1 = np.random.randn(10, 2)
center = np.median(selected_points1, axis=0)
set_max = range(128)
colors = {m: i for i, m in enumerate(set_max)}
colors = {m: (255 * np.array(plt.cm.hsv(i/float(len(colors))))[:3][::-1]).astype(np.int32)
            for m, i in colors.items()}

print(center)
dist = selected_points1 - center
print(dist.shape)

coord_angle = np.arctan2(dist[:, 1], dist[:, 0])
print(coord_angle.shape)
corr_color = np.int32(64 * coord_angle / np.pi) % 128
print(corr_color.shape, corr_color)

color = tuple(colors[corr_color[0]].tolist())
print(color)

corr_color = [tuple(colors[m].tolist()) for m in corr_color]
print(corr_color)

[-0.23902244 -0.55506653]
(10, 2)
(10,)
(10,) [ 0 14 70  0 93 63 91 30  4 53]
(0, 0, 255)
[(0, 0, 255), (0, 165, 255), (255, 193, 0), (0, 0, 255), (255, 0, 78), (234, 255, 0), (255, 0, 54), (0, 255, 155), (0, 47, 255), (116, 255, 0)]


## maximum

In [3]:
import numpy as np

data = np.arange(12).reshape(3, 4)
print(data, data.shape)

output = np.max(data, axis=1)
print(output, output.shape)

output = np.maximum(data, axis=1)
print(output, output.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[ 3  7 11] (3,)


TypeError: maximum() takes from 2 to 3 positional arguments but 1 were given

In [4]:
import numpy as np

sigma = np.array([-1, -2, 0.0, 0.1, 0.3, 1.0, 2.0, 3.0])
sigma = np.maximum(sigma, 0)
print(sigma)

temp_sigma = sigma.reshape(-1, 1)
temp_sigma = np.delete(temp_sigma, np.where(temp_sigma < 0.5))
temp_sigma.sort()
print(sigma)
print(temp_sigma)

[0.  0.  0.  0.1 0.3 1.  2.  3. ]
[0.  0.  0.  0.1 0.3 1.  2.  3. ]
[1. 2. 3.]


## Mean and sum

In [4]:
import numpy as np

x = np.random.random((68, 2))
mean = np.mean(x)
print(mean)

x = np.sum(x)
mean = x / (68 * 2)
print(mean)

data = [1, 2, 3, 4.0]
print(np.mean(data))
mean_data = np.mean(data)
print(type(mean_data))

assert isinstance(mean_data, (float, int)), "mean_data should be a float or int"

0.47264461064049273
0.47264461064049273
2.5
<class 'numpy.float64'>


## Normalize

In [7]:
import numpy as np

data = np.array([50, 50, 5.0])
data = np.array([40, 40, 5.4])
res = np.linalg.norm(data)
print(res)

56.82569841189812


In [4]:
MIN_MOTION = np.array([-0.00916614, -0.02674509, -0.0166305])
MAX_MOTION = np.array([0.01042878, 0.01583716, 0.01325295])
DIFF_MOTION = MAX_MOTION - MIN_MOTION

print(DIFF_MOTION)

x = -MIN_MOTION / DIFF_MOTION
print(x)

[0.01959492 0.04258225 0.02988345]
[0.46778145 0.62808071 0.55651205]


In [19]:
length_list = [5, 5, 20, 80, 120]

index = 5

def fetch_data(length_list, index):
    assert index < length_list[-1]
    temp_idx = np.array(length_list) > index
    list_idx = np.where(temp_idx==True)[0][0]
    sub_idx = index
    if list_idx != 0:
        sub_idx = index - length_list[list_idx - 1]
    return list_idx, sub_idx

list_idx, sub_idx = fetch_data(length_list, index)
print(list_idx, sub_idx)

2 0


## Compute norm

In [2]:
import numpy as np

input = np.array([[1, 2, 3, 4], [2, 2, 2, 2]])
print(input.shape)

output = np.linalg.norm(input, axis=1)
print(output, output.shape)

(2, 4)
[5.47722558 4.        ] (2,)


## MeshGrid

In [9]:
import numpy as np

grid_x, grid_y = np.mgrid[0:5:10j, 0:10:5j]
print(grid_x.shape, grid_y.shape)

print(grid_x)
# print(grid_y)

(10, 5) (10, 5)
[[0.         0.         0.         0.         0.        ]
 [0.55555556 0.55555556 0.55555556 0.55555556 0.55555556]
 [1.11111111 1.11111111 1.11111111 1.11111111 1.11111111]
 [1.66666667 1.66666667 1.66666667 1.66666667 1.66666667]
 [2.22222222 2.22222222 2.22222222 2.22222222 2.22222222]
 [2.77777778 2.77777778 2.77777778 2.77777778 2.77777778]
 [3.33333333 3.33333333 3.33333333 3.33333333 3.33333333]
 [3.88888889 3.88888889 3.88888889 3.88888889 3.88888889]
 [4.44444444 4.44444444 4.44444444 4.44444444 4.44444444]
 [5.         5.         5.         5.         5.        ]]


In [6]:
import numpy as np

X = np.arange(1, 3)
Y = np.arange(2, 5)
xs, ys = np.meshgrid(X, Y)
print(xs, ys)
print(xs.shape, ys.shape)
grid = np.stack((xs, ys), axis=-1)
print(grid.shape)
print(grid)

grid = grid.reshape(-1, grid.shape[-1])
print(grid)

[[1 2]
 [1 2]
 [1 2]] [[2 2]
 [3 3]
 [4 4]]
(3, 2) (3, 2)
(3, 2, 2)
[[[1 2]
  [2 2]]

 [[1 3]
  [2 3]]

 [[1 4]
  [2 4]]]
[[1 2]
 [2 2]
 [1 3]
 [2 3]
 [1 4]
 [2 4]]


## Sort values

In [6]:
ages = np.random.randint(low=30, high=60, size=10)
heights = np.random.randint(low=150, high=210, size=10)
print(ages, heights)

sorter = np.argsort(ages)
print(sorter)
print(ages[sorter]) # sort by ages
print(heights[sorter ])

[53 47 57 58 52 42 38 46 50 51] [157 151 167 204 159 151 206 173 160 177]
[6 5 7 1 8 9 4 0 2 3]
[38 42 46 47 50 51 52 53 57 58]
[206 151 173 151 160 177 159 157 167 204]


In [3]:
import numpy as np

img_resolution = 1024

img_resolution_log2 = int(np.log2(img_resolution))
block_resolutions = [2 ** i for i in range(2, img_resolution_log2 + 1)]
print(block_resolutions, len(block_resolutions))

[4, 8, 16, 32, 64, 128, 256, 512, 1024] 9


In [1]:
import numpy as np

num_segments = 1
average_duration = 234

offsets = np.multiply(list(range(num_segments)), average_duration)
print(offsets)

[0]


## Compute the L2 norm

In [5]:
from icecream import ic as print
import numpy as np

## Compute the L2 norm of a vector
delta_center = np.array([2.0, 2, 2.0])
distance = np.linalg.norm(delta_center)
print(distance)

## Compute the matrix
data_src = np.array([[1.1, 3.1],
                     [1.9, 5.5],
                     [2.8, 6.4],
                     [1.4, 3.6],
                     [2.4, 5.6],
                     [3.1, 3.4],
                     [2.7, 3.3]])

print(data_src.shape)

data_distance = np.linalg.norm(data_src[-3] - data_src, axis=1)
print(data_distance, data_distance.shape)

center = np.array([1.25, 3.35])
center = np.array([2.367,5.867])
center = np.array([2.9, 3.35])
data_distance = np.linalg.norm(center - data_src, axis=1)
print(data_distance)

data_batch = np.random.randn(8, 68, 2)
data_batch_diff = data_batch[:, 8, :] - data_batch[:, 28, :]
print(data_batch_diff.shape)

ic| distance: 3.4641016151377544
ic| data_src.shape: (7, 2)
ic| data_distance: array([2.81780056, 0.50990195, 0.89442719, 2.23606798, 0.        ,
                          2.30867928, 2.3194827 ])
    data_distance.shape: (7,)
ic| data_distance: array([1.81727818, 2.37118114, 3.0516389 , 1.52069063, 2.30488611,
                          0.20615528, 0.20615528])
ic| data_batch_diff.shape: (8, 2)


(8, 2)

In [6]:
import numpy as np
segmentation = np.array([[1, 2, 3, 4],
                         [2, 3, 1, 4],
                         [0, 3, 1, 3],
                         [3, 3, 1, 2]])
segmentation = segmentation.astype(np.uint8)

mat = np.eye(5)[segmentation]
print(mat)
print(mat.shape)


[[[0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]]
(4, 4, 5)
