# Some IO operations in Numpy for loading and saving matrix

In [1]:
import numpy as np

## npy file usages

In [2]:
def load_binary_data():
    file_path = "/home/zhanghm/Research/V100/FaceFormer/data/big_mouth_mask.npy"
    data = np.load(file_path)
    print(data.shape, data.min(), data.max())

    print(np.count_nonzero(data))


def load_dict_npy():
    """The npy file could be used to save dictionary data
    """
    npy_fp = "/home/zhanghm/Research/PU/ShapeFormer/experiments/vqdif/my_shapenet_res16/results/VisSparseRecon3D/computed/1.npy"
    data = np.load(npy_fp, allow_pickle=True)
    content = data.item()

    print(type(content), content.keys())
    for key, value in content.items():
        try:
            print(key, value.shape)
        except:
            print(key, type(value))
            print(value.keys())

    print(content.keys(), content['logits'].shape, content['quant_ind'].shape)
    print(np.unique(content['quant_ind']))

def load_FaceFormer_data():
    npy_fp = "/home/zhanghm/Research/TalkingFace/FaceFormer/vocaset/vertices_npy/FaceTalk_170725_00137_TA_sentence01.npy"
    data = np.load(npy_fp)
    print(data.shape)

def load_ShapeNet55():
    input_fp = "/home/zhanghm/Research/PointCloud/Point-MAE/data/ShapeNet55-34/shapenet_pc/02691156-1a04e3eab45ca15dd86060f189eb133.npy"
    data = np.load(input_fp).astype(np.float32)
    print(data.shape)

    np.savetxt("shapenet.xyz", data)

def load_ShapeNetPC15k():
    input_fp = "/data1/zhanghm/Datasets/ShapeNet/ShapeNetCore.v2.PC15k/02691156/train/47c7b3cb099b3212d1c83bc8b134e4d8.npy"
    data = np.load(input_fp)
    print(data.dtype)
    print(data.shape)

    np.savetxt("shapenet_15k.xyz", data)


load_ShapeNetPC15k()


float32
(15000, 3)


In [2]:
import numpy as np

arr1 = np.load("/home/zhanghm/Research/StyleGAN/Deep3DFaceRecon_pytorch/pred_coeffs_new.npy")
arr2 = np.load("/home/zhanghm/Research/StyleGAN/Deep3DFaceRecon_pytorch/pred_coeffs.npy")
print(arr1.shape, arr2.shape)

diff = arr1 - arr2
print(diff.min(), diff.max())

(402, 257) (402, 257)
-0.2383115 0.2779872


## npz file usages
https://vimsky.com/examples/usage/python-numpy.savez.html

In [12]:
import numpy as np
from PIL import Image

def read_points2nerf_npz():
    fp = "50_fff64da26715b520e40201fea1ad0f1.npz"
    data = np.load(fp)
    print(type(data))
    print(data.files)

    images = data['images']
    print(images.shape, images.min(), images.max())
    
    img = Image.fromarray((images[0] * 255.0).astype(np.uint8))
    img.save("dd.png")

    points = data['data']
    print(points.shape)
    np.savetxt("dd.xyz", points[:, :3])


read_points2nerf_npz()

<class 'numpy.lib.npyio.NpzFile'>
['images', 'cam_poses', 'data']
(50, 200, 200, 3) 0.011765 1.0
(2048, 6)


In [8]:
import numpy as np

def load_npz():
    npz_file_path = "./data/obama2.npz"
    netparams = np.load(open(npz_file_path, 'rb'))

    print(netparams.files)  ## Get the dictionary keys

    content = netparams['face']
    print(type(netparams), content.shape, np.min(content), np.max(content))

    ## Another npz file
    real_params = "/home/haimingzhang/Research/Face/FACIAL/gangqiang_2_preprocess/deep3dface.npz"
    realparams = np.load(open(real_params, 'rb'))['face']
    print(realparams.shape)


def load_npz2():
    npz_fp = "/home/zhanghm/Research/PU/ShapeFormer/experiments/my_demo_vqdif/eval/0.npz"
    content = np.load(open(npz_fp, "rb"))
    print(content.files)

    eval_pc = content['eval_pc']
    print(eval_pc.shape)
    np.savetxt("eval_pc.xyz", eval_pc)

def load_npz3():
    npz_fp = "/home/zhanghm/Research/PU/Github/sapcu/data/ShapeNet/02828884/faa74f8980fadf504777535b9098089a/pointcloud.npz"
    npz_fp = "/home/zhanghm/Research/PU/Github/sapcu/data/ShapeNet/02828884/f5557538f4c6d755d295b24579cf55b8/pointcloud.npz"
    npz_fp = "/home/zhanghm/Research/PU/Github/sapcu/data/ShapeNet/02933112/1a9a91aa5e3306ec5938fc2058ab2dbe/pointcloud.npz"
    npz_fp = "/home/zhanghm/Research/PU/Github/sapcu/data/ShapeNet/02933112/1d898bbd8bbad8f98430b7446f9e1252/pointcloud.npz"
    content = np.load(npz_fp)
    print(content.files)

    points = content['points']
    print(points.shape, points.min(), points.max())
    np.savetxt("points.xyz", points)

def load_general_npz():
    npz_fp = "/home/zhanghm/Research/PU/Github/OnSurfacePrior/data/input.ply.npz"
    content = np.load(npz_fp)
    print(content.files)
    for key, value in content.items():
        print(key, value.shape, value.min(), value.max())
        if key == "sample" or key == "pointcloud_s":
            np.savetxt(f"{key}.xyz", value)


def load_NeuralPull_data():
    npz_fp = "/home/zhanghm/Research/PU/Github/NeuralPull-Pytorch/data/gargoyle.npz"
    # npz_fp = "/home/zhanghm/Research/PU/Github/NeuralPull-Pytorch/data/punet_sample_100.npz"
    # npz_fp = "/home/zhanghm/Research/PU/CAP-UDF/data/owndata/query_data/punet_sample_100.npz"
    
    load_data = np.load(npz_fp)
    print(load_data.files)

    print(load_data['sample_near'].shape, load_data['sample'].shape, load_data['point'].shape)
    np.savetxt("0_sample_near.xyz", load_data['sample_near'][0])
    np.savetxt("0_sample.xyz", load_data['sample'][0])
    np.savetxt("0_point.xyz", load_data['point'])


def load_CAP_UDF_npz():
    npz_fp = "/home/zhanghm/Research/PU/CAP-UDF/data/shapenetCars2/query_data/3e5e4ff60c151baee9d84a67fdc5736.npz"
    # npz_fp = "/home/zhanghm/Research/PU/CAP-UDF/data/shapenetCars/query_data/3e5e4ff60c151baee9d84a67fdc5736.npz"
    
    load_data = np.load(npz_fp)
    print(load_data.files)
    sample = load_data['sample']
    point = load_data['point']
    sample_near = load_data['sample_near']
    print(sample.shape, point.shape, sample_near.shape)

    np.savetxt("sample_near.xyz", sample_near[0])
    np.savetxt("sample.xyz", sample[0])
    np.savetxt("gt.xyz", point)


def write_npz():
    face_params = np.zeros((10, 64), np.float)
    np.savez("./data/example.npz", face=face_params)
    
load_npz3()


['points', 'normals']
(50000, 3) -0.5075068 0.50887996


## Load .txt/.xyz file

In [5]:
import numpy as np


def load_xyz_pc_data():
    xyz_fp = "/home/zhanghm/Research/Programming/cv-fighter/GenPU_Dataset2/Bed/e0bd1850ff5dd7e9485059ffe7a2f9c7/gt_pc.xyz"
    xyz_fp = "/data/zhanghm/Datasets/sapcu/gt/camel.xyz"
    input = np.loadtxt(xyz_fp)
    print(input.shape, input.dtype)


def load_CAP_UDF_data():
    xyz_fp = "/home/zhanghm/Research/PU/CAP-UDF/data/shapenetCars/input/3e5e4ff60c151baee9d84a67fdc5736.xyz"
    xyz_fp = "/home/zhanghm/Research/PU/CAP-UDF/data/shapenetCars/input/c153fa692b6b6dd7ab7ec554b18515bb.xyz"
    input = np.loadtxt(xyz_fp)
    print(input.shape, input.dtype, input.min(), input.max())


load_xyz_pc_data()

(20000, 3) float64


In [2]:
import numpy as np

fp = "/data1/zhanghm/Code/NeRF/vision-nerf/dataset/srn_chairs/chairs_train/chairs_2.0_train/1a74a83fa6d24b3cacd67ce2c72c02e/pose/000003.txt"
fp = "/data1/zhanghm/Code/NeRF/vision-nerf/dataset/srn_cars/cars_train/1a4ef4a2a639f172f13d1237e1429e9e/pose/000009.txt"
pose = np.loadtxt(fp).reshape(4, 4)
print(pose)

radius = np.linalg.norm(pose[:3, 3])
print(radius)

[[-9.00029898e-01 -4.05742265e-02 -4.33935225e-01  5.64115703e-01]
 [ 4.35828000e-01 -8.37893337e-02 -8.96121204e-01  1.16495752e+00]
 [ 2.94297905e-07 -9.95657086e-01  9.30962339e-02 -1.21024936e-01]
 [-0.00000000e+00  0.00000000e+00 -0.00000000e+00  1.00000000e+00]]
1.299999843434892


## Combine different parameters from two persons

In [6]:
another_deep3dface_npz = "/home/haimingzhang/Research/Face/FACIAL/video_preprocessed/id00001/gangqiang_3/deep3dface.npz"

netparams = np.load(open(another_deep3dface_npz, 'rb'))['face']

print(type(netparams), netparams.shape, np.min(netparams), np.max(netparams))


<class 'numpy.ndarray'> (1419, 257) -3.4403297901153564 3.5975096225738525


## Load npy file

In [2]:
file_path = "/home/haimingzhang/Research/Face/voca/training_data/init_expression_basis.npy"
file_path = "/home/zhanghm/Research/Github/FaceFormer/vocaset/vertices_npy/FaceTalk_170725_00137_TA_sentence01.npy"

expression_basis = np.load(file_path)
print(expression_basis.shape, np.min(expression_basis), np.max(expression_basis))

(204, 15069) -0.18839313089847565 0.13654573261737823


In [34]:
import time
import numpy as np
import cv2

time1 = time.time()
mask = np.load("/home/haimingzhang/Research/Programming/cv-fighter/face_fighter/3DMM/mask.npy")
# mask = cv2.imread("/home/haimingzhang/Research/Programming/cv-fighter/face_fighter/3DMM/mask.png")
# mask = np.load(open("/home/haimingzhang/Research/Programming/cv-fighter/face_fighter/3DMM/mask.npz", "rb"))['mask']
print(mask.dtype)
time2 = time.time()
print(time2 - time1)

def get_contour(im):
    contours, hierarchy = cv2.findContours(im.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

    out = np.zeros_like(im)
    out = cv2.fillPoly(out, contours, 255)

    return out

mask2 = get_contour(mask)
cv2.imwrite("mask2.png", mask2)

uint8
0.0019309520721435547


True