In [2]:
import numpy as np
from icecream import ic as print

## Use mask vector to extract subarray

In [4]:
mask_vector = np.array([1, 0, 1, 0, 0, 0, 1], dtype=bool)
print(mask_vector.shape)

data_index = np.arange(7)
print(data_index)

remain_index = data_index[~mask_vector]
print(remain_index)

ic| mask_vector.shape: (7,)
ic| data_index: array([0, 1, 2, 3, 4, 5, 6])
ic| remain_index: array([1, 3, 4, 5])


array([1, 3, 4, 5])

In [9]:
mask_vector = np.array([3, 0, 1, 0], dtype=np.int)
print(mask_vector.shape, mask_vector)

data_index = np.arange(7)
print(data_index)

remain_index = data_index[mask_vector]
print(remain_index)

ic| mask_vector.shape: (4,), mask_vector: array([3, 0, 1, 0])
ic| data_index: array([0, 1, 2, 3, 4, 5, 6])
ic| remain_index: array([3, 0, 1, 0])


array([3, 0, 1, 0])

## Use mask index to set value for another vector

In [8]:
data_index = np.zeros(7)
print(data_index)

mask_index = np.array([1, 0, 4], dtype=np.int)
data_index[mask_index] = 1

print(data_index)



ic| data_index: array([0., 0., 0., 0., 0., 0., 0.])
ic| data_index: array([1., 1., 0., 0., 1., 0., 0.])


array([1., 1., 0., 0., 1., 0., 0.])

## Access subarray

In [18]:
import numpy as np

A = np.array([1, 2, 3, 5, 6])
B = np.array([3, 1])

res = list(map(lambda sub: list(filter(lambda i: A[i] == sub, range(len(A))))
               or [None], B))
res = np.array(res).squeeze()
print(res)

dd = np.in1d(A, B)
print(dd)

dd = A[np.in1d(A, B, invert=False)]
print(dd)

idx = np.where(B == dd)
print(idx)

AA = A.tolist()
print(AA)
dd = np.take(A.tolist(), res)
print(dd)

[2 0]
[ True False  True False False]
[1 3]
(array([], dtype=int64),)
[1, 2, 3, 5, 6]
[3 1]


## Linespace the array to get subarrray

In [7]:
import numpy as np
TimeList = np.linspace(0, 11-1, 11, dtype=np.int)
print(TimeList, len(TimeList), type(TimeList))

TimeList = list(TimeList)

print(type(TimeList))

length = 100
sub_arr = np.linspace(0, length-1, 60, dtype=np.int)
print(sub_arr, len(sub_arr), type(sub_arr))

length_list = np.array(range(100))
sub_length_list = length_list[sub_arr]
print(sub_length_list)

[ 0  1  2  3  4  5  6  7  8  9 10] 11 <class 'numpy.ndarray'>
<class 'list'>
[ 0  0  1  2  3  4  4  5  6  7  8  9  9 10 11 12 13 14 14 15 16 17 18 19
 19 20 21 22 23 24 24 25 26 27 28 29 29 30 31 32 33 34 34 35 36 37 38 39
 39 40 41 42 43 44 44 45 46 47 48 49] 60 <class 'numpy.ndarray'>
[ 0  0  1  2  3  4  4  5  6  7  8  9  9 10 11 12 13 14 14 15 16 17 18 19
 19 20 21 22 23 24 24 25 26 27 28 29 29 30 31 32 33 34 34 35 36 37 38 39
 39 40 41 42 43 44 44 45 46 47 48 49]
