In [1]:
import torch
import numpy as np
import time
# import icecream as print

In [20]:
data1 = torch.arange(12).reshape(2, 3, 2)
print(data1, data1.shape)

data2 = torch.arange(1, 6).reshape(5, 1)
print(data2, data2.shape)

diff = data1 - data2
print(diff, diff.shape)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]) torch.Size([2, 3, 2])
tensor([[1],
        [2],
        [3],
        [4],
        [5]]) torch.Size([5, 1])


RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1

In [5]:
samples = torch.randn(5, 2048, 3)
centers = torch.randn(5, 512, 3)

print(samples.shape, centers.shape)

samples = samples[:, :, None]
centers = centers[:, None]
print(samples.shape, centers.shape)



torch.Size([5, 2048, 3]) torch.Size([5, 512, 3])
torch.Size([5, 2048, 1, 3]) torch.Size([5, 1, 512, 3])


In [15]:
samples = torch.randn(2, 5, 2)
centers = torch.randn(2, 3, 2)

print(samples.shape, centers.shape)

samples = samples[:, :, None]
centers = centers[:, None]
print(samples.shape, centers.shape)
print(samples)
print(centers)

diff = samples - centers
print(diff.shape)


torch.Size([2, 5, 2]) torch.Size([2, 3, 2])
torch.Size([2, 5, 1, 2]) torch.Size([2, 1, 3, 2])
tensor([[[[ 0.2863, -2.0333]],

         [[-0.5930, -1.4498]],

         [[ 0.8496, -0.5239]],

         [[ 0.6585,  0.0317]],

         [[ 0.4878, -1.5573]]],


        [[[-0.8664, -0.3688]],

         [[ 0.7432,  0.6022]],

         [[ 0.4953, -2.3943]],

         [[-1.0468,  0.1989]],

         [[ 1.5930, -1.4863]]]])
tensor([[[[ 0.4738,  0.2337],
          [-0.6130, -0.0142],
          [-0.1410,  0.1656]]],


        [[[ 1.5062, -0.8948],
          [ 0.8406,  0.3560],
          [ 1.7580,  0.4282]]]])
torch.Size([2, 5, 3, 2])


In [14]:
print(diff)

tensor([[[[ 0.3577,  0.1267],
          [ 1.0638, -0.7291],
          [-0.7850,  1.6956]],

         [[-1.2511,  1.2253],
          [-0.5449,  0.3695],
          [-2.3938,  2.7942]],

         [[ 0.7763, -0.7426],
          [ 1.4824, -1.5984],
          [-0.3664,  0.8263]],

         [[ 0.1647,  0.0264],
          [ 0.8708, -0.8293],
          [-0.9780,  1.5954]],

         [[ 0.7199,  0.5614],
          [ 1.4260, -0.2944],
          [-0.4228,  2.1303]]],


        [[[-2.7425,  0.2651],
          [-0.2745,  0.6240],
          [-1.9553, -0.5651]],

         [[-0.4854,  2.0309],
          [ 1.9826,  2.3897],
          [ 0.3018,  1.2007]],

         [[ 0.0293,  0.6940],
          [ 2.4973,  1.0528],
          [ 0.8165, -0.1362]],

         [[-1.8309, -1.2456],
          [ 0.6372, -0.8867],
          [-1.0436, -2.0758]],

         [[-1.5062,  1.4292],
          [ 0.9618,  1.7881],
          [-0.7190,  0.5990]]]])
