In [1]:
import torch
import torch.nn as nn
import numpy as np
import random
from icecream import ic as print

ModuleNotFoundError: No module named 'icecream'

## Create torch tensors
https://pytorch.org/docs/stable/tensors.html#torch.Tensor

### Basic creation

In [9]:
### Basic creator
x = torch.tensor([1, 2, 3])
print(x.shape, x.dtype) # is torch.int64 by default

tensor_shape = x.shape
print(type(tensor_shape), len(tensor_shape))

x = torch.tensor([1, 2, 3], dtype=torch.float32) # we can specify the dtype
print(x.shape, x.dtype) # is torch.int64 by defau

### Random creator
x = torch.rand((3, 5)) # 生成0-1的随机数
print(x.shape, x.dtype) # is torch.float32 by default

x = torch.randn(3, 5) # 生成标准正态分布的随机数
print(x.shape, x.min(), x.max())

target = torch.randint(5, (10, ))
print(target.shape, target.dtype, target.min(), target.max())

input = torch.rand((10, 10, 30))
y = torch.zeros_like(input)
print(y.shape, y.dtype, input.dtype)

y = torch.rand_like(input) # [0, 1.0]
print(y.min(), y.max(), y.dtype, y.shape)

x = torch.zeros(2, 3)
y = torch.rand_like(x)
print(y, y.min(), y.max())

ic| x.shape: torch.Size([3]), x.dtype: torch.int64
ic| type(tensor_shape): <class 'torch.Size'>, len(tensor_shape): 1
ic| x.shape: torch.Size([3]), x.dtype: torch.float32
ic| x.shape: torch.Size([3, 5]), x.dtype: torch.float32
ic| x.shape: torch.Size([3, 5])
    x.min(): tensor(-2.4933)
    x.max(): tensor(1.4367)
ic| target.shape: torch.Size([10])
    target.dtype: torch.int64
    target.min(): tensor(0)
    target.max(): tensor(4)
ic| y.shape: torch.Size([10, 10, 30])
    y.dtype: torch.float32
    input.dtype: torch.float32
ic| y.min(): tensor(1.2398e-05)
    y.max(): tensor(0.9997)
    y.dtype: torch.float32
    y.shape: torch.Size([10, 10, 30])
ic| y: tensor([[0.1322, 0.0267, 0.9540],
               [0.7336, 0.3102, 0.6741]])
    y.min(): tensor(0.0267)
    y.max(): tensor(0.9540)


(tensor([[0.1322, 0.0267, 0.9540],
         [0.7336, 0.3102, 0.6741]]),
 tensor(0.0267),
 tensor(0.9540))

### Create image

In [1]:
import torch

image = torch.randint(0, 256, (3, 11, 10)).float()
print(image.shape, image.dtype, image.min(), image.max())

torch.Size([3, 11, 10]) torch.float32 tensor(0.) tensor(255.)


### Create from list

In [1]:
import torch

input = [1, 2, 3, 4]
tensor = torch.Tensor(input)
print(tensor, tensor.shape, tensor.mean().item())

normalize_matrix = torch.tensor([[1/((640-1)/2), 0, -1, 0], [0, 1/((512-1)/2), -1, 0], [0,0,1,0], [0,0,0,1]])
print(normalize_matrix)

/home/zhanghm/miniconda3/envs/py38-torch100-cu11/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([1., 2., 3., 4.]) torch.Size([4]) 2.5
tensor([[ 0.0031,  0.0000, -1.0000,  0.0000],
        [ 0.0000,  0.0039, -1.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])


### Create special tensors

In [1]:
import torch

## Create special tensors
### All zeros or all ones creator
y = torch.zeros((10, 5, 1)) # float32 by default
print(y.shape, y.dtype, tuple(y.shape[:2]))
print(type(y.shape[:2]))
print(y.shape[:2] + (257,))

y = torch.zeros((5, 1)).int() # convert to int32
print(y.shape, y.dtype)

y = torch.zeros(1).int()
print(y.shape, y[0])

## Identity matrix
I = torch.eye(4)
print(I, I.dtype)


all_ones_tensor = torch.ones(5)
print(all_ones_tensor, all_ones_tensor.dtype, all_ones_tensor.shape)

## Create the empty tensor
shape = (1, 1024, 256)
t = torch.empty(*shape)
print(t.shape)

## Create diagonal matrix
coord_trans = torch.diag(torch.tensor([1, -1, -1, 1], dtype=torch.float32))
print(coord_trans)

torch.Size([10, 5, 1]) torch.float32 (10, 5)
<class 'torch.Size'>
torch.Size([10, 5, 257])
torch.Size([5, 1]) torch.int32
torch.Size([1]) tensor(0, dtype=torch.int32)
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]) torch.float32
tensor([1., 1., 1., 1., 1.]) torch.float32 torch.Size([5])
torch.Size([1, 1024, 256])
tensor([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  0.,  0.,  1.]])


/home/zhanghm/miniconda3/envs/py38-torch100-cu11/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [1]:
import torch

## Create arange tensor
arr = torch.arange(0, 10)
print(arr.shape)

data1 = torch.arange(12).reshape(2, 3, 2)
print(data1, data1.shape)

data2 = torch.arange(1, 5).reshape(2, 1, 2)
print(data2, data2.shape)


torch.Size([10])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]) torch.Size([2, 3, 2])
tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])


/home/zhanghm/miniconda3/envs/py38-torch100-cu11/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [17]:

x = torch.tensor([[1, 2, 0], [0, 1, 0]])[..., None]

x = torch.zeros(2, 3, 4).scatter_(2, x.type(torch.LongTensor), 1)
print(x)

tensor([[[0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.]]])


### Create tensor from numpy matrix

In [3]:
## ============ Create tensor from numpy matrix ===============
import numpy as np

np_array = np.random.random((3, 4, 5)).astype(np.float32) # np.float64 by default
print(type(np_array), np_array.shape, np_array.dtype)

# by using torch.from_numpy function
tensor_array = torch.from_numpy(np_array)
print(tensor_array.shape, tensor_array.dtype)

# using torch.tensor function also ok
tensor_array = torch.tensor(np_array)
print(tensor_array.shape, tensor_array.dtype)

<class 'numpy.ndarray'> (3, 4, 5) float32
torch.Size([3, 4, 5]) torch.float32
torch.Size([3, 4, 5]) torch.float32


In [1]:
import torch

data = torch.randn(2, 3, 4)
data_new = torch.from_numpy(data)
print(data_new.shape, data_new.dtype)

TypeError: expected np.ndarray (got Tensor)

In [5]:
y = torch.zeros((10, 1))
print(y.shape, y.dtype)

print(y)
y = torch.unsqueeze(y, 0)
print(y.shape, y.dtype)
print(y)


input_data = torch.rand((4, 60, 8))
input_data = input_data[:, :8]
print(input_data.shape)


torch.Size([10, 1]) torch.float32
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
torch.Size([1, 10, 1]) torch.float32
tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])
torch.Size([4, 8, 8])


In [43]:
label = torch.arange(10, 19)
print(label.shape, label.dtype)

label = label.view(1,-1)
print(label, label.shape)

_, pred = label.topk(3, 1, True, True)
print(pred, pred.t())

torch.Size([9]) torch.int64
tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18]]) torch.Size([1, 9])
tensor([[8, 7, 6]]) tensor([[8],
        [7],
        [6]])


## Create torch tensors - Part 2

### Create right shifted matrix

In [8]:
from torch import Tensor

def _generate_shifted_target(target: Tensor):
    """_summary_

    Args:
        target (Tensor): (Sy, B, C)

    Returns:
        _type_: shifted target with a inserted start token
    """
    ret = torch.zeros_like(target)
    ret[1:, ...] = target[:-1, ...]
    return ret

target = torch.randn((2, 4, 5))
print(target)
shifted_target = _generate_shifted_target(target)
print(shifted_target.shape)
print(shifted_target)

tensor([[[ 0.5041,  0.6514, -0.3396,  0.4546,  0.3332],
         [-0.0036, -0.6595,  0.0423,  0.8735, -0.6663],
         [ 1.3240, -1.1321, -0.7364,  0.2649,  1.3023],
         [-0.9993,  0.5696,  0.2285, -1.1304, -0.4896]],

        [[ 3.0797, -0.4287,  0.6457,  0.5229, -0.1737],
         [-1.1057, -1.9149,  0.3974,  1.0938,  0.8098],
         [ 2.6179,  1.9122,  0.5650, -1.2638,  0.7957],
         [-0.5098,  0.0470,  1.4643, -0.7093,  2.1780]]])
torch.Size([2, 4, 5])
tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.5041,  0.6514, -0.3396,  0.4546,  0.3332],
         [-0.0036, -0.6595,  0.0423,  0.8735, -0.6663],
         [ 1.3240, -1.1321, -0.7364,  0.2649,  1.3023],
         [-0.9993,  0.5696,  0.2285, -1.1304, -0.4896]]])


In [5]:
locations = torch.randn(10, 2)
xs, ys = locations[:, 0], locations[:, 1]
print(xs.shape, ys.shape)
xs = xs[:, None]
print(xs.shape)

ys = ys[None]
print(ys.shape)

ic| xs.shape: torch.Size([10]), ys.shape: torch.Size([10])
ic| xs.shape: torch.Size([10, 1])
ic| ys.shape: torch.Size([1, 10])


torch.Size([1, 10])

### Create masked matrix

In [2]:
import torch

def generate_subsequent_mask(seq_len):
    """Generate future masked matrix

    Args:
        seq_len int): sequence length

    Returns:
        Tensor: (seq_len, seq_len) dimension
    """
    mask = (torch.triu(torch.ones(seq_len, seq_len)) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask

masked_matrix = generate_subsequent_mask(4)
print(masked_matrix)

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])


In [61]:
x = torch.rand((3, 5, 4))

lengths = torch.tensor([1, 2, 3])
batch_size, max_len, _ = x.shape
# create mask for padded elements and zero-out them
mask = torch.arange(max_len, device=lengths.device).expand(batch_size, max_len) >= lengths[:, None]
print(mask)
mask = ~mask[..., None]
print(x.shape, mask.shape)
mask = mask.type(torch.float)
x = torch.mul(x, mask)

# x[mask] = 0.0
print(x)

# mask = -10000.0 * mask[:, None, None, :].to(dtype=x.dtype)
# print(mask, mask.shape)
# mask = mask.expand(batch_size, 1, max_len, max_len)


tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True]])
torch.Size([3, 5, 4]) torch.Size([3, 5, 1])
tensor([[[0.2455, 0.5985, 0.7856, 0.8820],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.4024, 0.1510, 0.2556, 0.8236],
         [0.1437, 0.3919, 0.0533, 0.4486],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.3731, 0.3793, 0.7705, 0.9820],
         [0.4504, 0.8001, 0.7164, 0.3064],
         [0.0375, 0.4668, 0.8711, 0.9600],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]]])


In [4]:
def fill_with_neg_inf(t):
    """FP16-compatible function that fills a tensor with -inf."""
    return t.float().fill_(float("-inf")).type_as(t)

tokens_per_sample = 5
tmp = fill_with_neg_inf(torch.zeros([tokens_per_sample, tokens_per_sample]))
print(tmp, tmp.dtype)

output = torch.triu(tmp, 1)

print(output, output.shape)

tensor([[-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf]]) torch.float32
tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]]) torch.Size([5, 5])


In [5]:
def _generate_square_subsequent_mask(sz):
    mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask

src = torch.rand((10, 32, 512))
print(len(src))

mask = _generate_square_subsequent_mask(len(src))
print(mask, mask.shape)

10
tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) torch.Size([10, 10])


In [9]:
import math

def get_slopes(n):
    def get_slopes_power_of_2(n):
        start = (2**(-2**-(math.log2(n)-3)))
        ratio = start
        return [start*ratio**i for i in range(n)]

    if math.log2(n).is_integer():
        return get_slopes_power_of_2(n)                   #In the paper, we only train models that have 2^a heads for some a. This function has
    else:                                                 #some good properties that only occur when the input is a power of 2. To maintain that even
        closest_power_of_2 = 2**math.floor(math.log2(n))  #when the number of heads is not a power of 2, we use this workaround. 
        return get_slopes_power_of_2(closest_power_of_2) + get_slopes(2*closest_power_of_2)[0::2][:n-closest_power_of_2]

attn_heads = 8

slopes = torch.Tensor(get_slopes(attn_heads)).unsqueeze(1).unsqueeze(1)
print(slopes, slopes.dtype, slopes.shape)

maxpos = 5

alibi = slopes * torch.arange(maxpos, dtype=torch.float32).unsqueeze(0).unsqueeze(0).expand(attn_heads, -1, -1)
print(alibi, alibi.shape)

alibi = alibi.view(attn_heads, 1, maxpos)
print(alibi, alibi.shape)

dd = 11//maxpos
print(dd)
alibi = alibi.repeat(11//maxpos, 1, 1)
print("fff", alibi.shape)

mask = output.unsqueeze(0) + alibi
print(mask.shape)

print(mask[2])

tensor([[[0.5000]],

        [[0.2500]],

        [[0.1250]],

        [[0.0625]],

        [[0.0312]],

        [[0.0156]],

        [[0.0078]],

        [[0.0039]]]) torch.float32 torch.Size([8, 1, 1])
tensor([[[0.0000, 0.5000, 1.0000, 1.5000, 2.0000]],

        [[0.0000, 0.2500, 0.5000, 0.7500, 1.0000]],

        [[0.0000, 0.1250, 0.2500, 0.3750, 0.5000]],

        [[0.0000, 0.0625, 0.1250, 0.1875, 0.2500]],

        [[0.0000, 0.0312, 0.0625, 0.0938, 0.1250]],

        [[0.0000, 0.0156, 0.0312, 0.0469, 0.0625]],

        [[0.0000, 0.0078, 0.0156, 0.0234, 0.0312]],

        [[0.0000, 0.0039, 0.0078, 0.0117, 0.0156]]]) torch.Size([8, 1, 5])
tensor([[[0.0000, 0.5000, 1.0000, 1.5000, 2.0000]],

        [[0.0000, 0.2500, 0.5000, 0.7500, 1.0000]],

        [[0.0000, 0.1250, 0.2500, 0.3750, 0.5000]],

        [[0.0000, 0.0625, 0.1250, 0.1875, 0.2500]],

        [[0.0000, 0.0312, 0.0625, 0.0938, 0.1250]],

        [[0.0000, 0.0156, 0.0312, 0.0469, 0.0625]],

        [[0.0000, 0.0078, 0.0156

In [26]:
def one_hot(x):
    x = x.unsqueeze(-1)
    print(x.shape)
    condition = torch.zeros(x.shape[0], 8).scatter_(1, x.type(torch.LongTensor), 1)
    return condition

subject_idx = np.array([0, 1, 3])
x = torch.from_numpy(subject_idx).type(torch.FloatTensor)
print(x.shape)

subject_condition = one_hot(x)
print(subject_condition.shape)
print(subject_condition)

subject_idx = [0, 1, 3, 4, 1]

batch_size = len(subject_idx)

seq_len = 3

def one_hot2(x):
    x = x.unsqueeze(-1)
    print("dsfsdf", x.shape)
    condition = torch.zeros(x.shape[0], 3, 8).scatter_(2, x.type(torch.LongTensor), 1)
    return condition

# Bx3x8
subject_idx = np.expand_dims(subject_idx, axis=1)
print(subject_idx.shape)
subject_idx = subject_idx.repeat(3, axis=1)
print(subject_idx.shape)

subject_idx = torch.from_numpy(subject_idx).type(torch.FloatTensor)
subject_condition = one_hot2(subject_idx)
print(subject_condition.shape)
print(subject_condition[3], subject_condition.dtype)


torch.Size([3])
torch.Size([3, 1])
torch.Size([3, 8])
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.]])
(5, 1)
(5, 3)
dsfsdf torch.Size([5, 3, 1])
torch.Size([5, 3, 8])
tensor([[0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.]]) torch.float32


## To device

In [3]:
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

x = torch.from_numpy(np.array(["data1", "data2"]))
print(x, x.shape)

cuda


TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

## Check is tensor

In [18]:
## Method 1
x = torch.rand(4)
print(torch.is_tensor(x))

## Method 2
if isinstance(x, torch.Tensor):
    print("Is tensor")
else:
    print("Not a tensor")

ic| torch.is_tensor(x): True
ic| 'Is tensor'


## Check tensor dimension

In [2]:
import torch

data = torch.randn(2, 3, 4, 5)
print(data.shape, data.dim())
print(data.ndim)

torch.Size([2, 3, 4, 5]) 4
4


In [8]:
import torch

data = torch.randn(2, 3, 4, 5)
print(data.shape, data.dim(), data.shape)
print(data.is_contiguous())

data = torch.tensor(1.0)
print(data.shape, data.dim(), data.shape)

torch.Size([2, 3, 4, 5]) 4 torch.Size([2, 3, 4, 5])
True
torch.Size([]) 0 torch.Size([])


## Convert tensor types

In [3]:
import torch

device = torch.device("cuda")
## Specify the dtype when creating it
src_tensor = torch.tensor([1, 2, 3], dtype=torch.float32, device=device)
print(src_tensor.dtype, src_tensor.device)

tgt_tensor = torch.tensor([1, 2, 3])
print(tgt_tensor.dtype, tgt_tensor.device)

## Use to another Tensor to convert the data type and device
tgt_tensor = tgt_tensor.to(src_tensor)
print(tgt_tensor.dtype, tgt_tensor.device)

## Use the type() function
src_tensor = torch.rand((3, 2), dtype=torch.float64)
tgt_tensor = src_tensor.type(torch.float32)
print(src_tensor.dtype, tgt_tensor.dtype)


torch.float32 cuda:0
torch.int64 cpu
torch.float32 cuda:0
torch.float64 torch.float32


## Some member functions

In [8]:
tensor_data = torch.randn((3, 4, 5))
tensor_size = tensor_data.shape[1] # or using tensor_data.size(1)
print(type(tensor_size), tensor_size)
print(tensor_size)




<class 'int'> 4
4


### expand
https://discuss.pytorch.org/t/expand-vs-repeat-semantic-difference/59789

In [16]:
import torch

x = torch.zeros(1, 1, 3)
print(x, x.shape)

y = x.expand(2, 2, -1)
print(y, y.shape)

y[0,0,0] = 10  # expand would not deepcopy the memory
print(x)
print(y)


tensor([[[0., 0., 0.]]]) torch.Size([1, 1, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]) torch.Size([2, 2, 3])
tensor([[[10.,  0.,  0.]]])
tensor([[[10.,  0.,  0.],
         [10.,  0.,  0.]],

        [[10.,  0.,  0.],
         [10.,  0.,  0.]]])


## Reshape and Transpose
https://jdhao.github.io/2019/07/10/pytorch_view_reshape_transpose_permute/

### reshape vs. view

In [29]:
import torch

def test_function():
    input_data = torch.arange(6)
    print(input_data, input_data.shape)
    input_data_view = input_data.view(2, 3)
    print(input_data_view, input_data_view.shape)
    input_data_view[0, 0] = 100 # NOTE: This will change the input_data as well
    print(input_data_view, input_data)

    # print(input_data.reshape(3, 2))
    input_data_view2 = input_data.view(3, 2)
    print(input_data_view2, input_data_view2.shape)

    print(input_data_view.is_contiguous())
    input_data_transpose = input_data_view2.transpose(0, 1) # NOTE: transpose will change the contiguous
    print(input_data_transpose, input_data_transpose.is_contiguous())

    # error_data = input_data_transpose.view(3, 2) # NOTE: view function can only apply on contiguous data
    ok_data = input_data_transpose.reshape(3, 2) 
    print(ok_data)

test_function()

# input_data = input_data.transpose(0, 1)

# ## view function
# flatten_input_data = input_data.view(-1)
# print(flatten_input_data, flatten_input_data.shape)
# flatten_input_data[3] = 100 
# print(input_data)

## reshape function
# flatten_input_data = input_data.reshape(-1)
# print(flatten_input_data, flatten_input_data.shape)
# flatten_input_data[3] = 100 # NOTE: This will change the input_data as well
# print(input_data)

# flatten_input_data = input_data.reshape(-1, 1, 1)
# print(flatten_input_data.shape)
# print(flatten_input_data)

tensor([0, 1, 2, 3, 4, 5]) torch.Size([6])
tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
tensor([[100,   1,   2],
        [  3,   4,   5]]) tensor([100,   1,   2,   3,   4,   5])
tensor([[100,   1],
        [  2,   3],
        [  4,   5]]) torch.Size([3, 2])
True
tensor([[100,   2,   4],
        [  1,   3,   5]]) False
tensor([[100,   2],
        [  4,   1],
        [  3,   5]])


## Add new axis

In [4]:
input_data = torch.randn((3, 12, 12))
print(input_data.shape)

input_data = input_data[None]
print(input_data.shape)


samples = torch.randn(5, 2048, 3)
centers = torch.randn(5, 512, 3)

print(samples.shape, centers.shape)

samples = samples[:, :, None]
centers = centers[:, None]
print(samples.shape, centers.shape)

ic| input_data.shape: torch.Size([3, 12, 12])
ic| input_data.shape: torch.Size([1, 3, 12, 12])
ic| samples.shape: torch.Size([5, 2048, 3])
    centers.shape: torch.Size([5, 512, 3])
ic| samples.shape: torch.Size([5, 2048, 1, 3])
    centers.shape: torch.Size([5, 1, 512, 3])


(torch.Size([5, 2048, 1, 3]), torch.Size([5, 1, 512, 3]))

## Different data type conversion

In [10]:
pred = torch.FloatTensor(np.array([1,2,3]))
print(pred.dtype)
print(pred)
pred = pred.to(torch.int64)
print(pred.dtype)
print(pred)


torch.float32
tensor([1., 2., 3.])
torch.int64
tensor([1, 2, 3])


In [5]:
labels = None
labels = torch.tensor([1, 2, 3])
print(labels.dtype)
if labels is None: # use 'is' instead of ==
    print("Labels is None")
else:
    print("Labels is not None")

torch.int64
Labels is not None


In [13]:
## Loop the Tensor
data_a = torch.randn(3, 5, 5, 5)
print(data_a)


tensor([[[[ 1.2346e+00,  3.7939e-01, -1.9367e+00,  1.3094e+00,  4.6663e-01],
          [ 3.4819e-01, -5.6895e-01, -1.5108e+00,  7.0780e-01,  9.0777e-01],
          [ 4.6561e-01,  2.1563e+00, -2.3255e+00, -6.6472e-01,  5.5147e-01],
          [ 9.4951e-01, -3.3740e-01, -6.2161e-02,  4.8511e-01, -1.4107e-01],
          [ 6.3537e-01,  1.5464e+00,  2.0419e+00,  2.4523e-01,  2.2240e+00]],

         [[-5.4798e-01,  1.6411e-01, -2.4302e-01, -2.1069e+00, -1.1748e+00],
          [ 5.8614e-01, -1.0792e+00,  8.6184e-02,  2.6984e-02,  3.7680e-01],
          [-4.2325e-02,  5.9603e-01, -5.9892e-01,  6.5933e-01,  9.7178e-01],
          [-1.4920e+00, -2.1150e-01, -2.5007e-01, -2.6350e-01, -7.3031e-01],
          [-8.8017e-01, -1.0805e+00, -8.5367e-01,  2.3745e+00,  1.7426e+00]],

         [[ 3.5111e-01, -1.0492e+00, -6.6652e-01,  1.4015e+00,  2.0608e+00],
          [-1.2575e+00, -4.0794e-01,  2.2955e-02, -1.0286e+00,  6.4215e-01],
          [-8.6350e-01, -2.7992e-01, -2.8991e-01,  9.1334e-01,  3.0354e-

In [19]:
### Create meshgrid
# Ray helpers
def get_rays(H, W, K, c2w):
    i, j = torch.meshgrid(torch.linspace(0, W-1, W), torch.linspace(0, H-1, H))  # pytorch's meshgrid has indexing='ij'
    i = i.t()
    j = j.t()
    dirs = torch.stack([(i-K[0][2])/K[0][0], -(j-K[1][2])/K[1][1], -torch.ones_like(i)], -1)

    # Rotate ray directions from camera frame to the world frame
    rays_d = torch.sum(dirs[..., np.newaxis, :] * c2w[:3,:3], -1)  # dot product, equals to: [c2w.dot(dir) for dir in dirs]
    # Translate camera frame's origin to the world frame. It is the origin of all rays.
    rays_o = c2w[:3,-1].expand(rays_d.shape)
    return rays_o, rays_d

H, W, focal = 400, 400, 555.55
K = np.array([
            [focal, 0, 0.5*W],
            [0, focal, 0.5*H],
            [0, 0, 1]
        ])
c2w = np.random.rand(3, 4)
get_rays(H, W, K, c2w)

torch.Size([400, 400, 3])
torch.Size([400, 3])


In [8]:
data_a = torch.tensor([1, 2, 3])

data_b = data_a.clone()

data_b[0] = 12
print(data_a, data_b)

print(data_a.requires_grad)

tensor([1, 2, 3]) tensor([12,  2,  3])
False


## indexing

In [14]:
import torch

data = torch.arange(12).reshape(6, 2)
print(data)
index = torch.tensor([0, 2, 3, 5])
index = index.unsqueeze(0)
print(index.shape)

output = data[index]
print(output, output.shape)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
torch.Size([1, 4])
tensor([[[ 0,  1],
         [ 4,  5],
         [ 6,  7],
         [10, 11]]]) torch.Size([1, 4, 2])


## Slice operations for Tensor

In [12]:
data_a = torch.rand((2, 21, 48, 48))
length = 10
data_a_fw = data_a[:, :length-1, ...]
print(data_a_fw.shape)

data_a_bw = data_a[:, length:, ...].flip(1)
print(data_a_bw.shape)

t = 19
t = t // 3 * 3
print(t)

n = 2
n_clip = n * t // 3
print(n_clip)

hr_flow = list(range(19))
hr_flow_bw = hr_flow[0:t:3]
print(hr_flow_bw)

torch.Size([2, 9, 48, 48])
torch.Size([2, 11, 48, 48])
18
12
[1, 4, 7, 10, 13, 16]


## masked_fill

In [15]:
import torch

input = torch.randn(2, 3)
print(input)

output = input.masked_fill(input < 0, 0)
print(output)

input.masked_fill_(input < 0, 0)
print(input)

tensor([[ 0.4402, -2.4868, -0.9217],
        [-0.5635,  1.9211, -0.9840]])
tensor([[0.4402, 0.0000, 0.0000],
        [0.0000, 1.9211, 0.0000]])
tensor([[0.4402, 0.0000, 0.0000],
        [0.0000, 1.9211, 0.0000]])


## Submatrix

In [4]:
import torch

## Get the submatrix according to the boolean mask

mask = torch.tensor([True, False, True, False, True])
print(mask.shape)
data = torch.randn((5, 2, 2))
print(data, data.shape)

mask_data = data[mask]
print(mask_data)

torch.Size([5])
tensor([[[-1.1381, -0.0397],
         [ 1.6323,  0.1880]],

        [[-0.8910,  0.2037],
         [ 0.2593,  0.2279]],

        [[-0.2807,  1.2331],
         [-0.5396, -0.1515]],

        [[ 1.4733, -0.2060],
         [ 0.9064,  0.4809]],

        [[ 0.0519, -1.3739],
         [-0.3992, -2.0197]]]) torch.Size([5, 2, 2])
tensor([[[-1.1381, -0.0397],
         [ 1.6323,  0.1880]],

        [[-0.2807,  1.2331],
         [-0.5396, -0.1515]],

        [[ 0.0519, -1.3739],
         [-0.3992, -2.0197]]])


: 

## narrow & unbind functions

In [16]:
import torch
x = torch.randn(3, 3)
print("x:")
print(x)

print("narrow function") # https://pytorch.org/docs/master/generated/torch.narrow.html
row_slice = x.narrow(0, 1, 2) # (dim, start_idx, length)
print(row_slice, row_slice.shape) # column dimension keep unchanged

print(x.narrow(1, 1, 2))

print("unbind function") # https://pytorch.org/docs/master/generated/torch.unbind.html
row_unbind = x.unbind(0)
print(row_unbind, type(row_unbind))

col_unbind = x.unbind(1)
print(col_unbind)

x_iter = iter(col_unbind)
dd = next(x_iter)
print(dd.shape)

x:
tensor([[ 1.9275,  0.8109,  0.9534],
        [ 1.9258,  0.5665, -0.8327],
        [ 0.4763, -1.5188, -0.9933]])
tensor([[ 1.9258,  0.5665, -0.8327],
        [ 0.4763, -1.5188, -0.9933]]) torch.Size([2, 3])
tensor([[ 0.8109,  0.9534],
        [ 0.5665, -0.8327],
        [-1.5188, -0.9933]])
unbind function
(tensor([1.9275, 0.8109, 0.9534]), tensor([ 1.9258,  0.5665, -0.8327]), tensor([ 0.4763, -1.5188, -0.9933])) <class 'tuple'>
(tensor([1.9275, 1.9258, 0.4763]), tensor([ 0.8109,  0.5665, -1.5188]), tensor([ 0.9534, -0.8327, -0.9933]))
torch.Size([3])


## Set a matrix all negtive values to 0

In [20]:
input_tensor = torch.randn((2, 3, 4))
print(input_tensor)
input_tensor = torch.max(torch.zeros_like(input_tensor), input_tensor)
print(input_tensor)

tensor([[[-0.8786,  0.6568,  0.7157, -0.8748],
         [ 0.1681, -2.3124, -1.1988,  2.5490],
         [-1.0920, -1.5986, -0.1188,  0.2182]],

        [[-0.9203,  0.2892,  1.1653, -1.7656],
         [ 1.0775,  2.1220, -0.3829,  1.9707],
         [ 1.3156, -0.6420, -0.3613,  0.0979]]])
tensor([[[0.0000, 0.6568, 0.7157, 0.0000],
         [0.1681, 0.0000, 0.0000, 2.5490],
         [0.0000, 0.0000, 0.0000, 0.2182]],

        [[0.0000, 0.2892, 1.1653, 0.0000],
         [1.0775, 2.1220, 0.0000, 1.9707],
         [1.3156, 0.0000, 0.0000, 0.0979]]])


## Dimensions operation

In [27]:
### squeeze和unsqueeze的用法 https://pytorch.org/docs/stable/generated/torch.unsqueeze.html
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))

### Expand函数不复制张量元素
x = torch.tensor([1, 2, 3])
x = x.expand(2, 3)
print(x, x.shape)

### Repeat函数复制张量元素
y = torch.tensor([1, 2, 3])
y = y.repeat(2, 3)
print(y, y.shape)

### 使用Repeat可以为张量增加维度
y = torch.tensor([1, 2, 3])
print(y.shape)
y = y.unsqueeze(0).repeat(5, 1, 1)
print(y.shape)
print(y)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3],
        [1, 2, 3]]) torch.Size([2, 3])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]]) torch.Size([2, 9])
torch.Size([3])
torch.Size([5, 1, 3])
tensor([[[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]]])


## Conca, Stack operations

In [4]:
## stack operation
import torch

data = torch.arange(6).reshape(2, 3)
print(data)

data_a = [data, data, data]
data_b = torch.stack(data_a, dim=0)
print(data_b, data_b.shape)

data_a = [data, 
          data, 
          data]
data_b = torch.stack(data_a, dim=-1)
print(data_b, data_b.shape)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]]) torch.Size([3, 2, 3])
tensor([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]]]) torch.Size([2, 3, 3])


: 

In [28]:
### 连接堆叠操作
data_a = torch.randn(2, 3, 5, 96, 96)
data_b = torch.randn(2, 3, 5, 96, 96)
data_ab = torch.cat([data_a[:,i] for i in range(data_a.size(1))], dim=0)
print(data_ab.shape)

data_a = [torch.rand(5), torch.rand(5)]
data_b = torch.stack(data_a, 1)
print(data_b.shape)

data_a = [torch.rand((2,3)), torch.rand((2,3)), torch.rand((2,3))]
data_b = torch.stack(data_a, dim=0)
print("Stack result: \n", data_b, data_b.shape)

input_list = torch.Tensor([1, 2, 3, 4])

print(input_list.shape)

torch.Size([6, 5, 96, 96])
torch.Size([5, 2])
Stack result: 
 tensor([[[0.9829, 0.8784, 0.4056],
         [0.7488, 0.4011, 0.5612]],

        [[0.1599, 0.0827, 0.1275],
         [0.3106, 0.1268, 0.2426]],

        [[0.5175, 0.6330, 0.8574],
         [0.6942, 0.8501, 0.3712]]]) torch.Size([3, 2, 3])
torch.Size([4])


In [33]:
a=torch.tensor([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
print("a的shape：",a.shape)
#在第0维上进行split
b=torch.split(a, 1)
print("b:", b, len(b))
#在第1维上进行split
c=torch.split(a,[1,1],1)
print("c:",c)

a的shape： torch.Size([2, 2, 3])
b: (tensor([[[1, 2, 3],
         [4, 5, 6]]]), tensor([[[ 7,  8,  9],
         [10, 11, 12]]])) 2
c: (tensor([[[1, 2, 3]],

        [[7, 8, 9]]]), tensor([[[ 4,  5,  6]],

        [[10, 11, 12]]]))


In [16]:
gt_with_border = torch.rand((2, 10,3,128, 128))
border_size = int(1.5*3.0)
print(border_size)

scale = 4
n, t, c, gt_h, gt_w = gt_with_border.size()
lr_h = (gt_h - 2*border_size)//scale
lr_w = (gt_w - 2*border_size)//scale
print(lr_h, lr_w)

gt_data = gt_with_border[
                ...,
                border_size: border_size + scale*lr_h,
                border_size: border_size + scale*lr_w
            ]
print(gt_data.shape)

4
30 30
torch.Size([2, 10, 3, 120, 120])


## Tile and repeat the Tensor

In [4]:
## From pytorch 1.8, the torch.tile function has been removed,
## we can still use the repeat function
import torch
y = torch.tensor([[1, 2], [3, 4]])[None]
print(y, y.shape)

y = y.repeat((3, 1, 1))
print(y, y.shape)

y = y.reshape(-1, 2)
print(y, y.shape)

tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]]) torch.Size([3, 2, 2])
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]]) torch.Size([6, 2])


## Padding matrix

In [25]:
from torch.nn.utils.rnn import pad_sequence
import numpy as np

input_x =[[1,2,3],[4,5,6,7,8],[8,9]]
norm_data_pad = pad_sequence([torch.from_numpy(np.array(x)) for x in input_x], batch_first=True).float()
print(norm_data_pad)

arr1 = torch.rand(1, 3, 2)
arr2 = torch.rand(2, 3, 2)
arr3 = torch.rand(3, 3, 2)

norm_data_pad = pad_sequence([arr1, arr2, arr3], batch_first=True).float()
print(norm_data_pad.shape)
print(norm_data_pad[0])

tensor([[1., 2., 3., 0., 0.],
        [4., 5., 6., 7., 8.],
        [8., 9., 0., 0., 0.]])
torch.Size([3, 3, 3, 2])
tensor([[[0.6115, 0.5482],
         [0.9795, 0.7042],
         [0.9924, 0.8721]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000]]])


## Reshape

In [4]:
import torch

x = torch.randn(1, 42, 64)
print(x.shape)

cpatch = x[:, 0:16, 0:16]
cpatch = cpatch.reshape(cpatch.shape[0], -1)
print(cpatch.shape)

cpatch = cpatch[:, :-1]
print(cpatch.shape)

torch.Size([1, 42, 64])
torch.Size([1, 256])
torch.Size([1, 255])


## Repeat tensor

In [2]:
import torch

input = torch.randn(2, 3)
print(input)
print(input.shape)

input = input.repeat(1, 2)
print(input)
print(input.shape)

tensor([[ 0.0583,  0.7821,  0.8115],
        [ 1.6770,  0.3767, -0.4914]])
torch.Size([2, 3])
tensor([[ 0.0583,  0.7821,  0.8115,  0.0583,  0.7821,  0.8115],
        [ 1.6770,  0.3767, -0.4914,  1.6770,  0.3767, -0.4914]])
torch.Size([2, 6])


## View operations

In [25]:
import torch

downsample = 2
input = torch.randn(4, 4)
print(input)
H, W = input.shape
gt_depths = input.view(H // downsample,
                       downsample, W // downsample,
                       downsample, 1)
print(gt_depths)
print(gt_depths.shape)

tensor([[ 1.2284, -1.9785,  0.4349, -0.3315],
        [ 1.0020,  0.4194, -0.3357, -0.3839],
        [ 0.7561,  1.2428,  0.0676, -0.4730],
        [-0.5543, -0.4096,  1.9598,  0.4670]])
tensor([[[[[ 1.2284],
           [-1.9785]],

          [[ 0.4349],
           [-0.3315]]],


         [[[ 1.0020],
           [ 0.4194]],

          [[-0.3357],
           [-0.3839]]]],



        [[[[ 0.7561],
           [ 1.2428]],

          [[ 0.0676],
           [-0.4730]]],


         [[[-0.5543],
           [-0.4096]],

          [[ 1.9598],
           [ 0.4670]]]]])
torch.Size([2, 2, 2, 2, 1])


In [26]:
gt_depths = gt_depths.permute(0, 2, 4, 1, 3).contiguous()
gt_depths = gt_depths.view(-1, downsample * downsample)
print(gt_depths)
print(gt_depths.shape)

tensor([[ 1.2284, -1.9785,  1.0020,  0.4194],
        [ 0.4349, -0.3315, -0.3357, -0.3839],
        [ 0.7561,  1.2428, -0.5543, -0.4096],
        [ 0.0676, -0.4730,  1.9598,  0.4670]])
torch.Size([4, 4])


In [27]:
gt_depths_tmp = torch.where(gt_depths < 0.0,
                            1e5 * torch.ones_like(gt_depths),
                            gt_depths)
print(gt_depths_tmp)
gt_depths = torch.min(gt_depths_tmp, dim=-1).values
print(gt_depths)
print(gt_depths.shape)

gt_depths = gt_depths.view(H // downsample,
                            W // downsample)

print(gt_depths)
print(gt_depths.shape)

tensor([[1.2284e+00, 1.0000e+05, 1.0020e+00, 4.1941e-01],
        [4.3488e-01, 1.0000e+05, 1.0000e+05, 1.0000e+05],
        [7.5608e-01, 1.2428e+00, 1.0000e+05, 1.0000e+05],
        [6.7553e-02, 1.0000e+05, 1.9598e+00, 4.6698e-01]])
tensor([0.4194, 0.4349, 0.7561, 0.0676])
torch.Size([4])
tensor([[0.4194, 0.4349],
        [0.7561, 0.0676]])
torch.Size([2, 2])


In [11]:
import torch

input = torch.randn(1, 3, 5)
print(input.shape)
mask = torch.randint_like(input, 0, 2).bool()
print(mask, mask.shape)

output = input[mask]
print(output.shape)

torch.Size([1, 3, 5])
tensor([[[ True, False,  True,  True, False],
         [ True, False,  True,  True, False],
         [False, False,  True,  True,  True]]]) torch.Size([1, 3, 5])
torch.Size([9])


In [3]:
import torch
import numpy as np

curr_img2global = np.random.randn(4, 4)
adj_img_to_global = np.random.randn(4, 4)

curr_img_to_adj_img = np.linalg.inv(adj_img_to_global) @ curr_img2global
print(curr_img_to_adj_img)

curr_img2global[:2] *= 0.2
adj_img_to_global[:2] *= 0.2

curr_img_to_adj_img = np.linalg.inv(adj_img_to_global) @ curr_img2global
print(curr_img_to_adj_img)

[[-0.06632878 -0.11755253 -0.97472341 -0.44844803]
 [-0.46412638  2.17743045 -1.74345384  1.89693474]
 [-0.5920778  -0.08032467 -1.27751084  1.40742789]
 [-0.72611626 -1.27796876  0.00784594  0.45861456]]
[[-0.06632878 -0.11755253 -0.97472341 -0.44844803]
 [-0.46412638  2.17743045 -1.74345384  1.89693474]
 [-0.5920778  -0.08032467 -1.27751084  1.40742789]
 [-0.72611626 -1.27796876  0.00784594  0.45861456]]


In [1]:
import torch

inputs = torch.Tensor([])
all_inputs = [inputs, inputs]
data = torch.stack(all_inputs)
print(data.shape)

torch.Size([2, 0])


In [2]:
import torch

sh = torch.randn(2, 10, 3, 4)
print(sh.shape)

opacities = torch.randn(2, 10)

sh_2 = sh.broadcast_to((*opacities.shape, 3, 4))
print(sh_2.shape)

torch.Size([2, 10, 3, 4])
torch.Size([2, 10, 3, 4])
