In [2]:
import torch
import numpy as np
from torch.nn import functional as F

In [39]:
msm_bernoulli_prob = [0.2, 0.8]

p = np.random.uniform(*msm_bernoulli_prob)
print(p)
mask1 = torch.bernoulli(torch.ones(3, 4) * p)
print(mask1)


0.33066794459097115
tensor([[1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [1., 0., 1., 0.]])


In [6]:
x = torch.rand(2, 3)
print(x)

y = F.softmax(x, dim=1)
print(y)

z = torch.sum(y, dim=1)
print(z)

tensor([[0.6817, 0.9028, 0.9015],
        [0.7266, 0.8289, 0.2455]])
tensor([[0.2863, 0.3571, 0.3566],
        [0.3669, 0.4064, 0.2268]])
tensor([1., 1.])


## torch.min() and torch.max()

In [10]:
import torch

data = torch.randn(3, 2)
print(data)

min_dist, min_idx = torch.min(data, dim=-1)
print(min_dist, min_dist.shape)
print(min_idx)

min_dist = min_dist.unsqueeze(-1)
print(min_dist, min_dist.shape)


input = torch.randn(5, 6, 256, 196).requires_grad_()
print(input.shape, input.requires_grad)
output = torch.max(input, dim=1)[0]
print(output.shape, output.requires_grad)

tensor([[ 0.9402, -0.5233],
        [ 0.6936, -0.0681],
        [ 1.7741,  0.9901]])
tensor([-0.5233, -0.0681,  0.9901]) torch.Size([3])
tensor([1, 1, 1])
tensor([[-0.5233],
        [-0.0681],
        [ 0.9901]]) torch.Size([3, 1])
torch.Size([5, 6, 256, 196]) True
torch.Size([5, 256, 196]) True


## torch.mean()

In [8]:
import torch
data = torch.arange(10).reshape(5, 2).float()
print(data)
data_mean = torch.mean(data, dim=1)
print(data_mean)
data_mean2 = torch.mean(data_mean)
print(data_mean2)

data_meann = torch.mean(data)
print(data_meann)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])
tensor([0.5000, 2.5000, 4.5000, 6.5000, 8.5000])
tensor(4.5000)
tensor(4.5000)


## torch.argmin

In [4]:
import torch

distances = torch.randn(5, 2)
print(distances)

dis_idx = torch.argmin(distances, axis=1)
print(dis_idx, dis_idx.shape)

tensor([[ 2.7553,  1.3871],
        [ 1.0058, -1.3197],
        [ 0.9727,  0.0923],
        [ 2.9525, -1.1732],
        [-0.7277,  1.3667]])
tensor([1, 1, 1, 1, 0]) torch.Size([5])


## torch.linspace

In [5]:
import torch

X = torch.linspace(1, 10, 10)
print(X, X.shape)

X_splited = X.split(4)
print(len(X_splited), type(X_splited))
print(X_splited)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
3 <class 'tuple'>
(tensor([1., 2., 3., 4.]), tensor([5., 6., 7., 8.]), tensor([ 9., 10.]))


## torch.cdist
https://pytorch.org/docs/stable/generated/torch.cdist.html

In [4]:
import torch

x1 = torch.arange(4).reshape(2, 2).to(torch.float)
x2 = torch.arange(6).reshape(3, 2).to(torch.float)
print(x1, x1.shape)
print(x2, x2.dtype, x2.shape)

dist = torch.cdist(x1, x2)
dist = torch.cdist(x2, x1)
print(dist, dist.shape)

tensor([[0., 1.],
        [2., 3.]]) torch.Size([2, 2])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]]) torch.float32 torch.Size([3, 2])
tensor([[0.0000, 2.8284],
        [2.8284, 0.0000],
        [5.6569, 2.8284]]) torch.Size([3, 2])


## torch.gather

https://pytorch.org/docs/stable/generated/torch.gather.html

```bash
torch.gather(input, dim, index, *, sparse_grad=False, out=None) → Tensor

out will have the same shape as index
```


In [ ]:
torch.gather(input, dim, index)

## torch.masked_select

In [4]:
import torch
x = torch.randn([3, 4])
print(x)
# 将x中的每一个元素与0.5进行比较
# 当元素大于等于0.5返回True,否则返回False
mask = x.ge(0.5)
print(mask)
print(torch.masked_select(x, mask))

tensor([[-2.1747, -0.1719,  0.7052,  0.3118],
        [ 0.5429, -0.5695, -0.5542,  0.6174],
        [-0.8066, -0.7021, -0.3135, -2.0744]])
tensor([[False, False,  True, False],
        [ True, False, False,  True],
        [False, False, False, False]])
tensor([0.7052, 0.5429, 0.6174])


## torch.topk

In [10]:
import torch

pred = torch.randn((4, 5))
print(pred)
values, indices = pred.topk(3, dim=-1, largest=False, sorted=False)
print(values)
print(indices)

pc = torch.randn(100, 3)
pc = pc[indices]
print(pc.shape)

tensor([[ 0.3988, -0.4285,  0.9232, -0.0042, -1.7357],
        [-0.5347,  1.1426, -1.2428,  0.7063,  1.0780],
        [ 0.9742, -0.0708,  0.3661,  0.8740,  0.9038],
        [ 0.5233,  0.0808,  0.3399, -0.7865,  0.0210]])
tensor([[-0.4285, -1.7357, -0.0042],
        [-0.5347, -1.2428,  0.7063],
        [ 0.3661, -0.0708,  0.8740],
        [-0.7865,  0.0210,  0.0808]])
tensor([[1, 4, 3],
        [0, 2, 3],
        [2, 1, 3],
        [3, 4, 1]])


In [2]:
import torch

q_loc = torch.normal(mean=0.0, std=1,
                     size=(5, 3))
print(q_loc)

tensor([[ 0.4793, -0.6942, -0.0746],
        [-0.5317,  1.2179,  1.0645],
        [-0.7935,  2.3039, -0.7851],
        [ 0.3673,  1.7328, -0.6026],
        [-0.1441,  0.9631, -0.7099]])


## torch.repeat_interleave
https://blog.csdn.net/weixin_45261707/article/details/119187799

In [7]:
import torch

B = 6
N = 1

batch = torch.arange(B).reshape(3, 2)
print(batch, batch.shape)

batch = torch.repeat_interleave(batch, N)
print(batch, batch.shape)
batch = batch.reshape(3, 2)
print(batch)

tensor([[0, 1],
        [2, 3],
        [4, 5]]) torch.Size([3, 2])
tensor([0, 1, 2, 3, 4, 5]) torch.Size([6])
tensor([[0, 1],
        [2, 3],
        [4, 5]])


## torch.randperm

In [3]:
import torch

index = torch.randperm(10)
print(index, index.shape, index.dtype)

tensor([1, 4, 3, 0, 6, 7, 9, 8, 2, 5]) torch.Size([10]) torch.int64


## torch.cumsum
https://pytorch.org/docs/stable/generated/torch.cumsum.html

In [7]:
import torch

a = torch.arange(10).reshape(2, 5)
print(a, a.shape)
out = torch.cumsum(a, dim=1)
print(out, out.shape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) torch.Size([2, 5])
tensor([[ 0,  1,  3,  6, 10],
        [ 5, 11, 18, 26, 35]]) torch.Size([2, 5])


## Transpose

In [5]:
import torch

input = torch.randn(5, 1024, 3)

input = input.transpose(2, 1)
# input = input.transpose(1, 2)
print(input.shape)

torch.Size([5, 3, 1024])


In [7]:
import torch

beta = 0.5

w_avg = torch.ones(10)
w = torch.rand(10)
print(w)
out = w_avg.lerp(w, beta)
print(out, out.shape)

tensor([0.4084, 0.2738, 0.2688, 0.6091, 0.1376, 0.1700, 0.5771, 0.8596, 0.2714,
        0.3064])
tensor([0.7042, 0.6369, 0.6344, 0.8046, 0.5688, 0.5850, 0.7885, 0.9298, 0.6357,
        0.6532]) torch.Size([10])


## torch.where

In [14]:
import torch

data = torch.randn(3, 4)
print(data, data.shape)

mask = data > 0.5
print(mask, mask.shape)

others = torch.randn(3, 4, 3)

data2 = others[mask]
print(data2, data2.shape)

tensor([[-0.0922,  1.7921,  0.8308, -3.5614],
        [-1.5490, -0.6031,  0.7743, -1.2391],
        [ 0.3471, -0.0755, -0.2125,  0.1686]]) torch.Size([3, 4])
tensor([[False,  True,  True, False],
        [False, False,  True, False],
        [False, False, False, False]]) torch.Size([3, 4])
tensor([[ 1.2382, -0.6162,  0.9906],
        [-2.0638, -0.1396, -1.5969],
        [ 0.1864, -1.8095,  0.9308]]) torch.Size([3, 3])


In [9]:
import torch

mask = [[1, 0, 1, 1],
        [0, 1, 1, 0]]
mask = torch.zeros(2, 4)
mask = torch.asarray(mask)
print(mask)

dd = (mask == 1)
print(dd)

print(mask.shape)

idx = torch.where(mask)
print(idx)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[False, False, False, False],
        [False, False, False, False]])
torch.Size([2, 4])
(tensor([], dtype=torch.int64), tensor([], dtype=torch.int64))


In [2]:
dd = range(50, 100)
print(dd, list(dd))

range(50, 100) [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
