In [2]:
import torch
import numpy as np
from torch.nn import functional as F

In [4]:
aa = [1, 2, 3, 4]
import numpy as np

np.random.shuffle(aa)
print(aa)

[3, 4, 2, 1]


In [39]:
msm_bernoulli_prob = [0.2, 0.8]

p = np.random.uniform(*msm_bernoulli_prob)
print(p)
mask1 = torch.bernoulli(torch.ones(3, 4) * p)
print(mask1)

0.33066794459097115
tensor([[1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [1., 0., 1., 0.]])


In [6]:
x = torch.rand(2, 3)
print(x)

y = F.softmax(x, dim=1)
print(y)

z = torch.sum(y, dim=1)
print(z)

tensor([[0.6817, 0.9028, 0.9015],
        [0.7266, 0.8289, 0.2455]])
tensor([[0.2863, 0.3571, 0.3566],
        [0.3669, 0.4064, 0.2268]])
tensor([1., 1.])


## torch.any

In [23]:
import torch

x = torch.randint(0, 10, (2, 3))
print(x)

if torch.any(x == 5):
    print('yes')
else:
    print('no')

tensor([[7, 6, 2],
        [3, 1, 7]])
no


## torch.eq

In [ ]:
# Import torch and create dummy tensors
import torch

A = torch.randint(2, (5,))
print(A)
B = torch.randint(2, (5,))
print(B)
# Checking for number of equal values
C = torch.eq(A, B)
C

tensor([0, 1, 0, 1, 0])
tensor([1, 1, 1, 0, 1])


tensor([False,  True, False, False, False])

In [19]:
import torch

a = torch.randint(2, (5,), dtype=torch.bool)
print(a)

b = torch.randint(2, (5,), dtype=torch.bool)
print(b)

c = a & b
print(c)

# get the indices
idx = torch.where(c)
print(idx)

tensor([ True, False, False,  True,  True])
tensor([ True, False,  True,  True,  True])
tensor([ True, False, False,  True,  True])
(tensor([0, 3, 4]),)


## torch.expand()

In [4]:
import torch

data = torch.rand(3)
print(data, data.shape)

data = data.expand((4, 3))
print(data.shape)

tensor([0.8704, 0.7653, 0.5003]) torch.Size([3])
torch.Size([4, 3])


## torch.flatten

In [9]:
import torch

data = torch.tensor(3)
print(data, data.shape)

data = data.flatten()
print(data, data.shape)



tensor(3) torch.Size([])
tensor([3]) torch.Size([1])


## torch.min() and torch.max()

In [10]:
import torch

data = torch.randn(2, 3)
print(data)

max_data = data.max()
print(max_data)

tensor([[-0.8369, -0.8041,  0.0486],
        [-0.2859, -0.4030, -1.2867]])
tensor(0.0486)


In [10]:
import torch

data = torch.randn(3, 2)
print(data)

min_dist, min_idx = torch.min(data, dim=-1)
print(min_dist, min_dist.shape)
print(min_idx)

min_dist = min_dist.unsqueeze(-1)
print(min_dist, min_dist.shape)


input = torch.randn(5, 6, 256, 196).requires_grad_()
print(input.shape, input.requires_grad)
output = torch.max(input, dim=1)[0]
print(output.shape, output.requires_grad)

tensor([[ 0.9402, -0.5233],
        [ 0.6936, -0.0681],
        [ 1.7741,  0.9901]])
tensor([-0.5233, -0.0681,  0.9901]) torch.Size([3])
tensor([1, 1, 1])
tensor([[-0.5233],
        [-0.0681],
        [ 0.9901]]) torch.Size([3, 1])
torch.Size([5, 6, 256, 196]) True
torch.Size([5, 256, 196]) True


## torch.mean()

In [8]:
import torch
data = torch.arange(10).reshape(5, 2).float()
print(data)
data_mean = torch.mean(data, dim=1)
print(data_mean)
data_mean2 = torch.mean(data_mean)
print(data_mean2)

data_meann = torch.mean(data)
print(data_meann)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])
tensor([0.5000, 2.5000, 4.5000, 6.5000, 8.5000])
tensor(4.5000)
tensor(4.5000)


## torch.meshgrid

In [1]:
import torch

h, w = 2, 3
lin_y = torch.arange(0, h)
lin_x = torch.arange(0, w)
grid_y, grid_x = torch.meshgrid((lin_y, lin_x))
grid = torch.stack((grid_x, grid_y), -1)

print(lin_y)
print(lin_x)
print(grid_y)
print(grid_x)
print(grid, grid.shape)

tensor([0, 1])
tensor([0, 1, 2])
tensor([[0, 0, 0],
        [1, 1, 1]])
tensor([[0, 1, 2],
        [0, 1, 2]])
tensor([[[0, 0],
         [1, 0],
         [2, 0]],

        [[0, 1],
         [1, 1],
         [2, 1]]]) torch.Size([2, 3, 2])


/data/zhanghm/miniconda3/envs/bevdet_py38/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [2]:
import torch

x_bound = [-40, 40, 0.8]
y_bound = [-40, 40, 0.8]
z_bound = [-1, 5.4, 1.6]

X = torch.arange(*x_bound, dtype=torch.float) + x_bound[-1]/2
Y = torch.arange(*y_bound, dtype=torch.float) + y_bound[-1]/2
Z = torch.arange(*z_bound, dtype=torch.float) + z_bound[-1]/2
Y, X, Z = torch.meshgrid([Y, X, Z])
coords = torch.stack([X, Y, Z], dim=-1)
print(coords.shape)

## torch.argmin

In [4]:
import torch

distances = torch.randn(5, 2)
print(distances)

dis_idx = torch.argmin(distances, axis=1)
print(dis_idx, dis_idx.shape)

tensor([[ 2.7553,  1.3871],
        [ 1.0058, -1.3197],
        [ 0.9727,  0.0923],
        [ 2.9525, -1.1732],
        [-0.7277,  1.3667]])
tensor([1, 1, 1, 1, 0]) torch.Size([5])


## torch.linspace

In [5]:
import torch

X = torch.linspace(1, 10, 10)
print(X, X.shape)

X_splited = X.split(4)
print(len(X_splited), type(X_splited))
print(X_splited)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
3 <class 'tuple'>
(tensor([1., 2., 3., 4.]), tensor([5., 6., 7., 8.]), tensor([ 9., 10.]))


## torch.multinomial
https://pytorch.org/docs/stable/generated/torch.multinomial.html#torch.multinomial

In [45]:
import torch
import numpy as np

num_random_view = 3
rand_ind = torch.multinomial(
                    torch.tensor([1/num_random_view] * 6), 
                    num_random_view, 
                    replacement=False)
print(rand_ind)

dummy_rand_ind = torch.arange(6)
print(dummy_rand_ind)

a = torch.tensor([1, 2, 3, 4])
p = torch.tensor([0.1, 0.2, 0.2, 0.6])
n = 2
replace = False
idx = p.multinomial(num_samples=n, replacement=replace)
b = a[idx]
print(b)

tensor([0, 3, 2])
tensor([0, 1, 2, 3, 4, 5])
tensor([4, 3])


## torch.nonzero

In [5]:
# Create a sample instance map tensor
H, W = 5, 5
instance_map = torch.randint(0, 10, size=(H, W))

print(instance_map, instance_map.shape)

instance_id = 1
mask = instance_map == instance_id  # Create a mask for the current instance
valid_indices = torch.nonzero(mask)
print(valid_indices, valid_indices.shape)

tensor([[2, 4, 5, 0, 5],
        [5, 8, 9, 7, 2],
        [4, 2, 1, 1, 0],
        [9, 5, 2, 4, 4],
        [2, 5, 8, 3, 6]]) torch.Size([5, 5])
tensor([[2, 2],
        [2, 3]]) torch.Size([2, 2])


In [16]:
import torch

# Create a sample instance map tensor
H, W = 5, 5
instance_map = torch.randint(0, 10, size=(H, W, 1))  # Replace with your instance map tensor

# Step 1: Compute unique instance IDs
unique_instance_ids = torch.unique(instance_map)
print(unique_instance_ids, unique_instance_ids.shape)

# Step 2: Generate random indices for each unique instance
random_indices = torch.randint(0, H * W, size=(len(unique_instance_ids),))

# Create a mask with the shape [H, W, num_unique_instances]
mask = instance_map.unsqueeze(2) == unique_instance_ids.unsqueeze(1)
print(mask.shape)

# Use scatter to select one random pixel from each instance
selected_pixels = torch.where(mask, random_indices, H * W).min(dim=2)[0]

# Print the selected pixels
print(selected_pixels)


tensor([0, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
torch.Size([5, 5, 9, 1])
tensor([[[19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13]],

        [[19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13]],

        [[19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13]],

        [[19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3, 15, 11, 13,  0, 13],
         [19,  2, 13,  3

In [29]:
import torch

# Create a sample instance map tensor
H, W = 3, 3
instance_map = torch.randint(0, 10, size=(H, W))  # Replace with your instance map tensor
print(instance_map, instance_map.shape)
# Step 1: Compute unique instance IDs
unique_instance_ids = torch.unique(instance_map)
print(unique_instance_ids)

# Step 2: Generate random indices for each unique instance
random_indices = torch.randint(0, H * W, size=(len(unique_instance_ids),))

# Create a mask with the shape [H, W, num_unique_instances]
mask = instance_map == unique_instance_ids[0]
print(mask, mask.shape)

mask = (instance_map.unsqueeze(2) == unique_instance_ids)
print(mask[..., 0], mask.shape)
print(mask[..., -1], mask.shape)

selected_pixels = torch.nonzero(mask[None])
print(selected_pixels, selected_pixels.shape)

# Use scatter to select one random pixel from each instance
selected_pixels = (mask * random_indices).sum(dim=2).long()

# Print the selected pixels
print(selected_pixels)


tensor([[3, 7, 5],
        [5, 3, 7],
        [6, 0, 1]]) torch.Size([3, 3])
tensor([0, 1, 3, 5, 6, 7])
tensor([[False, False, False],
        [False, False, False],
        [False,  True, False]]) torch.Size([3, 3])
tensor([[False, False, False],
        [False, False, False],
        [False,  True, False]]) torch.Size([3, 3, 6])
tensor([[False,  True, False],
        [False, False,  True],
        [False, False, False]]) torch.Size([3, 3, 6])
tensor([[0, 0, 0, 2],
        [0, 0, 1, 5],
        [0, 0, 2, 3],
        [0, 1, 0, 3],
        [0, 1, 1, 2],
        [0, 1, 2, 5],
        [0, 2, 0, 4],
        [0, 2, 1, 0],
        [0, 2, 2, 1]]) torch.Size([9, 4])
tensor([[8, 3, 2],
        [2, 8, 3],
        [5, 6, 0]])


## torch.cdist
https://pytorch.org/docs/stable/generated/torch.cdist.html

In [4]:
import torch

x1 = torch.arange(4).reshape(2, 2).to(torch.float)
x2 = torch.arange(6).reshape(3, 2).to(torch.float)
print(x1, x1.shape)
print(x2, x2.dtype, x2.shape)

dist = torch.cdist(x1, x2)
dist = torch.cdist(x2, x1)
print(dist, dist.shape)

tensor([[0., 1.],
        [2., 3.]]) torch.Size([2, 2])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]]) torch.float32 torch.Size([3, 2])
tensor([[0.0000, 2.8284],
        [2.8284, 0.0000],
        [5.6569, 2.8284]]) torch.Size([3, 2])


## torch.rot90 & torch.flip

In [5]:
import torch

x_raw = torch.arange(6).reshape(2, 3).to(torch.float)
print(x_raw, x_raw.shape)

x = torch.flip(x_raw, dims=[0])
print(x, x.shape)

y = x_raw.numpy()
print(y, y.shape)

y = y[::-1, ...]
print(y, y.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]]) torch.Size([2, 3])
tensor([[3., 4., 5.],
        [0., 1., 2.]]) torch.Size([2, 3])
[[0. 1. 2.]
 [3. 4. 5.]] (2, 3)
[[3. 4. 5.]
 [0. 1. 2.]] (2, 3)


## torch.gather

https://pytorch.org/docs/stable/generated/torch.gather.html

```bash
torch.gather(input, dim, index, *, sparse_grad=False, out=None) → Tensor

out will have the same shape as index
```


In [ ]:
torch.gather(input, dim, index)

## torch.masked_select

In [4]:
import torch
x = torch.randn([3, 4])
print(x)
# 将x中的每一个元素与0.5进行比较
# 当元素大于等于0.5返回True,否则返回False
mask = x.ge(0.5)
print(mask)
print(torch.masked_select(x, mask))

tensor([[-2.1747, -0.1719,  0.7052,  0.3118],
        [ 0.5429, -0.5695, -0.5542,  0.6174],
        [-0.8066, -0.7021, -0.3135, -2.0744]])
tensor([[False, False,  True, False],
        [ True, False, False,  True],
        [False, False, False, False]])
tensor([0.7052, 0.5429, 0.6174])


## torch.permute

In [8]:
import torch

input = torch.arange(12).reshape(2, 2, 3)
print(input)

output = input.transpose(0, 1)
print(output.shape, output.is_contiguous())
output = output.reshape(-1, 3)
print(output)

output = input.permute(1, 0, 2)
print(output)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([2, 2, 3]) False
tensor([[ 0,  1,  2],
        [ 6,  7,  8],
        [ 3,  4,  5],
        [ 9, 10, 11]])
tensor([[[ 0,  1,  2],
         [ 6,  7,  8]],

        [[ 3,  4,  5],
         [ 9, 10, 11]]])


## torch.split

In [1]:
import torch

x = torch.randn((2, 5, 3))

print(x)

x = torch.split(x, 1, dim=0)
print(type(x), len(x), x[0].shape)

x = torch.cat(x, dim=-1)
print(x.shape)

print(x)

tensor([[[-0.7344,  1.6499, -0.2924],
         [ 0.1482, -1.5709, -0.7470],
         [ 0.3299,  0.7175, -0.3415],
         [ 0.5543,  0.5210,  0.5650],
         [ 1.5115,  0.1675,  1.3452]],

        [[-1.0781, -2.3267, -1.1224],
         [-1.9603, -0.6313, -1.6316],
         [ 0.9826,  0.0818, -1.2699],
         [ 0.1995, -0.5995, -0.4268],
         [ 0.2989, -1.6949,  0.1793]]])
<class 'tuple'> 2 torch.Size([1, 5, 3])
torch.Size([1, 5, 6])
tensor([[[-0.7344,  1.6499, -0.2924, -1.0781, -2.3267, -1.1224],
         [ 0.1482, -1.5709, -0.7470, -1.9603, -0.6313, -1.6316],
         [ 0.3299,  0.7175, -0.3415,  0.9826,  0.0818, -1.2699],
         [ 0.5543,  0.5210,  0.5650,  0.1995, -0.5995, -0.4268],
         [ 1.5115,  0.1675,  1.3452,  0.2989, -1.6949,  0.1793]]])


## torch.topk

In [10]:
import torch

pred = torch.randn((4, 5))
print(pred)
values, indices = pred.topk(3, dim=-1, largest=False, sorted=False)
print(values)
print(indices)

pc = torch.randn(100, 3)
pc = pc[indices]
print(pc.shape)

tensor([[ 0.3988, -0.4285,  0.9232, -0.0042, -1.7357],
        [-0.5347,  1.1426, -1.2428,  0.7063,  1.0780],
        [ 0.9742, -0.0708,  0.3661,  0.8740,  0.9038],
        [ 0.5233,  0.0808,  0.3399, -0.7865,  0.0210]])
tensor([[-0.4285, -1.7357, -0.0042],
        [-0.5347, -1.2428,  0.7063],
        [ 0.3661, -0.0708,  0.8740],
        [-0.7865,  0.0210,  0.0808]])
tensor([[1, 4, 3],
        [0, 2, 3],
        [2, 1, 3],
        [3, 4, 1]])


In [2]:
import torch

q_loc = torch.normal(mean=0.0, std=1,
                     size=(5, 3))
print(q_loc)

tensor([[ 0.4793, -0.6942, -0.0746],
        [-0.5317,  1.2179,  1.0645],
        [-0.7935,  2.3039, -0.7851],
        [ 0.3673,  1.7328, -0.6026],
        [-0.1441,  0.9631, -0.7099]])


## torch.repeat_interleave
https://blog.csdn.net/weixin_45261707/article/details/119187799

In [7]:
import torch

B = 6
N = 1

batch = torch.arange(B).reshape(3, 2)
print(batch, batch.shape)

batch = torch.repeat_interleave(batch, N)
print(batch, batch.shape)
batch = batch.reshape(3, 2)
print(batch)

tensor([[0, 1],
        [2, 3],
        [4, 5]]) torch.Size([3, 2])
tensor([0, 1, 2, 3, 4, 5]) torch.Size([6])
tensor([[0, 1],
        [2, 3],
        [4, 5]])


## torch.randperm
https://pytorch.org/docs/stable/generated/torch.randperm.html

In [32]:
import torch

index = torch.randperm(10)
print(index, index.shape, index.dtype)

tensor([0, 6, 4, 2, 3, 1, 9, 7, 5, 8]) torch.Size([10]) torch.int64


## torch.random

In [ ]:
import torch

torch.random.choice()


## torch.cumsum
https://pytorch.org/docs/stable/generated/torch.cumsum.html

In [7]:
import torch

a = torch.arange(10).reshape(2, 5)
print(a, a.shape)
out = torch.cumsum(a, dim=1)
print(out, out.shape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) torch.Size([2, 5])
tensor([[ 0,  1,  3,  6, 10],
        [ 5, 11, 18, 26, 35]]) torch.Size([2, 5])


## Transpose

In [5]:
import torch

input = torch.randn(5, 1024, 3)

input = input.transpose(2, 1)
# input = input.transpose(1, 2)
print(input.shape)

torch.Size([5, 3, 1024])


In [7]:
import torch

beta = 0.5

w_avg = torch.ones(10)
w = torch.rand(10)
print(w)
out = w_avg.lerp(w, beta)
print(out, out.shape)

tensor([0.4084, 0.2738, 0.2688, 0.6091, 0.1376, 0.1700, 0.5771, 0.8596, 0.2714,
        0.3064])
tensor([0.7042, 0.6369, 0.6344, 0.8046, 0.5688, 0.5850, 0.7885, 0.9298, 0.6357,
        0.6532]) torch.Size([10])


## torch.where

In [1]:
import torch

data = torch.randn(3, 4)
print(data, data.shape)

mask = data > 0.5
print(mask, mask.shape)

occIdx = torch.where(mask)
print(occIdx, type(occIdx))

others = torch.randn(3, 4, 3)

data2 = others[mask]
print(data2, data2.shape)

tensor([[-0.4152, -0.1302,  1.3266,  0.2277],
        [-0.8039,  0.0621, -2.2380,  0.3965],
        [ 0.1304,  0.9455, -1.8112, -0.1149]]) torch.Size([3, 4])
tensor([[False, False,  True, False],
        [False, False, False, False],
        [False,  True, False, False]]) torch.Size([3, 4])
(tensor([0, 2]), tensor([2, 1])) <class 'tuple'>
tensor([[-0.5990,  0.3586,  0.7046],
        [-1.1091,  0.6062, -1.2518]]) torch.Size([2, 3])


: 

In [9]:
import torch

mask = [[1, 0, 1, 1],
        [0, 1, 1, 0]]
mask = torch.zeros(2, 4)
mask = torch.asarray(mask)
print(mask)

dd = (mask == 1)
print(dd)

print(mask.shape)

idx = torch.where(mask)
print(idx)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[False, False, False, False],
        [False, False, False, False]])
torch.Size([2, 4])
(tensor([], dtype=torch.int64), tensor([], dtype=torch.int64))


In [2]:
dd = range(50, 100)
print(dd, list(dd))

range(50, 100) [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
