In [2]:
import torch
import numpy as np
from torch.nn import functional as F

In [39]:
msm_bernoulli_prob = [0.2, 0.8]

p = np.random.uniform(*msm_bernoulli_prob)
print(p)
mask1 = torch.bernoulli(torch.ones(3, 4) * p)
print(mask1)


0.33066794459097115
tensor([[1., 1., 1., 0.],
        [0., 0., 0., 0.],
        [1., 0., 1., 0.]])


In [6]:
x = torch.rand(2, 3)
print(x)

y = F.softmax(x, dim=1)
print(y)

z = torch.sum(y, dim=1)
print(z)

tensor([[0.6817, 0.9028, 0.9015],
        [0.7266, 0.8289, 0.2455]])
tensor([[0.2863, 0.3571, 0.3566],
        [0.3669, 0.4064, 0.2268]])
tensor([1., 1.])


## torch.argmin

In [4]:
import torch

distances = torch.randn(5, 2)
print(distances)

dis_idx = torch.argmin(distances, axis=1)
print(dis_idx, dis_idx.shape)

tensor([[ 2.7553,  1.3871],
        [ 1.0058, -1.3197],
        [ 0.9727,  0.0923],
        [ 2.9525, -1.1732],
        [-0.7277,  1.3667]])
tensor([1, 1, 1, 1, 0]) torch.Size([5])
