In [1]:
import torch
import torch.nn as nn
import numpy as np


### Get number of parameters in Module
def get_num_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

## Parameter class

In [2]:
import torch
import torch.nn as nn

learn_data = nn.Parameter(torch.randn(10, 10))
print(type(learn_data), learn_data.requires_grad)  # requires_grad is True by default
print(type(learn_data.data), learn_data.shape)

print(learn_data.shape)

<class 'torch.nn.parameter.Parameter'> True
<class 'torch.Tensor'> torch.Size([10, 10])
torch.Size([10, 10])


## Module class

In [31]:
class Dummy(nn.Module):
    def __init__(self):
        super(Dummy, self).__init__()

        emb = nn.Parameter(torch.randn(10, 10))
        self.register_parameter('emb', emb)

        buffer = torch.randn(2, 3)  # tensor
        self.register_buffer('my_buffer', buffer)

        self.weight = nn.Parameter(torch.randn(10, 10))
        self.conv = nn.Conv2d(3, 10, 5)
        layers = [self.conv, self.conv]

        self.style = nn.Sequential(nn.Conv2d(1, 20, 5), nn.ReLU())

    def forward(self, x):
        return x * self.weight

net = Dummy()

print("The total number of parameters in module is:", get_num_parameters(net))
print('Total number of parameters: {:.3f}M'.format(get_num_parameters(net) / 1e6))

params = net.parameters()
for i in params:
    print(i.shape)

for buffer in net.buffers():
    print("buffer: ", buffer.shape)

for name, params in net.named_parameters():
    print(name, params.shape, params.requires_grad)

print(net)
print(net.state_dict().keys())

The total number of parameters in module is: 1480
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 3, 5, 5])
torch.Size([10])
torch.Size([20, 1, 5, 5])
torch.Size([20])
buffer:  torch.Size([2, 3])
emb torch.Size([10, 10]) True
weight torch.Size([10, 10]) True
conv.weight torch.Size([10, 3, 5, 5]) True
conv.bias torch.Size([10]) True
style.0.weight torch.Size([20, 1, 5, 5]) True
style.0.bias torch.Size([20]) True
Dummy(
  (conv): Conv2d(3, 10, kernel_size=(5, 5), stride=(1, 1))
  (style): Sequential(
    (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU()
  )
)
odict_keys(['emb', 'weight', 'my_buffer', 'conv.weight', 'conv.bias', 'style.0.weight', 'style.0.bias'])


## BatchNorm

In [8]:
norm = nn.BatchNorm2d(512)

input = torch.randn(1, 512, 64, 64)
output = norm(input)
print(output.shape)

print("The total number of parameters in module is:")
pytorch_total_params = get_num_parameters(norm)
print(pytorch_total_params)

torch.Size([1, 512, 64, 64])
The total number of parameters in module is:
1024


## Linear layer

In [26]:
from icecream import ic as print

fc = nn.Linear(8, 128)

input_data = torch.randn(64, 60, 8, requires_grad=True)
input_data = torch.randn(64, 60, 8)
# by default, the requires_grad of parameters is True
output = fc(input_data)
print(input_data.requires_grad, output.requires_grad) 
print(fc.weight.requires_grad, fc.bias.requires_grad)

print("Use torch.no_grad")
with torch.no_grad():
    output = fc(input_data)
    print(fc.weight.requires_grad, fc.bias.requires_grad)
    print(input_data.requires_grad, output.requires_grad)

print("Set network requires_grad False")
input_data = torch.randn(64, 60, 8, requires_grad=True)
input_data = torch.randn(64, 60, 8)
fc.requires_grad_(False)
print(fc.weight.requires_grad, fc.bias.requires_grad)
output = fc(input_data)
print(input_data.requires_grad, output.requires_grad)

ic| input_data.requires_grad: False, output.requires_grad: True
ic| fc.weight.requires_grad: True, fc.bias.requires_grad: True
ic| 'Use torch.no_grad'
ic| fc.weight.requires_grad: True, fc.bias.requires_grad: True
ic| input_data.requires_grad: False, output.requires_grad: False
ic| 'Set network requires_grad False'
ic| fc.weight.requires_grad: False, fc.bias.requires_grad: False
ic| input_data.requires_grad: False, output.requires_grad: False


(False, False)

## Identity Module

In [3]:
## To be as a placeholder in code, don't use any passed arguments
m = nn.Identity(54, unused_argument1=0.1, unused_argument2=False)
input = torch.randn(3, 4)
print(input)

output = m(input)  # Do nothing
print(output)

tensor([[-0.8822, -0.3836, -0.4453,  0.4732],
        [-0.2166,  1.7199,  0.8660, -1.1443],
        [-1.3421,  0.9498, -0.0602, -0.1829]])
tensor([[-0.8822, -0.3836, -0.4453,  0.4732],
        [-0.2166,  1.7199,  0.8660, -1.1443],
        [-1.3421,  0.9498, -0.0602, -0.1829]])


## Convolution

### Conv2d

In [21]:
import torch
import torch.nn as nn

## Common convolutional layers
conv = nn.Conv2d(3, 5, 3, 2, 1)

print(get_num_parameters(conv))

conv = nn.Conv2d(30, 5, 3, 2, 1)
print(get_num_parameters(conv))

from thop import profile
from thop import clever_format

flops, params = profile(conv, inputs=(torch.randn(1, 30, 128, 128),))
print(flops, params) # 1819066368.0 11689512.0
flops, params = clever_format([flops, params], "%.3f")
print(flops, params)

140
1355
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
5529600.0 0
5.530M 0.000B


0

In [3]:
### 反卷积 https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html
import torch
import torch.nn as nn

## Common convolutional layers
conv = nn.Conv2d(4, 5, 3, 2, 1)
print(conv.weight.shape)
print(conv.bias.shape)
print(conv.bias)
conv.weight.data.normal_()
conv.bias.data.zero_()
print(conv.bias)

weight = getattr(conv, "weight")
print(weight.shape)
print(weight.data.size(1), weight.data[0][0])

## Apply convolution
print("\nApply convolution")
input = torch.randn(2, 3, 10, 10)
output = conv(input)
print(output.shape)

torch.Size([5, 4, 3, 3])
torch.Size([5])
Parameter containing:
tensor([ 0.1460, -0.1008, -0.1073, -0.0464,  0.1341], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)
torch.Size([5, 4, 3, 3])
4 tensor([[ 0.6317,  1.4049, -0.9065],
        [ 0.1092, -1.6640,  1.5237],
        [-0.8378,  0.3228, -0.5971]])

Apply convolution


RuntimeError: Given groups=1, weight of size [5, 4, 3, 3], expected input[2, 3, 10, 10] to have 4 channels, but got 3 channels instead

### Conv3d

In [5]:
import torch
import torch.nn as nn

conv_module = nn.Conv3d(in_channels=3, out_channels=768, 
                        kernel_size = (1, 16, 16), 
                        stride=(1, 16, 16))

input = torch.randn(5, 3, 8, 224, 224)
output = conv_module(input)
print(output.shape)

output = output.flatten(2)
print(output.shape)


torch.Size([5, 768, 8, 14, 14])
torch.Size([5, 768, 1568])


### Conv1x1

In [11]:
from icecream import ic as print

conv1 = nn.Conv2d(1024, 64, 1, stride=1, padding=0)

input = torch.rand(2, 1024, 1, 1)

output = conv1(input)
print(output.shape)

num_param_conv1 = get_num_parameters(conv1)
print(num_param_conv1)

fc = nn.Linear(1024, 64)
output = fc(input.squeeze())
print(output.shape)

num_param_fc = get_num_parameters(fc)
print(num_param_fc)


ic| output.shape: torch.Size([2, 64, 1, 1])
ic| num_param_conv1: 65600
ic| output.shape: torch.Size([2, 64])
ic| num_param_fc: 65600


65600

## Embedding

In [10]:
import torch
import torch.nn as nn
class_emb = nn.Embedding(16, 8)

input = torch.randint(0, 16, (1, 8, 200, 200, 16))
print(input.shape)
# print(input)

output = class_emb(input)
print(output.shape)


torch.Size([1, 8, 200, 200, 16])
torch.Size([1, 8, 200, 200, 16, 8])


In [3]:
import torch
import torch.nn as nn
image_emb = nn.Embedding(1024, 256)
params = get_num_parameters(image_emb)
print(params)

image_emb = nn.Embedding(5, 768)
print(image_emb.weight.shape)

# input = torch.LongTensor(4,)
tok = torch.tensor([0], dtype=torch.long)
input = tok.repeat(4, 10)
print(input.shape)
output = image_emb(input)
print(output.shape, output.min(), output.max())


262144
torch.Size([5, 768])
torch.Size([4, 10])
torch.Size([4, 10, 768]) tensor(-2.6352, grad_fn=<MinBackward1>) tensor(2.5464, grad_fn=<MaxBackward1>)


## Compute the Convolution output tensor size

In [11]:
def Cov3DSize(input, cin, cout, kernel_size, stride, padding):
    conv = nn.Conv3d(cin, cout, kernel_size=kernel_size, stride=stride, padding=padding)
    output = conv(input)
    print(output.shape)
    return output

def MaxPool3D(input, kernel_size, stride):
    pool = nn.MaxPool3d(kernel_size=kernel_size, stride=stride)
    output = pool(input)
    print("MaxPool3D shape: ", output.shape)
    return output

input = torch.rand(20, 3, 5, 224, 224)
input = Cov3DSize(input, 3, 96, kernel_size=(5,7,7), stride=(1,2,2), padding=0)
input = MaxPool3D(input, kernel_size=(1,3,3), stride=(1,2,2))




torch.Size([20, 96, 1, 109, 109])
MaxPool3D shape:  torch.Size([20, 96, 1, 54, 54])


tensor([[[[[ 0.5023,  0.5023,  0.4128,  ...,  0.4558,  0.3107,  0.4717],
           [ 0.5023,  0.5793,  0.3253,  ...,  0.4558,  0.3143,  0.4888],
           [ 0.3287,  0.2374,  0.5073,  ...,  0.3702,  0.3143,  0.4888],
           ...,
           [ 0.3105,  0.3293,  0.4435,  ...,  0.2628,  0.4014,  0.4014],
           [ 0.2706,  0.3995,  0.4435,  ...,  0.3990,  0.2933,  0.1918],
           [ 0.4065,  0.3995,  0.3467,  ...,  0.2890,  0.1323,  0.1790]]],


         [[[ 0.2466,  0.2063,  0.1703,  ...,  0.0763, -0.0086, -0.0442],
           [-0.0941,  0.2566,  0.1294,  ...,  0.0763, -0.1647, -0.1810],
           [ 0.0423,  0.0423,  0.0011,  ...,  0.1201,  0.1201,  0.0577],
           ...,
           [ 0.0726,  0.0833,  0.2228,  ..., -0.0621,  0.2760,  0.0202],
           [ 0.0406,  0.0515,  0.2228,  ..., -0.0695,  0.2760, -0.0345],
           [ 0.0502,  0.0502, -0.0586,  ...,  0.0078, -0.0091,  0.1370]]],


         [[[-0.0618, -0.0442, -0.0197,  ...,  0.1594, -0.0027,  0.0232],
           

## MaxPool2d, MaxPool3d
[https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html)

tensor([[[[ 1.2346e+00,  3.7939e-01, -1.9367e+00,  1.3094e+00,  4.6663e-01],
          [ 3.4819e-01, -5.6895e-01, -1.5108e+00,  7.0780e-01,  9.0777e-01],
          [ 4.6561e-01,  2.1563e+00, -2.3255e+00, -6.6472e-01,  5.5147e-01],
          [ 9.4951e-01, -3.3740e-01, -6.2161e-02,  4.8511e-01, -1.4107e-01],
          [ 6.3537e-01,  1.5464e+00,  2.0419e+00,  2.4523e-01,  2.2240e+00]],

         [[-5.4798e-01,  1.6411e-01, -2.4302e-01, -2.1069e+00, -1.1748e+00],
          [ 5.8614e-01, -1.0792e+00,  8.6184e-02,  2.6984e-02,  3.7680e-01],
          [-4.2325e-02,  5.9603e-01, -5.9892e-01,  6.5933e-01,  9.7178e-01],
          [-1.4920e+00, -2.1150e-01, -2.5007e-01, -2.6350e-01, -7.3031e-01],
          [-8.8017e-01, -1.0805e+00, -8.5367e-01,  2.3745e+00,  1.7426e+00]],

         [[ 3.5111e-01, -1.0492e+00, -6.6652e-01,  1.4015e+00,  2.0608e+00],
          [-1.2575e+00, -4.0794e-01,  2.2955e-02, -1.0286e+00,  6.4215e-01],
          [-8.6350e-01, -2.7992e-01, -2.8991e-01,  9.1334e-01,  3.0354e-

### AdaptiveAvgPool2d

In [2]:
import torch

adp_pool = torch.nn.AdaptiveAvgPool2d((256, 256))
input = torch.randn(1, 3, 512, 512)
output = adp_pool(input)
print(output.shape)

/home/zhanghm/miniconda3/envs/py38-torch100-cu11/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.Size([1, 3, 256, 256])


In [53]:
upsample = nn.Upsample(scale_factor=2, mode='nearest')
print([i for i in upsample.parameters()])

print("The total number of parameters in module is:")
pytorch_total_params = sum(p.numel() for p in upsample.parameters())
print(pytorch_total_params)

[]
The total number of parameters in module is:
0


In [56]:
style = torch.randn(1, 4, 2, 2)
gamma, beta = style.chunk(2, 1)
print(gamma.shape, beta.shape)
print(style)
print(gamma)
print(beta)

torch.Size([1, 2, 2, 2]) torch.Size([1, 2, 2, 2])
tensor([[[[ 0.3909, -0.1451],
          [-1.6407, -1.0667]],

         [[-0.2172,  0.2076],
          [ 1.9867,  0.7596]],

         [[ 1.0905, -0.9003],
          [ 0.4875,  0.6588]],

         [[ 1.1397,  1.1139],
          [ 0.7776,  1.0089]]]])
tensor([[[[ 0.3909, -0.1451],
          [-1.6407, -1.0667]],

         [[-0.2172,  0.2076],
          [ 1.9867,  0.7596]]]])
tensor([[[[ 1.0905, -0.9003],
          [ 0.4875,  0.6588]],

         [[ 1.1397,  1.1139],
          [ 0.7776,  1.0089]]]])


## nn.Upsample class
https://www.cnblogs.com/wanghui-garcia/p/11399053.html
https://github.com/christianversloot/machine-learning-articles/blob/main/how-to-use-upsample-for-upsampling-with-pytorch.md

In [8]:
import torch
import torch.nn as nn
import numpy as np

input_data = np.loadtxt("./data/02933112.23637357c4e5efb653c80c0a3ef7382.xyz").astype(np.float32)
print(input_data.shape)
input_data = torch.from_numpy(input_data).unsqueeze(0)
input_data = input_data.permute(0, 2, 1)
upsample_module = nn.Upsample(scale_factor=4, mode="linear")
output = upsample_module(input_data)
print(output.shape)
output_numpy = output.squeeze().permute(1, 0).numpy()
np.savetxt("./data/upsampled_points_X4.xyz", output_numpy)

(256, 3)
torch.Size([1, 3, 1024])


/home/zhanghm/miniconda3/envs/py38-torch100-cu11/lib/python3.8/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=linear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(


## nn.Softmax

In [11]:
import torch
import torch.nn as nn

m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
print(input)
output = m(input)
print(output)

output = input.softmax(dim=1)
print(output)

output = output.sum(dim=1)
print(output)

tensor([[-0.7364, -0.5942, -0.3573],
        [ 0.6877,  0.4940,  1.5346]])
tensor([[0.2767, 0.3190, 0.4043],
        [0.2406, 0.1982, 0.5612]])
tensor([[0.2767, 0.3190, 0.4043],
        [0.2406, 0.1982, 0.5612]])
tensor([1.0000, 1.0000])
