# Play with different Loss Functions in Pytorch

## Reference Resources
[all-pytorch-loss-function](https://analyticsindiamag.com/all-pytorch-loss-function/)

In [10]:
import torch
import torch.nn as nn
import numpy as np

## KL loss

In [3]:
import torch
import torch.nn.functional as F

pred = torch.randn(4, 200, 200, 16, 18)
target = torch.randn(4, 200, 200, 16, 18)

pred = torch.randn(4, 18)
target = torch.randn(4, 18)
T = 10


kd_loss = F.kl_div(
        F.log_softmax(pred / T, dim=1), target, reduction='none').mean(1) * (
            T * T)
print(kd_loss.shape)

torch.Size([4])


In [8]:
import torch
from mmdet.models.losses import KnowledgeDistillationKLDivLoss

kl_loss = KnowledgeDistillationKLDivLoss()

pred = torch.randn(4, 18)
target = torch.randn(4, 18)
weight = torch.randn(4)
print(weight.shape)
dd = pred.reshape(2, -1)
print(dd.shape)

loss = kl_loss(pred, target, weight)
print(loss)

torch.Size([4])
torch.Size([2, 36])
tensor(-0.0144)


## L1 loss

In [14]:
import torch
import torch.nn.functional as F


### https://pytorch.org/docs/stable/generated/torch.nn.L1Loss.html
def cal_loss(input, target):
    """
    MAE计算细节
    """
    print(target - input)
    print(torch.abs(target - input))
    ### Calculate the absolute
    diff = input - target
    abs_diff = torch.abs(diff)
    mae = torch.mean(abs_diff)
    print(mae)


def calc_loss_with_different_methods(pred, tgt):
    print("calc_loss_with_different_methods")
    ## Method 1
    l1_loss = nn.L1Loss(reduction='none')
    output = l1_loss(pred, tgt)
    print(output, output.shape)
    
    output = torch.mean(output) # the same with nn.L1Loss(reduction='mean')
    print(output)

    ## Method 2
    l1_loss = nn.L1Loss()
    output = l1_loss(pred, tgt)
    print(output)

    ## Method 3
    output = F.l1_loss(pred, tgt)
    print(output)


pred = torch.arange(16).reshape(2, 4, 2).to(torch.float32)
target = torch.arange(16, 0, step=-1).reshape(2, 4, 2).to(torch.float32)

calc_loss_with_different_methods(pred, target)


# mae_loss = nn.L1Loss(reduction='mean')
# input = torch.randn(3, 5)
# target = torch.randn(3, 5)
# target = torch.tensor([[1,2,3,4,5],[1,2,3,4,5], [1,2,3,4,5.0]])
# target = torch.tensor([[1,2,3,4,5.0]])

# print(input, target)
# cal_loss(input, target)

# output = mae_loss(input, target)
# print(output, output.shape)

# target = torch.tensor([[1,2,3,4,5],[1,2,3,4,5], [1,2,3,4,5.0]])
# output = mae_loss(input, target)
# print(output, output.shape)




calc_loss_with_different_methods
tensor([[[16., 14.],
         [12., 10.],
         [ 8.,  6.],
         [ 4.,  2.]],

        [[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.],
         [12., 14.]]]) torch.Size([2, 4, 2])
tensor(8.)
tensor(8.)
tensor(8.)


In [30]:
import torch.nn.functional as F


def pixel_wise_loss(pred, target, mask=None, weight=1.0):
    l1_dist = F.l1_loss(pred, target, reduction="none")

    if mask is None:
        return torch.mean(l1_dist)
    
    loss1 = weight * l1_dist * mask
    loss2 = l1_dist * (1 - mask)
    
    loss = torch.mean(loss1 + loss2)
    return loss

pred = torch.arange(0, 9).reshape(3, 3).to(torch.float32)

# target = torch.arange(9, 0, -1).reshape(3, 3).to(torch.float32)
target = torch.arange(1, 10).reshape(3, 3).to(torch.float32)
# target[0, 0] += 2

target[2, 2] += 2


print(pred)
print(target)

mask = torch.zeros_like(target)
mask[:2, :2] = 1.
print(mask)

loss = pixel_wise_loss(pred, target)
# loss = pixel_wise_loss(pred, target, mask=mask, weight=2.0)

print(loss)




tensor(1.2222)
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8., 11.]])
tensor([[1., 1., 0.],
        [1., 1., 0.],
        [0., 0., 0.]])
tensor(1.2222)


## Smooth L1Loss

## MSE Loss

In [6]:
import torch

mse_criterion = torch.nn.MSELoss(reduction='sum')

pred = torch.tensor([[0, 2, 2, 4]], dtype=torch.float32)
target = torch.tensor([[2, 3, 4, 5]], dtype=torch.float32)

mse_loss = mse_criterion(pred, target)
print(mse_loss)


tensor(10.)


In [ ]:

### Pytorch实现
input = torch.randn(3, 4, requires_grad=True)
target = torch.randn(3, 4)
mse_loss = nn.MSELoss()
output = mse_loss(input, target)
print(output)
output.backward()
print('input -: ', input)
print('target -: ', target)
print('output -: ', output)

pred = torch.arange(0, 9).reshape(3, 3).to(torch.float32) / 9.0
# pred[0, 0] = 0.5
# pred[2, 2] = 0.1




target = torch.arange(9, 0, -1).reshape(3, 3).to(torch.float32) / 9.0
print(target)

pred[2] = target[2]
# pred[2, :2] = target[2, :2]
print(pred)

class WeightedLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.mse_loss = nn.MSELoss()
    
    def forward(self, pred, target):
        weight = -torch.log(1 - target + 1e-5)
        weighted_diff = torch.multiply((pred - target), weight)
        
        return torch.sum(torch.pow(weighted_diff, 2))

mse_loss = WeightedLoss()
output = mse_loss(pred, target)
print(output)

## Binary Cross Entropy(nn.BCELoss)
[https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html)

[https://gombru.github.io/2018/05/23/cross_entropy_loss/](https://gombru.github.io/2018/05/23/cross_entropy_loss/)

In [56]:
### Python实现
y_pred = np.array([0.1580, 0.4137, 0.2285])
y_true = np.array([0.0, 1.0, 0.0]) #2 labels: (0,1)
def BCE(y_pred, y_true):
    total_bce_loss = np.sum(-y_true * np.log(y_pred) - (1 - y_true) * np.log(1 - y_pred))
    # Getting the mean BCE loss
    num_of_samples = y_pred.shape[0]
    mean_bce_loss = total_bce_loss / num_of_samples
    return mean_bce_loss
bce_value = BCE(y_pred, y_true)
print ("BCE error is: " + str(bce_value))

BCE error is: 0.43800269247783435


In [58]:
## Using Pytorch implementation
bce_loss = torch.nn.BCELoss()
sigmoid = torch.nn.Sigmoid() # Ensuring inputs are between 0 and 1
input = torch.tensor(y_pred)
target = torch.tensor(y_true)
print(input.shape, target.shape)
output = bce_loss(input, target)
print(output)

torch.Size([3]) torch.Size([3])
tensor(0.4380, dtype=torch.float64)


## BCEWithLogitsLoss(nn.BCEWithLogitsLoss)

In [2]:
import torch
import torch.nn as nn

def example1():
    model = nn.Linear(10, 1)
    criterion = nn.BCEWithLogitsLoss()
    criterion = nn.BCELoss()

    x = torch.randn(16, 10)
    y = torch.empty(16).random_(2)  # (16, )
    print(y, y.shape)

    out = model(x)  # (16, 1)
    out = out.squeeze(dim=-1)  # (16, )

    print(out)

    loss = criterion(y, y)
    print(loss)

def example2():
    torch.manual_seed(100)
    
    criterion = nn.BCEWithLogitsLoss()
    criterion2 = nn.BCELoss()

    pred = torch.rand(16,1) * 100
    print(pred)

    sigmoid = torch.nn.Sigmoid()
    print(sigmoid(pred))

    target = torch.zeros_like(pred)
    print(target.shape)

    loss = criterion(target, pred)
    print(loss)

    print(criterion2(target, sigmoid(pred)))

example2()

tensor([[11.1664],
        [81.5843],
        [26.2562],
        [48.3878],
        [67.6504],
        [75.3911],
        [26.2691],
        [ 4.2840],
        [20.8029],
        [11.8037],
        [12.1695],
        [73.5599],
        [71.1765],
        [78.7581],
        [41.8305],
        [90.1415]])
tensor([[1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [0.9864],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000],
        [1.0000]])
torch.Size([16, 1])
tensor(0.6931)
tensor(27.6075)


## CrossEntroypLoss

In [ ]:
from mmdet.models.losses import CrossEntropyLoss

## CosineEmbeddingLoss
https://pytorch.org/docs/stable/generated/torch.nn.CosineEmbeddingLoss.html

In [14]:
criterion = torch.nn.CosineEmbeddingLoss()

v1 = torch.randn((16, 64))
v2 = torch.randn((16, 64))
v2 = v1 * 0.6

target = torch.ones((v1.shape[0]))
print(target.shape)

loss = criterion(v1, v2, target)
print(loss)

torch.Size([16])
tensor(-1.1176e-08)


## Perceptual Loss

In [6]:
import lpips
loss_fn_alex = lpips.LPIPS(net='alex') # best forward scores
loss_fn_vgg = lpips.LPIPS(net='vgg') # closer to "traditional" perceptual loss, when used for optimization

import torch
img0 = torch.zeros(1,3,64,64) # image should be RGB, IMPORTANT: normalized to [-1,1]
img1 = torch.ones(1,3,64,64)
d = torch.mean(loss_fn_vgg(img0, img1))
print(d.shape)
print(d)

Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /home/haimingzhang/miniconda3/envs/GAN/lib/python3.6/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /home/haimingzhang/miniconda3/envs/GAN/lib/python3.6/site-packages/lpips/weights/v0.1/vgg.pth
torch.Size([])
tensor(0.4945, grad_fn=<MeanBackward0>)


## Total Variation Loss

In [10]:
import torch
import cv2

def total_variation_loss(img):
    bs_img, c_img, h_img, w_img = img.size()
    tv_h = torch.pow(img[:,:,1:,:]-img[:,:,:-1,:], 2).sum()
    tv_w = torch.pow(img[:,:,:,1:]-img[:,:,:,:-1], 2).sum()
    return (tv_h + tv_w) / (bs_img*c_img*h_img*w_img)

img = cv2.imread("/home/zhanghm/Research/V100/programming-learning-examples/Python_learning/data/obama.jpg")
img_pred = torch.rand(1,3,64,64)
img_pred = torch.FloatTensor(img)[None] / 255
img_pred = img_pred.permute(0,3,1,2)

loss = total_variation_loss(img_pred)
print(loss)

tensor(0.0004)
