# Some basic operatioins by using Pytorch

In [2]:
import torch
import torch as nn
import numpy as np

## Create torch tensors

In [12]:
### Basic creator
x = torch.tensor([1, 2, 3])
print(x.shape)

### Random creator
print(torch.rand(3, 5)) # 生成0-1的随机数
print(torch.randn(3, 5)) # 生成标准正态分布的随机数

### From numpy

torch.Size([3])
tensor([[0.7925, 0.2678, 0.8116, 0.3457, 0.3045],
        [0.7637, 0.0065, 0.0652, 0.5085, 0.8011],
        [0.7650, 0.4977, 0.5035, 0.5900, 0.6967]])
tensor([[ 2.5541, -0.1705, -0.7015,  0.5510, -0.0155],
        [ 0.4679, -0.2098,  0.6918,  2.0037, -0.1771],
        [-1.1810,  1.9495, -0.7814, -0.5482, -0.7604]])


In [19]:
### Create meshgrid
# Ray helpers
def get_rays(H, W, K, c2w):
    i, j = torch.meshgrid(torch.linspace(0, W-1, W), torch.linspace(0, H-1, H))  # pytorch's meshgrid has indexing='ij'
    i = i.t()
    j = j.t()
    dirs = torch.stack([(i-K[0][2])/K[0][0], -(j-K[1][2])/K[1][1], -torch.ones_like(i)], -1)

    # Rotate ray directions from camera frame to the world frame
    rays_d = torch.sum(dirs[..., np.newaxis, :] * c2w[:3,:3], -1)  # dot product, equals to: [c2w.dot(dir) for dir in dirs]
    # Translate camera frame's origin to the world frame. It is the origin of all rays.
    rays_o = c2w[:3,-1].expand(rays_d.shape)
    return rays_o, rays_d

H, W, focal = 400, 400, 555.55
K = np.array([
            [focal, 0, 0.5*W],
            [0, focal, 0.5*H],
            [0, 0, 1]
        ])
c2w = np.random.rand(3, 4)
get_rays(H, W, K, c2w)

torch.Size([400, 400, 3])
torch.Size([400, 3])


## Dimensions operation

In [27]:
### squeeze和unsqueeze的用法 https://pytorch.org/docs/stable/generated/torch.unsqueeze.html
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))

### Expand函数不复制张量元素
x = torch.tensor([1, 2, 3])
x = x.expand(2, 3)
print(x, x.shape)

### Repeat函数复制张量元素
y = torch.tensor([1, 2, 3])
y = y.repeat(2, 3)
print(y, y.shape)

### 使用Repeat可以为张量增加维度
y = torch.tensor([1, 2, 3])
print(y.shape)
y = y.unsqueeze(0).repeat(5, 1, 1)
print(y.shape)
print(y)

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3],
        [1, 2, 3]]) torch.Size([2, 3])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]]) torch.Size([2, 9])
torch.Size([3])
torch.Size([5, 1, 3])
tensor([[[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]]])


## Misc math operations

## Conca, Stack operations

### 连接堆叠操作
torch
torch.cat()

In [33]:
a=torch.tensor([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
print("a的shape：",a.shape)
#在第0维上进行split
b=torch.split(a, 1)
print("b:", b, len(b))
#在第1维上进行split
c=torch.split(a,[1,1],1)
print("c:",c)

a的shape： torch.Size([2, 2, 3])
b: (tensor([[[1, 2, 3],
         [4, 5, 6]]]), tensor([[[ 7,  8,  9],
         [10, 11, 12]]])) 2
c: (tensor([[[1, 2, 3]],

        [[7, 8, 9]]]), tensor([[[ 4,  5,  6]],

        [[10, 11, 12]]]))
