## Learn how to use the einops library

In [1]:
import torch
from einops import repeat, rearrange

### Use repeat function

In [2]:
input = torch.randn(2, 3)
print(input, input.shape)

output = repeat(input, 'h w -> h w c', c=3)
print(output, output.shape)

tensor([[-0.0445,  1.2679,  0.0591],
        [ 0.8185, -0.0033, -1.2111]]) torch.Size([2, 3])
tensor([[[-0.0445, -0.0445, -0.0445],
         [ 1.2679,  1.2679,  1.2679],
         [ 0.0591,  0.0591,  0.0591]],

        [[ 0.8185,  0.8185,  0.8185],
         [-0.0033, -0.0033, -0.0033],
         [-1.2111, -1.2111, -1.2111]]]) torch.Size([2, 3, 3])


In [4]:
class_label = 9

batch_size = 2
input = torch.tensor([class_label])

c_indices = repeat(input, '1 -> b 1', b=batch_size)  # class token
print(c_indices.shape, c_indices.dtype)
print(c_indices)


torch.Size([2, 1]) torch.int64
tensor([[9],
        [9]])
