## Learn how to use the einops library

In [1]:
import torch
from einops import repeat, rearrange

## Use repeat function

In [2]:
input = torch.randn(2, 3)
print(input, input.shape)

output = repeat(input, 'h w -> h w c', c=3)
print(output, output.shape)

tensor([[-0.0445,  1.2679,  0.0591],
        [ 0.8185, -0.0033, -1.2111]]) torch.Size([2, 3])
tensor([[[-0.0445, -0.0445, -0.0445],
         [ 1.2679,  1.2679,  1.2679],
         [ 0.0591,  0.0591,  0.0591]],

        [[ 0.8185,  0.8185,  0.8185],
         [-0.0033, -0.0033, -0.0033],
         [-1.2111, -1.2111, -1.2111]]]) torch.Size([2, 3, 3])


### repeat specific axis

In [10]:
pc = torch.randn(1, 2, 3)
print(pc)

### The below three methods are the same
pc = repeat(pc, 'b n c -> (repeat b) n c', repeat=2).contiguous()
# pc = repeat(pc, 'b n c -> (b 2) n c').contiguous()
# pc = repeat(pc, 'b n c -> (2 b) n c').contiguous()
print(pc, pc.shape)

tensor([[[-1.5255, -2.6183,  0.1318],
         [ 0.5025, -0.5046,  0.7587]]])
tensor([[[-1.5255, -2.6183,  0.1318],
         [ 0.5025, -0.5046,  0.7587]],

        [[-1.5255, -2.6183,  0.1318],
         [ 0.5025, -0.5046,  0.7587]]]) torch.Size([2, 2, 3])


In [4]:
class_label = 9

batch_size = 2
input = torch.tensor([class_label])

c_indices = repeat(input, '1 -> b 1', b=batch_size)  # class token
print(c_indices.shape, c_indices.dtype)
print(c_indices)


torch.Size([2, 1]) torch.int64
tensor([[9],
        [9]])


## rearange operation

In [10]:
import torch

from einops import rearrange, repeat

data = torch.arange(24).reshape(2, 3, 4)
print(data)

# data = rearrange(data, 'b n c -> (b n) c')
# data = rearrange(data, 'b n c -> b (n c)')
data = rearrange(data, 'b n c -> (n c) b')
# data = rearrange(data, 'b n c -> b (c n)')
print(data, data.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]) torch.Size([12, 2])


In [3]:
input = torch.rand(5, 256, 12)
print(input.shape)

output = rearrange(input, 'b n (r c) -> b n r c', c=3)
print(output.shape)


torch.Size([5, 256, 12])
torch.Size([5, 256, 4, 3])


In [4]:
import torch
from einops import rearrange

input = torch.randn(2, 5, 4, 3)

input = rearrange(input, 'b g m c -> (b g) m c')
print(input.shape)

torch.Size([10, 4, 3])


In [5]:
import torch
from einops import rearrange

input = torch.randn(1, 262144, 3)

output = rearrange(input, 'x (b n) c -> (x b) n c', b=128)
print(output.shape)

torch.Size([128, 2048, 3])
