# Play with different Loss Functions in Pytorch

## Reference Resources
[all-pytorch-loss-function](https://analyticsindiamag.com/all-pytorch-loss-function/)

In [29]:
import torch
import torch.nn as nn
import numpy as np

## L1 loss

In [66]:
### https://pytorch.org/docs/stable/generated/torch.nn.L1Loss.html
def cal_loss(input, target):
    """
    MAE计算细节
    """
    print(target - input)
    print(torch.abs(target - input))
    ### Calculate the absolute
    diff = input - target
    abs_diff = torch.abs(diff)
    mae = torch.mean(abs_diff)
    print(mae)

mae_loss = nn.L1Loss(reduction='mean')
input = torch.randn(3, 5)
target = torch.randn(3, 5)
target = torch.tensor([[1,2,3,4,5],[1,2,3,4,5], [1,2,3,4,5.0]])
target = torch.tensor([[1,2,3,4,5.0]])

print(input, target)
cal_loss(input, target)

output = mae_loss(input, target)
print(output, output.shape)

target = torch.tensor([[1,2,3,4,5],[1,2,3,4,5], [1,2,3,4,5.0]])
output = mae_loss(input, target)
print(output, output.shape)




tensor([[ 0.0410, -2.2190, -1.3664, -0.8746, -0.5793],
        [ 0.8840,  0.4308, -0.6027,  1.0672, -0.2522],
        [ 0.5394,  0.2882, -0.0208,  0.7330,  1.1930]]) tensor([[1., 2., 3., 4., 5.]])
tensor([[0.9590, 4.2190, 4.3664, 4.8746, 5.5793],
        [0.1160, 1.5692, 3.6027, 2.9328, 5.2522],
        [0.4606, 1.7118, 3.0208, 3.2670, 3.8070]])
tensor([[0.9590, 4.2190, 4.3664, 4.8746, 5.5793],
        [0.1160, 1.5692, 3.6027, 2.9328, 5.2522],
        [0.4606, 1.7118, 3.0208, 3.2670, 3.8070]])
tensor(3.0492)
tensor(3.0492) torch.Size([])
tensor(3.0492) torch.Size([])


## Smooth L1Loss

## Mean Squared Error (nn.L2Loss)

In [61]:
### Pytorch实现
input = torch.randn(3, 4, requires_grad=True)
target = torch.randn(3, 4)
mse_loss = nn.MSELoss()
output = mse_loss(input, target)
print(output)
output.backward()
print('input -: ', input)
print('target -: ', target)
print('output -: ', output)

tensor(3.4604, grad_fn=<MseLossBackward>)
input -:  tensor([[ 0.4401, -0.1579, -1.3036,  0.9847],
        [ 1.4939,  1.3887, -0.2879, -0.6568],
        [ 0.7111, -0.2692,  0.0091, -0.8270]], requires_grad=True)
target -:  tensor([[-0.1593,  0.2934,  2.1880, -1.8528],
        [ 0.3778, -1.4392,  1.9269,  0.5127],
        [-0.1783,  1.4818,  1.1663, -0.9139]])
output -:  tensor(3.4604, grad_fn=<MseLossBackward>)


## Binary Cross Entropy(nn.BCELoss)
[https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html)

[https://gombru.github.io/2018/05/23/cross_entropy_loss/](https://gombru.github.io/2018/05/23/cross_entropy_loss/)

In [56]:
### Python实现
y_pred = np.array([0.1580, 0.4137, 0.2285])
y_true = np.array([0.0, 1.0, 0.0]) #2 labels: (0,1)
def BCE(y_pred, y_true):
    total_bce_loss = np.sum(-y_true * np.log(y_pred) - (1 - y_true) * np.log(1 - y_pred))
    # Getting the mean BCE loss
    num_of_samples = y_pred.shape[0]
    mean_bce_loss = total_bce_loss / num_of_samples
    return mean_bce_loss
bce_value = BCE(y_pred, y_true)
print ("BCE error is: " + str(bce_value))

BCE error is: 0.43800269247783435


In [58]:
## Using Pytorch implementation
bce_loss = torch.nn.BCELoss()
sigmoid = torch.nn.Sigmoid() # Ensuring inputs are between 0 and 1
input = torch.tensor(y_pred)
target = torch.tensor(y_true)
print(input.shape, target.shape)
output = bce_loss(input, target)
print(output)

torch.Size([3]) torch.Size([3])
tensor(0.4380, dtype=torch.float64)


## BCEWithLogitsLoss(nn.BCEWithLogitsLoss)

## CrossEntroypLoss