# Play with different Loss Functions in Pytorch

## Reference Resources
[all-pytorch-loss-function](https://analyticsindiamag.com/all-pytorch-loss-function/)

In [29]:
import torch
import torch.nn as nn
import numpy as np

## L1 loss

In [23]:
### https://pytorch.org/docs/stable/generated/torch.nn.L1Loss.html
def cal_loss(input, target):
    """
    MAE计算细节
    """
    print(target - input)
    print(torch.abs(target - input))
    ### Calculate the absolute
    diff = input - target
    abs_diff = torch.abs(diff)
    mae = torch.mean(abs_diff)
    print(mae)

mae_loss = nn.L1Loss(reduction='mean')
input = torch.randn(3, 5)
target = torch.randn(3, 5)

print(input, target)
cal_loss(input, target)

output = mae_loss(input, target)
print(output, output.shape)



tensor([[-1.3854,  1.1842,  1.0388, -0.4160, -0.8009],
        [-0.2005, -1.3640,  0.9319,  1.0852,  0.7869],
        [ 0.0369,  0.5503, -1.8960,  0.6278,  0.2536]]) tensor([[ 1.9095,  0.5111,  0.8696, -0.7395,  1.6061],
        [ 0.4301,  2.0581,  1.1303,  0.2786,  0.4720],
        [ 1.7267, -1.7716, -0.0319,  0.4141, -0.3385]])
tensor([[ 3.2949, -0.6731, -0.1692, -0.3235,  2.4069],
        [ 0.6307,  3.4221,  0.1984, -0.8066, -0.3149],
        [ 1.6899, -2.3219,  1.8641, -0.2138, -0.5920]])
tensor([[3.2949, 0.6731, 0.1692, 0.3235, 2.4069],
        [0.6307, 3.4221, 0.1984, 0.8066, 0.3149],
        [1.6899, 2.3219, 1.8641, 0.2138, 0.5920]])
tensor(1.2615)
tensor(1.2615)
tensor(1.2615) torch.Size([])


## Mean Squared Error (nn.L2Loss)

In [27]:
input = torch.randn(3, 4, requires_grad=True)
target = torch.randn(3, 4)
mse_loss = nn.MSELoss()
output = mse_loss(input, target)
print(output)
output.backward()
print('input -: ', input)
print('target -: ', target)
print('output -: ', output)

tensor(1.8406, grad_fn=<MseLossBackward>)
input -:  tensor([[ 1.8761,  0.4816,  1.1025,  0.8694],
        [-0.7637, -0.3180, -0.0189, -0.5305],
        [-1.8623,  0.8848,  0.2659,  0.5529]], requires_grad=True)
target -:  tensor([[ 1.1865,  0.4024,  0.7173, -0.5816],
        [ 0.0767, -0.8407,  0.3574,  1.6857],
        [ 0.2532, -1.0210, -1.7251, -0.5643]])
output -:  tensor(1.8406, grad_fn=<MseLossBackward>)


## Binary Cross Entropy(nn.BCELoss)
[https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html)

In [56]:
### Python实现
y_pred = np.array([0.1580, 0.4137, 0.2285])
y_true = np.array([0.0, 1.0, 0.0]) #2 labels: (0,1)
def BCE(y_pred, y_true):
    total_bce_loss = np.sum(-y_true * np.log(y_pred) - (1 - y_true) * np.log(1 - y_pred))
    # Getting the mean BCE loss
    num_of_samples = y_pred.shape[0]
    mean_bce_loss = total_bce_loss / num_of_samples
    return mean_bce_loss
bce_value = BCE(y_pred, y_true)
print ("BCE error is: " + str(bce_value))

BCE error is: 0.43800269247783435


In [58]:
## Using Pytorch implementation
bce_loss = torch.nn.BCELoss()
sigmoid = torch.nn.Sigmoid() # Ensuring inputs are between 0 and 1
input = torch.tensor(y_pred)
target = torch.tensor(y_true)
print(input.shape, target.shape)
output = bce_loss(input, target)
print(output)

torch.Size([3]) torch.Size([3])
tensor(0.4380, dtype=torch.float64)
