In [2]:
import torch

In [2]:
import torch
lengths = torch.tensor([14, 13, 45])
print(lengths.dtype, lengths.shape)

lengths = (lengths * 3 / 4).to(lengths.dtype)
print(lengths)
print(lengths.dtype, lengths.shape)

## log the tensor
target = torch.randn(5)
target_log = torch.log(target)
print(target, target_log)


target = torch.arange(9, 0, -1).reshape(3, 3).to(torch.float32) / 9.0
target_log = torch.log(1 - target + 1e-4)
print(target)
print(target_log)

## Member math functions
tensor_data = torch.rand((2, 3))
print(tensor_data)

tensor_data = tensor_data.add(1)
print(tensor_data)

torch.int64 torch.Size([3])
tensor([10,  9, 33])
torch.int64 torch.Size([3])
tensor([-0.0458,  0.6097, -0.3880, -0.0786,  0.9249]) tensor([    nan, -0.4948,     nan,     nan, -0.0781])
tensor([[1.0000, 0.8889, 0.7778],
        [0.6667, 0.5556, 0.4444],
        [0.3333, 0.2222, 0.1111]])
tensor([[-9.2103, -2.1963, -1.5036],
        [-1.0983, -0.8107, -0.5876],
        [-0.4053, -0.2512, -0.1177]])
tensor([[0.5979, 0.7400, 0.2809],
        [0.5995, 0.2080, 0.2111]])
tensor([[1.5979, 1.7400, 1.2809],
        [1.5995, 1.2080, 1.2111]])


## * and torch.mul operation
`*` and torch.mul both are element-wise multiplication

In [20]:
pred = torch.arange(0, 9).reshape(3, 3).type(torch.float)
print(pred, pred.dtype, pred.shape)

target = torch.arange(1, 10).reshape(3, 3).type(torch.float)[..., None]
print(target, target.dtype, target.shape)

output = pred * target
print(output, output.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) torch.float32 torch.Size([3, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]) torch.float32 torch.Size([3, 3, 1])
tensor([[[ 0.,  1.,  2.],
         [ 6.,  8., 10.],
         [18., 21., 24.]],

        [[ 0.,  4.,  8.],
         [15., 20., 25.],
         [36., 42., 48.]],

        [[ 0.,  7., 14.],
         [24., 32., 40.],
         [54., 63., 72.]]]) torch.Size([3, 3, 3])


## mm() function
torch.mm is the dot product or matrix multiplication operations

In [10]:
feat_2d = torch.randn((2, 3))
feat_3d = torch.randn((2, 3))

print(feat_2d.shape)

cos_scores = feat_2d.mm(feat_3d.t())
print(cos_scores)

print(cos_scores.diag())

diagonal = cos_scores.diag().view(feat_2d.size(0), 1)
print(diagonal)

d1 = diagonal.expand_as(cos_scores)
print(d1)

I = torch.eye(cos_scores.size(0))
print(I)


torch.Size([2, 3])
tensor([[-0.8462, -1.7038],
        [ 0.8599,  2.6345]])
tensor([-0.8462,  2.6345])
tensor([[-0.8462],
        [ 2.6345]])
tensor([[-0.8462, -0.8462],
        [ 2.6345,  2.6345]])
tensor([[1., 0.],
        [0., 1.]])


## Broadcasting +-

In [8]:
import numpy as np

subject_idx = np.array([0, 1, 3, 2])[:, None]
print(subject_idx.shape)

seq_len = 3
subject_idx = subject_idx.repeat(seq_len, axis=-1)
print(subject_idx, subject_idx.shape)


subject_idx = torch.tensor([0, 1, 3, 2])[:, None]
print(subject_idx.shape)

# subject_idx.repeat(seq_len, axis=-1)
# one_hot_speaker_vector = 

(4, 1)
[[0 0 0]
 [1 1 1]
 [3 3 3]
 [2 2 2]] (4, 3)
torch.Size([4, 1])


In [17]:
index = 0

subject_idx_one_hot = torch.zeros((1, 8), dtype=torch.float32)
subject_idx_one_hot[:, index] = 1

print(subject_idx_one_hot, subject_idx_one_hot.shape)

subject_idx_one_hot = subject_idx_one_hot.repeat((2, 3, 1))
print(subject_idx_one_hot, subject_idx_one_hot.shape)

tensor([[1., 0., 0., 0., 0., 0., 0., 0.]]) torch.Size([1, 8])
tensor([[[1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.]]]) torch.Size([2, 3, 8])


## Masked filled

In [ ]:
import cv2

src_img = "/home/haimingzhang/Research/Face/FaceFormer/FaceFormer/data/id00002/obama_weekly_023/face_image/000000.jpg"
mask_img = "/home/haimingzhang/Research/Face/FaceFormer/FaceFormer/data/id00002/obama_weekly_023/mouth_mask/000000.png"

src_img = cv2.resize(cv2.imread(src_img, cv2.IMREAD_UNCHANGED), (192, 192))
