In [1]:
import torch
from einops import rearrange

## Multiplication

In [6]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(a.shape)
b = torch.tensor([[1, 2, 3]])
b = torch.tensor([[1], [2]])
print(b.shape)

c = a * b
print(c, c.shape)

torch.Size([2, 3])
torch.Size([2, 1])
tensor([[ 1,  2,  3],
        [ 8, 10, 12]]) torch.Size([2, 3])


In [5]:
import torch

a = torch.arange(9).reshape(3, 3)
b = torch.arange(3).reshape(3, 1)
print(a)
print(b)
c = a * b
print(c, c.shape)
c = torch.sum(c, dim=-2)
print(c)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0],
        [1],
        [2]])
tensor([[ 0,  0,  0],
        [ 3,  4,  5],
        [12, 14, 16]]) torch.Size([3, 3])
tensor([15, 18, 21])


## Basic math operations

In [8]:
z_flattened = torch.randn(512, 1)
z = torch.randn(1024)
print(z_flattened.shape, z.shape)

z_sum = z_flattened + z
print(z_sum.shape)

torch.Size([512, 1]) torch.Size([1, 1024])
torch.Size([512, 1024])


In [12]:
z_flattened = torch.randn(512, 256)
embedding_weight = torch.randn(1024, 256)

zd =  torch.sum(embedding_weight**2, dim=1)
print(zd.shape)
d = torch.sum(z_flattened ** 2, dim=1, keepdim=True) + \
              torch.sum(embedding_weight**2, dim=1) - 2 * \
              torch.einsum('bd,dn->bn', z_flattened, rearrange(embedding_weight, 'n d -> d n'))
print(d.shape)

min_encoding_indices = torch.argmin(d, dim=1)
print(min_encoding_indices.shape, min_encoding_indices.dtype)

torch.Size([1024])
torch.Size([512, 1024])
torch.Size([512]) torch.int64


In [2]:
import torch
lengths = torch.tensor([14, 13, 45])
print(lengths.dtype, lengths.shape)

lengths = (lengths * 3 / 4).to(lengths.dtype)
print(lengths)
print(lengths.dtype, lengths.shape)

## log the tensor
target = torch.randn(5)
target_log = torch.log(target)
print(target, target_log)


target = torch.arange(9, 0, -1).reshape(3, 3).to(torch.float32) / 9.0
target_log = torch.log(1 - target + 1e-4)
print(target)
print(target_log)

## Member math functions
tensor_data = torch.rand((2, 3))
print(tensor_data)

tensor_data = tensor_data.add(1)
print(tensor_data)

torch.int64 torch.Size([3])
tensor([10,  9, 33])
torch.int64 torch.Size([3])
tensor([-0.0458,  0.6097, -0.3880, -0.0786,  0.9249]) tensor([    nan, -0.4948,     nan,     nan, -0.0781])
tensor([[1.0000, 0.8889, 0.7778],
        [0.6667, 0.5556, 0.4444],
        [0.3333, 0.2222, 0.1111]])
tensor([[-9.2103, -2.1963, -1.5036],
        [-1.0983, -0.8107, -0.5876],
        [-0.4053, -0.2512, -0.1177]])
tensor([[0.5979, 0.7400, 0.2809],
        [0.5995, 0.2080, 0.2111]])
tensor([[1.5979, 1.7400, 1.2809],
        [1.5995, 1.2080, 1.2111]])


## Mean function

In [2]:
import torch

input = torch.randn(10, 256, 16, 16)
print(input.shape)

mean = torch.mean(input)
print(mean.shape)

torch.Size([10, 256, 16, 16])
torch.Size([])


## Sum function

In [4]:
input = torch.arange(0, 6).view(3,2) % 3
print(input, input.shape, input.dtype)

output = input.sum(0)
print(output, output.shape)

tensor([[0, 1],
        [2, 0],
        [1, 2]]) torch.Size([3, 2]) torch.int64
tensor([3, 3]) torch.Size([2])


## sigmoid function

In [6]:
import torch

input = torch.Tensor([0.0, 1.0, 2.0, 3.0, 4.0])
sigmoid_output = torch.sigmoid(input)
print(sigmoid_output)

tensor([0.5000, 0.7311, 0.8808, 0.9526, 0.9820])


## clip function

In [3]:
deltas = torch.randn((2, 3))
print(deltas)

delats = torch.clip(deltas, 0)
print(delats)

tensor([[ 1.1636,  0.0972, -2.4962],
        [-1.0498,  1.1946, -1.3589]])
tensor([[1.1636, 0.0972, 0.0000],
        [0.0000, 1.1946, 0.0000]])


## Get indices with a condition


In [11]:
data = torch.tensor([[-1, -1, -1], [20, 20, 30], [-1, -1, -1], [-1, -1, -1]])
print(data)

indices = data[:, 0] == -1
print(indices)

value = torch.ones_like(data[0:1, :]) * 10
print(value.shape)

data[indices] = value
print(data)

tensor([[-1, -1, -1],
        [20, 20, 30],
        [-1, -1, -1],
        [-1, -1, -1]])
tensor([ True, False,  True,  True])
torch.Size([1, 3])
tensor([[10, 10, 10],
        [20, 20, 30],
        [10, 10, 10],
        [10, 10, 10]])


## Min and Max

In [14]:
data = torch.randn(3, 2)
print(data)
min_data = data.min(-1)[0]
print(min_data.shape, min_data)

tensor([[ 1.9761, -0.1429],
        [ 1.5052, -0.7960],
        [-0.6867, -0.7477]])
torch.Size([3]) tensor([-0.1429, -0.7960, -0.7477])


## torch.enisum

In [8]:
import torch
import numpy as np

id_base = np.ones((5, 3)).astype(np.float32)
id_coeff = np.random.randn(1, 3).astype(np.float32)

print(id_coeff)

id_part = torch.einsum('ij,aj->ai', torch.from_numpy(id_base), torch.from_numpy(id_coeff))
print(id_part.shape)
print(id_part)

dd = id_coeff @ id_base.T
print(dd)

[[-1.7518793 -0.7754192  0.0082383]]
torch.Size([1, 5])
tensor([[-2.5191, -2.5191, -2.5191, -2.5191, -2.5191]])
[[-2.5190601 -2.5190601 -2.5190601 -2.5190601 -2.5190601]]


In [5]:
import torch
exp_base = torch.randn((1, 6, 3))
pred_exp = torch.randn((2, 2, 3))
print(exp_base)
print(pred_exp)

vertex_out = torch.einsum('ijk,iak->iaj', exp_base, pred_exp)
print(vertex_out.shape)
print(vertex_out)

tensor([[[-1.9341, -0.7535, -0.6572],
         [ 1.2373,  0.0140, -0.1188],
         [ 1.9827,  0.5932, -0.0518],
         [ 0.3313, -0.6091,  0.3620],
         [-0.5179,  0.3783,  0.6571],
         [-0.8270,  1.2038,  0.2044]]])
tensor([[[-0.2444,  0.0737, -0.4545],
         [-0.2458, -0.9911, -0.1228]],

        [[ 0.4285, -0.1567, -1.0661],
         [-0.5874,  0.6451, -2.4545]]])
torch.Size([2, 2, 6])
tensor([[[ 0.7158, -0.2473, -0.4173, -0.2904, -0.1442,  0.1979],
         [ 1.3028, -0.3034, -1.0689,  0.4778, -0.3283, -1.0149]],

        [[-0.0100,  0.6546,  0.8118, -0.1485, -0.9817, -0.7610],
         [ 2.2629, -0.4260, -0.6548, -1.4759, -1.0646,  0.7605]]])


## * and torch.mul operation
`*` and torch.mul both are element-wise multiplication

In [20]:
pred = torch.arange(0, 9).reshape(3, 3).type(torch.float)
print(pred, pred.dtype, pred.shape)

target = torch.arange(1, 10).reshape(3, 3).type(torch.float)[..., None]
print(target, target.dtype, target.shape)

output = pred * target
print(output, output.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) torch.float32 torch.Size([3, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]) torch.float32 torch.Size([3, 3, 1])
tensor([[[ 0.,  1.,  2.],
         [ 6.,  8., 10.],
         [18., 21., 24.]],

        [[ 0.,  4.,  8.],
         [15., 20., 25.],
         [36., 42., 48.]],

        [[ 0.,  7., 14.],
         [24., 32., 40.],
         [54., 63., 72.]]]) torch.Size([3, 3, 3])


## mm() function
torch.mm is the dot product or matrix multiplication operations

In [10]:
feat_2d = torch.randn((2, 3))
feat_3d = torch.randn((2, 3))

print(feat_2d.shape)

cos_scores = feat_2d.mm(feat_3d.t())
print(cos_scores)

print(cos_scores.diag())

diagonal = cos_scores.diag().view(feat_2d.size(0), 1)
print(diagonal)

d1 = diagonal.expand_as(cos_scores)
print(d1)

I = torch.eye(cos_scores.size(0))
print(I)


torch.Size([2, 3])
tensor([[-0.8462, -1.7038],
        [ 0.8599,  2.6345]])
tensor([-0.8462,  2.6345])
tensor([[-0.8462],
        [ 2.6345]])
tensor([[-0.8462, -0.8462],
        [ 2.6345,  2.6345]])
tensor([[1., 0.],
        [0., 1.]])


## Broadcasting +-

In [8]:
import numpy as np

subject_idx = np.array([0, 1, 3, 2])[:, None]
print(subject_idx.shape)

seq_len = 3
subject_idx = subject_idx.repeat(seq_len, axis=-1)
print(subject_idx, subject_idx.shape)


subject_idx = torch.tensor([0, 1, 3, 2])[:, None]
print(subject_idx.shape)

# subject_idx.repeat(seq_len, axis=-1)
# one_hot_speaker_vector = 

(4, 1)
[[0 0 0]
 [1 1 1]
 [3 3 3]
 [2 2 2]] (4, 3)
torch.Size([4, 1])


In [17]:
index = 0

subject_idx_one_hot = torch.zeros((1, 8), dtype=torch.float32)
subject_idx_one_hot[:, index] = 1

print(subject_idx_one_hot, subject_idx_one_hot.shape)

subject_idx_one_hot = subject_idx_one_hot.repeat((2, 3, 1))
print(subject_idx_one_hot, subject_idx_one_hot.shape)

tensor([[1., 0., 0., 0., 0., 0., 0., 0.]]) torch.Size([1, 8])
tensor([[[1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0.]]]) torch.Size([2, 3, 8])


## Masked filled

In [ ]:
import cv2

src_img = "/home/haimingzhang/Research/Face/FaceFormer/FaceFormer/data/id00002/obama_weekly_023/face_image/000000.jpg"
mask_img = "/home/haimingzhang/Research/Face/FaceFormer/FaceFormer/data/id00002/obama_weekly_023/mouth_mask/000000.png"

src_img = cv2.resize(cv2.imread(src_img, cv2.IMREAD_UNCHANGED), (192, 192))
